module EnergyVarInTransferModule

    use NoahowpmpIOType
    use NoahowpmpType

    implicit none
  
  contains
  
  subroutine EnergyVarInTransfer(noahowpmp, NoahowpmpIO)

    implicit none

    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO
    type(noahowp_type),     intent(inout) :: noahowpmp

    associate(ix   => NoahowpmpIO%ix, &
              iy   => NoahowpmpIO%iy)

    noahowpmp%energy%TV = NoahowpmpIO%TV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TG = NoahowpmpIO%TG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FCEV = NoahowpmpIO%FCEV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FCTR = NoahowpmpIO%FCTR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%IGS = NoahowpmpIO%IGS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FROZEN_CANOPY = NoahowpmpIO%FROZEN_CANOPY(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FROZEN_GROUND = NoahowpmpIO%FROZEN_GROUND(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%IMELT(:) = NoahowpmpIO%IMELT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%STC(:) = NoahowpmpIO%STC(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%DF(:) = NoahowpmpIO%DF(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%HCPCT(:) = NoahowpmpIO%HCPCT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FACT(:) = NoahowpmpIO%FACT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%PAHV = NoahowpmpIO%PAHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PAHG = NoahowpmpIO%PAHG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PAHB = NoahowpmpIO%PAHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PAH = NoahowpmpIO%PAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUSS = NoahowpmpIO%TAUSS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FAGE = NoahowpmpIO%FAGE(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ALB = NoahowpmpIO%ALB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ALBOLD = NoahowpmpIO%ALBOLD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ALBD(:) = NoahowpmpIO%ALBD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%ALBI(:) = NoahowpmpIO%ALBI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%ALBGRD(:) = NoahowpmpIO%ALBGRD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%ALBGRI(:) = NoahowpmpIO%ALBGRI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%ALBSND(:) = NoahowpmpIO%ALBSND(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%ALBSNI(:) = NoahowpmpIO%ALBSNI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FABD(:) = NoahowpmpIO%FABD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FABI(:) = NoahowpmpIO%FABI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FTDD(:) = NoahowpmpIO%FTDD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FTDI(:) = NoahowpmpIO%FTDI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FTID(:) = NoahowpmpIO%FTID(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FTII(:) = NoahowpmpIO%FTII(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FREVD(:) = NoahowpmpIO%FREVD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FREVI(:) = NoahowpmpIO%FREVI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FREGD(:) = NoahowpmpIO%FREGD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%FREGI(:) = NoahowpmpIO%FREGI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%RHO(:) = NoahowpmpIO%RHO(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%TAU(:) = NoahowpmpIO%TAU(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%energy%COSZ = NoahowpmpIO%COSZ(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%COSZ_HORIZ = NoahowpmpIO%COSZ_HORIZ(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%BGAP = NoahowpmpIO%BGAP(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%WGAP = NoahowpmpIO%WGAP(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSUN = NoahowpmpIO%FSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSHA = NoahowpmpIO%FSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LAISUN = NoahowpmpIO%LAISUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LAISHA = NoahowpmpIO%LAISHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PARSUN = NoahowpmpIO%PARSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PARSHA = NoahowpmpIO%PARSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SAV = NoahowpmpIO%SAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SAG = NoahowpmpIO%SAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSA = NoahowpmpIO%FSA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSR = NoahowpmpIO%FSR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSRV = NoahowpmpIO%FSRV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSRG = NoahowpmpIO%FSRG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAH = NoahowpmpIO%TAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EAH = NoahowpmpIO%EAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ZPD = NoahowpmpIO%ZPD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Z0MG = NoahowpmpIO%Z0MG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Z0M = NoahowpmpIO%Z0M(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ZLVL = NoahowpmpIO%ZLVL(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CMV = NoahowpmpIO%CMV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CMB = NoahowpmpIO%CMB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CM = NoahowpmpIO%CM(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CH = NoahowpmpIO%CH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TGB = NoahowpmpIO%TGB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%QSFC = NoahowpmpIO%QSFC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EMV = NoahowpmpIO%EMV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EMG = NoahowpmpIO%EMG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%GAMMAV = NoahowpmpIO%GAMMAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%GAMMAG = NoahowpmpIO%GAMMAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EVC = NoahowpmpIO%EVC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%IRC = NoahowpmpIO%IRC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%IRG = NoahowpmpIO%IRG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SHC = NoahowpmpIO%SHC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SHG = NoahowpmpIO%SHG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SHB = NoahowpmpIO%SHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EVG = NoahowpmpIO%EVG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EVB = NoahowpmpIO%EVB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TR = NoahowpmpIO%TR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%GH = NoahowpmpIO%GH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%GHB = NoahowpmpIO%GHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%GHV = NoahowpmpIO%GHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%T2MV = NoahowpmpIO%T2MV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHLEAF = NoahowpmpIO%CHLEAF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHUC = NoahowpmpIO%CHUC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHV2 = NoahowpmpIO%CHV2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHB2 = NoahowpmpIO%CHB2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Q2V = NoahowpmpIO%Q2V(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LATHEAV = NoahowpmpIO%LATHEAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LATHEAG = NoahowpmpIO%LATHEAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LATHEA = NoahowpmpIO%LATHEA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%RSURF = NoahowpmpIO%RSURF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%RHSUR = NoahowpmpIO%RHSUR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUXV = NoahowpmpIO%TAUXV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUYV = NoahowpmpIO%TAUYV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUXB = NoahowpmpIO%TAUXB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUYB = NoahowpmpIO%TAUYB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUX = NoahowpmpIO%TAUX(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TAUY = NoahowpmpIO%TAUY(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CAH2 = NoahowpmpIO%CAH2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EHB2 = NoahowpmpIO%EHB2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%T2MB = NoahowpmpIO%T2MB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Q2B = NoahowpmpIO%Q2B(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TGV = NoahowpmpIO%TGV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHV = NoahowpmpIO%CHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%RSSUN = NoahowpmpIO%RSSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%RSSHA = NoahowpmpIO%RSSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%RB = NoahowpmpIO%RB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FIRA = NoahowpmpIO%FIRA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FSH = NoahowpmpIO%FSH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%FGEV = NoahowpmpIO%FGEV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TRAD = NoahowpmpIO%TRAD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%IRB = NoahowpmpIO%IRB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%SSOIL = NoahowpmpIO%SSOIL(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%T2M = NoahowpmpIO%T2M(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TS = NoahowpmpIO%TS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%CHB = NoahowpmpIO%CHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Q1 = NoahowpmpIO%Q1(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Q2E = NoahowpmpIO%Q2E(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%Z0WRF = NoahowpmpIO%Z0WRF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%EMISSI = NoahowpmpIO%EMISSI(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PSN = NoahowpmpIO%PSN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PSNSUN = NoahowpmpIO%PSNSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%PSNSHA = NoahowpmpIO%PSNSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%APAR = NoahowpmpIO%APAR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%QMELT = NoahowpmpIO%QMELT(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%LH = NoahowpmpIO%LH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%TGS = NoahowpmpIO%TGS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%energy%ICE = NoahowpmpIO%ICE(NoahowpmpIO%ix,NoahowpmpIO%iy) 

    end associate

  end subroutine

end module EnergyVarInTransferModule