module EnergyVarInTransferModule

    use NoahowpmpIOVarType
    use NoahowpType

    implicit none
  
  contains
  
  subroutine EnergyVarInTransfer(noahowpmp, NoahowpmpIO)

    implicit none

    type(NoahmpIO_type), intent(inout) :: NoahowpmpIO
    type(noahmp_type),   intent(inout) :: noahowpmp

    associate(ix   => NoahowpmpIO%ix, &
              iy   => NoahowpmpIO%iy)

    noahowpmp%TV = NoahowpmpIO%TV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TG = NoahowpmpIO%TG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FCEV = NoahowpmpIO%FCEV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FCTR = NoahowpmpIO%FCTR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%IGS = NoahowpmpIO%IGS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FROZEN_CANOPY = NoahowpmpIO%FROZEN_CANOPY(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FROZEN_GROUND = NoahowpmpIO%FROZEN_GROUND(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%IMELT(:) = NoahowpmpIO%IMELT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%STC(:) = NoahowpmpIO%STC(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%DF(:) = NoahowpmpIO%DF(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%HCPCT(:) = NoahowpmpIO%HCPCT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FACT(:) = NoahowpmpIO%FACT(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%PAHV = NoahowpmpIO%PAHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PAHG = NoahowpmpIO%PAHG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PAHB = NoahowpmpIO%PAHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PAH = NoahowpmpIO%PAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUSS = NoahowpmpIO%TAUSS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FAGE = NoahowpmpIO%FAGE(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ALB = NoahowpmpIO%ALB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ALBOLD = NoahowpmpIO%ALBOLD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ALBD(:) = NoahowpmpIO%ALBD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%ALBI(:) = NoahowpmpIO%ALBI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%ALBGRD(:) = NoahowpmpIO%ALBGRD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%ALBGRI(:) = NoahowpmpIO%ALBGRI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%ALBSND(:) = NoahowpmpIO%ALBSND(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%ALBSNI(:) = NoahowpmpIO%ALBSNI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FABD(:) = NoahowpmpIO%FABD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FABI(:) = NoahowpmpIO%FABI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FTDD(:) = NoahowpmpIO%FTDD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FTDI(:) = NoahowpmpIO%FTDI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FTID(:) = NoahowpmpIO%FTID(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FTII(:) = NoahowpmpIO%FTII(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FREVD(:) = NoahowpmpIO%FREVD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FREVI(:) = NoahowpmpIO%FREVI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FREGD(:) = NoahowpmpIO%FREGD(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%FREGI(:) = NoahowpmpIO%FREGI(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%RHO(:) = NoahowpmpIO%RHO(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%TAU(:) = NoahowpmpIO%TAU(NoahowpmpIO%ix,NoahowpmpIO%iy,:)
    noahowpmp%COSZ = NoahowpmpIO%COSZ(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%COSZ_HORIZ = NoahowpmpIO%COSZ_HORIZ(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%BGAP = NoahowpmpIO%BGAP(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%WGAP = NoahowpmpIO%WGAP(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSUN = NoahowpmpIO%FSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSHA = NoahowpmpIO%FSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LAISUN = NoahowpmpIO%LAISUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LAISHA = NoahowpmpIO%LAISHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PARSUN = NoahowpmpIO%PARSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PARSHA = NoahowpmpIO%PARSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SAV = NoahowpmpIO%SAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SAG = NoahowpmpIO%SAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSA = NoahowpmpIO%FSA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSR = NoahowpmpIO%FSR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSRV = NoahowpmpIO%FSRV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSRG = NoahowpmpIO%FSRG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAH = NoahowpmpIO%TAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EAH = NoahowpmpIO%EAH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ZPD = NoahowpmpIO%ZPD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Z0MG = NoahowpmpIO%Z0MG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Z0M = NoahowpmpIO%Z0M(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ZLVL = NoahowpmpIO%ZLVL(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CMV = NoahowpmpIO%CMV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CMB = NoahowpmpIO%CMB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CM = NoahowpmpIO%CM(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CH = NoahowpmpIO%CH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TGB = NoahowpmpIO%TGB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%QSFC = NoahowpmpIO%QSFC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EMV = NoahowpmpIO%EMV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EMG = NoahowpmpIO%EMG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%GAMMAV = NoahowpmpIO%GAMMAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%GAMMAG = NoahowpmpIO%GAMMAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EVC = NoahowpmpIO%EVC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%IRC = NoahowpmpIO%IRC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%IRG = NoahowpmpIO%IRG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SHC = NoahowpmpIO%SHC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SHG = NoahowpmpIO%SHG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SHB = NoahowpmpIO%SHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EVG = NoahowpmpIO%EVG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EVB = NoahowpmpIO%EVB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TR = NoahowpmpIO%TR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%GH = NoahowpmpIO%GH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%GHB = NoahowpmpIO%GHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%GHV = NoahowpmpIO%GHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%T2MV = NoahowpmpIO%T2MV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHLEAF = NoahowpmpIO%CHLEAF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHUC = NoahowpmpIO%CHUC(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHV2 = NoahowpmpIO%CHV2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHB2 = NoahowpmpIO%CHB2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Q2V = NoahowpmpIO%Q2V(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LATHEAV = NoahowpmpIO%LATHEAV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LATHEAG = NoahowpmpIO%LATHEAG(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LATHEA = NoahowpmpIO%LATHEA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%RSURF = NoahowpmpIO%RSURF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%RHSUR = NoahowpmpIO%RHSUR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUXV = NoahowpmpIO%TAUXV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUYV = NoahowpmpIO%TAUYV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUXB = NoahowpmpIO%TAUXB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUYB = NoahowpmpIO%TAUYB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUX = NoahowpmpIO%TAUX(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TAUY = NoahowpmpIO%TAUY(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CAH2 = NoahowpmpIO%CAH2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EHB2 = NoahowpmpIO%EHB2(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%T2MB = NoahowpmpIO%T2MB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Q2B = NoahowpmpIO%Q2B(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TGV = NoahowpmpIO%TGV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHV = NoahowpmpIO%CHV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%RSSUN = NoahowpmpIO%RSSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%RSSHA = NoahowpmpIO%RSSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%RB = NoahowpmpIO%RB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FIRA = NoahowpmpIO%FIRA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FSH = NoahowpmpIO%FSH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%FGEV = NoahowpmpIO%FGEV(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TRAD = NoahowpmpIO%TRAD(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%IRB = NoahowpmpIO%IRB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%SSOIL = NoahowpmpIO%SSOIL(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%T2M = NoahowpmpIO%T2M(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TS = NoahowpmpIO%TS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%CHB = NoahowpmpIO%CHB(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Q1 = NoahowpmpIO%Q1(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Q2E = NoahowpmpIO%Q2E(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%Z0WRF = NoahowpmpIO%Z0WRF(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%EMISSI = NoahowpmpIO%EMISSI(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PSN = NoahowpmpIO%PSN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PSNSUN = NoahowpmpIO%PSNSUN(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%PSNSHA = NoahowpmpIO%PSNSHA(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%APAR = NoahowpmpIO%APAR(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%QMELT = NoahowpmpIO%QMELT(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%LH = NoahowpmpIO%LH(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%TGS = NoahowpmpIO%TGS(NoahowpmpIO%ix,NoahowpmpIO%iy)
    noahowpmp%ICE = NoahowpmpIO%ICE(NoahowpmpIO%ix,NoahowpmpIO%iy) 

    end associate

  end subroutine

end module EnergyVarInTransferModule