module NoahmpIOVarInitModule

  use NoahowpmpIOVarType
  
  implicit none
  
  contains

  subroutine NoahmpIOVarInitDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    call DomainTypeAllocate(NoahowpmpIO)
    call DomainTypeDefault(NoahowpmpIO)
    call EnergyTypeAllocate(NoahowpmpIO)
    call EnergyTypeDefault(NoahowpmpIO)
    call ForcingTypeAllocate(NoahowpmpIO)
    call ForcingTypeDefault(NoahowpmpIO)
    call LevelsTypeAllocate(NoahowpmpIO)
    call LevelsTypeDefault(NoahowpmpIO)
    call OptionsTypeAllocate(NoahowpmpIO)
    call OptionsTypeDefault(NoahowpmpIO)
    call ParametersTypeAllocate(NoahowpmpIO)
    call ParametersTypeDefault(NoahowpmpIO)
    call WaterTypeAllocate(NoahowpmpIO)
    call WaterTypeDefault(NoahowpmpIO)

  end subroutine NoahmpIOVarInitDefault

  subroutine WaterTypeAllocate(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%qinsur)) allocate(NoahowpmpIO%qinsur(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%qseva)) allocate(NoahowpmpIO%qseva(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVAPOTRANS)) allocate(NoahowpmpIO%EVAPOTRANS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsrf)) allocate(NoahowpmpIO%runsrf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsub)) allocate(NoahowpmpIO%runsub(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%qdrain)) allocate(NoahowpmpIO%qdrain(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%zwt)) allocate(NoahowpmpIO%zwt(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%smcwtd)) allocate(NoahowpmpIO%smcwtd(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%deeprech)) allocate(NoahowpmpIO%deeprech(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%fcrmax)) allocate(NoahowpmpIO%fcrmax(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%snoflow)) allocate(NoahowpmpIO%snoflow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%pddum)) allocate(NoahowpmpIO%pddum(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FACC)) allocate(NoahowpmpIO%FACC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%sicemax)) allocate(NoahowpmpIO%sicemax(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FB_snow)) allocate(NoahowpmpIO%FB_snow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%rain)) allocate(NoahowpmpIO%rain(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%snow)) allocate(NoahowpmpIO%snow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%bdfall)) allocate(NoahowpmpIO%bdfall(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FP)) allocate(NoahowpmpIO%FP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%canliq)) allocate(NoahowpmpIO%canliq(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%canice)) allocate(NoahowpmpIO%canice(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FWET)) allocate(NoahowpmpIO%FWET(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMC)) allocate(NoahowpmpIO%CMC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QINTR)) allocate(NoahowpmpIO%QINTR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDRIPR)) allocate(NoahowpmpIO%QDRIPR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QTHROR)) allocate(NoahowpmpIO%QTHROR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QINTS)) allocate(NoahowpmpIO%QINTS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDRIPS)) allocate(NoahowpmpIO%QDRIPS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QTHROS)) allocate(NoahowpmpIO%QTHROS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QRAIN)) allocate(NoahowpmpIO%QRAIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNOW)) allocate(NoahowpmpIO%QSNOW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNOWHIN)) allocate(NoahowpmpIO%SNOWHIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ECAN)) allocate(NoahowpmpIO%ECAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ETRAN)) allocate(NoahowpmpIO%ETRAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNFRO)) allocate(NoahowpmpIO%QSNFRO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNSUB)) allocate(NoahowpmpIO%QSNSUB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNOWH)) allocate(NoahowpmpIO%SNOWH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNEQV)) allocate(NoahowpmpIO%SNEQV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNEQVO)) allocate(NoahowpmpIO%SNEQVO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BDSNO)) allocate(NoahowpmpIO%BDSNO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNBOT)) allocate(NoahowpmpIO%QSNBOT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING)) allocate(NoahowpmpIO%PONDING(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING1)) allocate(NoahowpmpIO%PONDING1(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING2)) allocate(NoahowpmpIO%PONDING2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QVAP)) allocate(NoahowpmpIO%QVAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDEW)) allocate(NoahowpmpIO%QDEW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSDEW)) allocate(NoahowpmpIO%QSDEW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%WSLAKE)) allocate(NoahowpmpIO%WSLAKE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsrf_dt)) allocate(NoahowpmpIO%runsrf_dt(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ASAT)) allocate(NoahowpmpIO%ASAT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ISNOW)) allocate(NoahowpmpIO%ISNOW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%smc)) allocate(NoahowpmpIO%smc(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%smc_init)) allocate(NoahowpmpIO%smc_init(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%sice)) allocate(NoahowpmpIO%sice(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%sh2o)) allocate(NoahowpmpIO%sh2o(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%etrani)) allocate(NoahowpmpIO%etrani(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%BTRANI)) allocate(NoahowpmpIO%BTRANI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%wcnd)) allocate(NoahowpmpIO%wcnd(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%fcr)) allocate(NoahowpmpIO%fcr(NoahowpmpIO%n_x,NoahowpmpIO%n_y,,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%FICEOLD)) allocate(NoahowpmpIO%FICEOLD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNICE)) allocate(NoahowpmpIO%SNICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNLIQ)) allocate(NoahowpmpIO%SNLIQ(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNICEV)) allocate(NoahowpmpIO%SNICEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNLIQV)) allocate(NoahowpmpIO%SNLIQV(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%FICE)) allocate(NoahowpmpIO%FICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%EPORE)) allocate(NoahowpmpIO%EPORE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%FSNO)) allocate(NoahowpmpIO%FSNO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BTRAN)) allocate(NoahowpmpIO%BTRAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine WaterTypeDefault(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%qinsur(:,:) = huge(1.0)
    NoahowpmpIO%qseva(:,:) = huge(1.0)
    NoahowpmpIO%EVAPOTRANS(:,:) = huge(1.0)
    NoahowpmpIO%runsrf(:,:) = huge(1.0)
    NoahowpmpIO%runsub(:,:) = huge(1.0)
    NoahowpmpIO%qdrain(:,:) = huge(1.0)
    NoahowpmpIO%zwt(:,:) = huge(1.0)
    NoahowpmpIO%smcwtd(:,:) = huge(1.0)
    NoahowpmpIO%deeprech(:,:) = huge(1.0)
    NoahowpmpIO%fcrmax(:,:) = huge(1.0)
    NoahowpmpIO%snoflow(:,:) = huge(1.0)
    NoahowpmpIO%pddum(:,:) = huge(1.0)
    NoahowpmpIO%FACC(:,:) = huge(1.0)
    NoahowpmpIO%sicemax(:,:) = huge(1.0)
    NoahowpmpIO%FB_snow(:,:) = huge(1.0)
    NoahowpmpIO%rain(:,:) = huge(1.0)
    NoahowpmpIO%snow(:,:) = huge(1.0)
    NoahowpmpIO%bdfall(:,:) = huge(1.0)
    NoahowpmpIO%FP(:,:) = huge(1.0)
    NoahowpmpIO%canliq(:,:) = huge(1.0)
    NoahowpmpIO%canice(:,:) = huge(1.0)
    NoahowpmpIO%FWET(:,:) = huge(1.0)
    NoahowpmpIO%CMC(:,:) = huge(1.0)
    NoahowpmpIO%QINTR(:,:) = huge(1.0)
    NoahowpmpIO%QDRIPR(:,:) = huge(1.0)
    NoahowpmpIO%QTHROR(:,:) = huge(1.0)
    NoahowpmpIO%QINTS(:,:) = huge(1.0)
    NoahowpmpIO%QDRIPS(:,:) = huge(1.0)
    NoahowpmpIO%QTHROS(:,:) = huge(1.0)
    NoahowpmpIO%QRAIN(:,:) = huge(1.0)
    NoahowpmpIO%QSNOW(:,:) = huge(1.0)
    NoahowpmpIO%SNOWHIN(:,:) = huge(1.0)
    NoahowpmpIO%ECAN(:,:) = huge(1.0)
    NoahowpmpIO%ETRAN(:,:) = huge(1.0)
    NoahowpmpIO%QSNFRO(:,:) = huge(1.0)
    NoahowpmpIO%QSNSUB(:,:) = huge(1.0)
    NoahowpmpIO%SNOWH(:,:) = huge(1.0)
    NoahowpmpIO%SNEQV(:,:) = huge(1.0)
    NoahowpmpIO%SNEQVO(:,:) = huge(1.0)
    NoahowpmpIO%BDSNO(:,:) = huge(1.0)
    NoahowpmpIO%QSNBOT(:,:) = huge(1.0)
    NoahowpmpIO%PONDING(:,:) = huge(1.0)
    NoahowpmpIO%PONDING1(:,:) = huge(1.0)
    NoahowpmpIO%PONDING2(:,:) = huge(1.0)
    NoahowpmpIO%QVAP(:,:) = huge(1.0)
    NoahowpmpIO%QDEW(:,:) = huge(1.0)
    NoahowpmpIO%QSDEW(:,:) = huge(1.0)
    NoahowpmpIO%WSLAKE(:,:) = huge(1.0)
    NoahowpmpIO%runsrf_dt(:,:) = huge(1.0)
    NoahowpmpIO%ASAT(:,:) = huge(1.0)
    NoahowpmpIO%ISNOW(:,:) = huge(1)
    NoahowpmpIO%smc(:,:,:) = huge(1.0)
    NoahowpmpIO%smc_init(:,:,:) = huge(1.0)
    NoahowpmpIO%sice(:,:,:) = huge(1.0)
    NoahowpmpIO%sh2o(:,:,:) = huge(1.0)
    NoahowpmpIO%etrani(:,:,:) = huge(1.0)
    NoahowpmpIO%BTRANI(:,:,:) = huge(1.0)
    NoahowpmpIO%wcnd(:,:,:) = huge(1.0)
    NoahowpmpIO%fcr(:,:,:) = huge(1.0)
    NoahowpmpIO%FICEOLD(:,:,:) = huge(1.0)
    NoahowpmpIO%SNICE(:,:,:) = huge(1.0)
    NoahowpmpIO%SNLIQ(:,:,:) = huge(1.0)
    NoahowpmpIO%SNICEV(:,:,:) = huge(1.0)
    NoahowpmpIO%SNLIQV(:,:,:) = huge(1.0)
    NoahowpmpIO%FICE(:,:,:) = huge(1.0)
    NoahowpmpIO%EPORE(:,:,:) = huge(1.0)
    NoahowpmpIO%FSNO(:,:) = huge(1.0)
    NoahowpmpIO%BTRAN(:,:) = huge(1.0)

  end subroutine

  subroutine ParametersTypeAllocate(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%bexp)) allocate(NoahowpmpIO%bexp(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcmax)) allocate(NoahowpmpIO%smcmax(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcwlt)) allocate(NoahowpmpIO%smcwlt(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcref)) allocate(NoahowpmpIO%smcref(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%dksat)) allocate(NoahowpmpIO%dksat(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%dwsat)) allocate(NoahowpmpIO%dwsat(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%psisat)) allocate(NoahowpmpIO%psisat(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%bvic)) allocate(NoahowpmpIO%bvic(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%AXAJ)) allocate(NoahowpmpIO%AXAJ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BXAJ)) allocate(NoahowpmpIO%BXAJ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%XXAJ)) allocate(NoahowpmpIO%XXAJ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BBVIC)) allocate(NoahowpmpIO%BBVIC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%G)) allocate(NoahowpmpIO%G(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QUARTZ)) allocate(NoahowpmpIO%QUARTZ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%kdt)) allocate(NoahowpmpIO%kdt(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%frzx)) allocate(NoahowpmpIO%frzx(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ZWT_INIT)) allocate(NoahowpmpIO%ZWT_INIT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%urban_flag)) allocate(NoahowpmpIO%urban_flag(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LAIM)) allocate(NoahowpmpIO%LAIM(NoahowpmpIO%n_x,NoahowpmpIO%n_y,12))
    if(.NOT.allocated(NoahowpmpIO%SAIM)) allocate(NoahowpmpIO%SAIM(NoahowpmpIO%n_x,NoahowpmpIO%n_y,12))
    if(.NOT.allocated(NoahowpmpIO%LAI)) allocate(NoahowpmpIO%LAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SAI)) allocate(NoahowpmpIO%SAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CH2OP)) allocate(NoahowpmpIO%CH2OP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%NROOT)) allocate(NoahowpmpIO%NROOT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%HVT)) allocate(NoahowpmpIO%HVT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%HVB)) allocate(NoahowpmpIO%HVB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TMIN)) allocate(NoahowpmpIO%TMIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHDFAC)) allocate(NoahowpmpIO%SHDFAC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHDMAX)) allocate(NoahowpmpIO%SHDMAX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0MVT)) allocate(NoahowpmpIO%Z0MVT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RC)) allocate(NoahowpmpIO%RC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%XL)) allocate(NoahowpmpIO%XL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BP)) allocate(NoahowpmpIO%BP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FOLNMX)) allocate(NoahowpmpIO%FOLNMX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QE25)) allocate(NoahowpmpIO%QE25(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%VCMX25)) allocate(NoahowpmpIO%VCMX25(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%MP)) allocate(NoahowpmpIO%MP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RGL)) allocate(NoahowpmpIO%RGL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSMIN)) allocate(NoahowpmpIO%RSMIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%HS)) allocate(NoahowpmpIO%HS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%AKC)) allocate(NoahowpmpIO%AKC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%AKO)) allocate(NoahowpmpIO%AKO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%AVCMX)) allocate(NoahowpmpIO%AVCMX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSMAX)) allocate(NoahowpmpIO%RSMAX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CWP)) allocate(NoahowpmpIO%CWP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%C3PSN)) allocate(NoahowpmpIO%C3PSN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%DLEAF)) allocate(NoahowpmpIO%DLEAF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%KC25)) allocate(NoahowpmpIO%KC25(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%KO25)) allocate(NoahowpmpIO%KO25(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ELAI)) allocate(NoahowpmpIO%ELAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ESAI)) allocate(NoahowpmpIO%ESAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%VAI)) allocate(NoahowpmpIO%VAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%VEG)) allocate(NoahowpmpIO%VEG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FVEG)) allocate(NoahowpmpIO%FVEG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RHOL)) allocate(NoahowpmpIO%RHOL(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%RHOS)) allocate(NoahowpmpIO%RHOS(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUL)) allocate(NoahowpmpIO%TAUL(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUS)) allocate(NoahowpmpIO%TAUS(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%MFSNO)) allocate(NoahowpmpIO%MFSNO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ALBSAT)) allocate(NoahowpmpIO%ALBSAT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBDRY)) allocate(NoahowpmpIO%ALBDRY(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBICE)) allocate(NoahowpmpIO%ALBICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBLAK)) allocate(NoahowpmpIO%ALBLAK(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%OMEGAS)) allocate(NoahowpmpIO%OMEGAS(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%EG)) allocate(NoahowpmpIO%EG(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TOPT)) allocate(NoahowpmpIO%TOPT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine ParametersTypeDefault(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%bexp(:,:,:) = huge(1.0)
    NoahowpmpIO%smcmax(:,:,:) = huge(1.0)
    NoahowpmpIO%smcwlt(:,:,:) = huge(1.0)
    NoahowpmpIO%smcref(:,:,:) = huge(1.0)
    NoahowpmpIO%dksat(:,:,:) = huge(1.0)
    NoahowpmpIO%dwsat(:,:,:) = huge(1.0)
    NoahowpmpIO%psisat(:,:,:) = huge(1.0)
    NoahowpmpIO%bvic(:,:) = huge(1.0)
    NoahowpmpIO%AXAJ(:,:) = huge(1.0)
    NoahowpmpIO%BXAJ(:,:) = huge(1.0)
    NoahowpmpIO%XXAJ(:,:) = huge(1.0)
    NoahowpmpIO%BBVIC(:,:) = huge(1.0)
    NoahowpmpIO%G(:,:) = huge(1.0)
    NoahowpmpIO%QUARTZ(:,:) = huge(1.0)
    NoahowpmpIO%kdt(:,:) = huge(1.0)
    NoahowpmpIO%refkdt = huge(1.0)
    NoahowpmpIO%refdk = huge(1.0)
    NoahowpmpIO%csoil = huge(1.0)
    NoahowpmpIO%Z0 = huge(1.0)
    NoahowpmpIO%CZIL = huge(1.0)
    NoahowpmpIO%ZBOT = huge(1.0)
    NoahowpmpIO%frzx(:,:) = huge(1.0)
    NoahowpmpIO%slope = huge(1.0)
    NoahowpmpIO%timean = huge(1.0)
    NoahowpmpIO%fsatmx = huge(1.0)
    NoahowpmpIO%ZWT_INIT(:,:) = huge(1.0)
    NoahowpmpIO%urban_flag(:,:) = .FALSE.
    NoahowpmpIO%LAIM(:,:,:) = huge(1.0)
    NoahowpmpIO%SAIM(:,:,:) = huge(1.0)
    NoahowpmpIO%LAI(:,:) = huge(1.0)
    NoahowpmpIO%SAI(:,:) = huge(1.0)
    NoahowpmpIO%CH2OP(:,:) = huge(1.0)
    NoahowpmpIO%NROOT(:,:) = huge(1)
    NoahowpmpIO%HVT(:,:) = huge(1.0)
    NoahowpmpIO%HVB(:,:) = huge(1.0)
    NoahowpmpIO%TMIN(:,:) = huge(1.0)
    NoahowpmpIO%SHDFAC(:,:) = huge(1.0)
    NoahowpmpIO%SHDMAX(:,:) = huge(1.0)
    NoahowpmpIO%Z0MVT(:,:) = huge(1.0)
    NoahowpmpIO%RC(:,:) = huge(1.0)
    NoahowpmpIO%XL(:,:) = huge(1.0)
    NoahowpmpIO%BP(:,:) = huge(1.0)
    NoahowpmpIO%FOLNMX(:,:) = huge(1.0)
    NoahowpmpIO%QE25(:,:) = huge(1.0)
    NoahowpmpIO%VCMX25(:,:) = huge(1.0)
    NoahowpmpIO%MP(:,:) = huge(1.0)
    NoahowpmpIO%RGL(:,:) = huge(1.0)
    NoahowpmpIO%RSMIN(:,:) = huge(1.0)
    NoahowpmpIO%HS(:,:) = huge(1.0)
    NoahowpmpIO%AKC(:,:) = huge(1.0)
    NoahowpmpIO%AKO(:,:) = huge(1.0)
    NoahowpmpIO%AVCMX(:,:) = huge(1.0)
    NoahowpmpIO%RSMAX(:,:) = huge(1.0)
    NoahowpmpIO%CWP(:,:) = huge(1.0)
    NoahowpmpIO%C3PSN(:,:) = huge(1.0)
    NoahowpmpIO%DLEAF(:,:) = huge(1.0)
    NoahowpmpIO%KC25(:,:) = huge(1.0)
    NoahowpmpIO%KO25(:,:) = huge(1.0)
    NoahowpmpIO%ELAI(:,:) = huge(1.0)
    NoahowpmpIO%ESAI(:,:) = huge(1.0)
    NoahowpmpIO%VAI(:,:) = huge(1.0)
    NoahowpmpIO%VEG(:,:) = .FALSE.
    NoahowpmpIO%FVEG(:,:) = huge(1.0)
    NoahowpmpIO%RHOL(:,:,:) = huge(1.0)
    NoahowpmpIO%RHOS(:,:,:) = huge(1.0)
    NoahowpmpIO%TAUL(:,:,:) = huge(1.0)
    NoahowpmpIO%TAUS(:,:,:) = huge(1.0)
    NoahowpmpIO%ISURBAN = huge(1)
    NoahowpmpIO%ISWATER = huge(1)
    NoahowpmpIO%ISBARREN = huge(1)
    NoahowpmpIO%ISICE = huge(1)
    NoahowpmpIO%ISCROP = huge(1)
    NoahowpmpIO%EBLFOREST = huge(1)
    NoahowpmpIO%NATURAL = huge(1)
    NoahowpmpIO%LOW_DENSITY_RESIDENTIAL = huge(1)
    NoahowpmpIO%HIGH_DENSITY_RESIDENTIAL = huge(1)
    NoahowpmpIO%HIGH_INTENSITY_INDUSTRIAL = huge(1)
    NoahowpmpIO%SB = huge(1.0)
    NoahowpmpIO%VKC = huge(1.0)
    NoahowpmpIO%TFRZ = huge(1.0)
    NoahowpmpIO%HSUB = huge(1.0)
    NoahowpmpIO%HVAP = huge(1.0)
    NoahowpmpIO%HFUS = huge(1.0)
    NoahowpmpIO%CWAT = huge(1.0)
    NoahowpmpIO%CICE = huge(1.0)
    NoahowpmpIO%CPAIR = huge(1.0)
    NoahowpmpIO%TKWAT = huge(1.0)
    NoahowpmpIO%TKICE = huge(1.0)
    NoahowpmpIO%TKAIR = huge(1.0)
    NoahowpmpIO%RAIR = huge(1.0)
    NoahowpmpIO%RW = huge(1.0)
    NoahowpmpIO%DENH2O = huge(1.0)
    NoahowpmpIO%DENICE = huge(1.0)
    NoahowpmpIO%THKW = huge(1.0)
    NoahowpmpIO%THKO = huge(1.0)
    NoahowpmpIO%THKQTZ = huge(1.0)
    NoahowpmpIO%SSI = huge(1.0)
    NoahowpmpIO%MFSNO(:,:) = huge(1.0)
    NoahowpmpIO%Z0SNO = huge(1.0)
    NoahowpmpIO%SWEMX = huge(1.0)
    NoahowpmpIO%TAU0 = huge(1.0)
    NoahowpmpIO%GRAIN_GROWTH = huge(1.0)
    NoahowpmpIO%EXTRA_GROWTH = huge(1.0)
    NoahowpmpIO%DIRT_SOOT = huge(1.0)
    NoahowpmpIO%BATS_COSZ = huge(1.0)
    NoahowpmpIO%BATS_VIS_NEW = huge(1.0)
    NoahowpmpIO%BATS_NIR_NEW = huge(1.0)
    NoahowpmpIO%BATS_VIS_AGE = huge(1.0)
    NoahowpmpIO%BATS_NIR_AGE = huge(1.0)
    NoahowpmpIO%BATS_VIS_DIR = huge(1.0)
    NoahowpmpIO%BATS_NIR_DIR = huge(1.0)
    NoahowpmpIO%RSURF_SNOW = huge(1.0)
    NoahowpmpIO%RSURF_EXP = huge(1.0)
    NoahowpmpIO%ALBSAT(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBDRY(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBICE(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBLAK(:,:,:) = huge(1.0)
    NoahowpmpIO%OMEGAS(:,:,:) = huge(1.0)
    NoahowpmpIO%BETADS = huge(1.0)
    NoahowpmpIO%BETAIS = huge(1.0)
    NoahowpmpIO%EG(:,:,:) = huge(1.0)
    NoahowpmpIO%WSLMAX = huge(1.0)
    NoahowpmpIO%max_liq_mass_fraction = huge(1.0)
    NoahowpmpIO%SNOW_RET_FAC = huge(1.0)
    NoahowpmpIO%NBAND = huge(1)
    NoahowpmpIO%MPE = huge(1.0)
    NoahowpmpIO%TOPT(:,:) = huge(1.0)
    NoahowpmpIO%O2 = huge(1.0)
    NoahowpmpIO%CO2 = huge(1.0)
    NoahowpmpIO%PSIWLT = huge(1.0)
    NoahowpmpIO%TBOT = huge(1.0)
    NoahowpmpIO%GRAV = huge(1.0)
    NoahowpmpIO%rain_snow_thresh = huge(1.0)

  end subroutine

  subroutine OptionsTypeAllocate(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%opt_snf)) allocate(NoahowpmpIO%opt_snf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_run)) allocate(NoahowpmpIO%opt_run(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_drn)) allocate(NoahowpmpIO%opt_drn(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_inf)) allocate(NoahowpmpIO%opt_inf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_infdv)) allocate(NoahowpmpIO%opt_infdv(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%dveg)) allocate(NoahowpmpIO%dveg(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_alb)) allocate(NoahowpmpIO%opt_alb(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_rad)) allocate(NoahowpmpIO%opt_rad(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_sfc)) allocate(NoahowpmpIO%opt_sfc(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_crs)) allocate(NoahowpmpIO%opt_crs(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_crop)) allocate(NoahowpmpIO%opt_crop(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_stc)) allocate(NoahowpmpIO%opt_stc(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_tbot)) allocate(NoahowpmpIO%opt_tbot(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_frz)) allocate(NoahowpmpIO%opt_frz(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_btr)) allocate(NoahowpmpIO%opt_btr(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_rsf)) allocate(NoahowpmpIO%opt_rsf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_sub)) allocate(NoahowpmpIO%opt_sub(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine OptionsTypeDefault(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%opt_snf(:,:)       = huge(1)
    NoahowpmpIO%opt_run(:,:)       = huge(1)
    NoahowpmpIO%opt_drn(:,:)       = huge(1)
    NoahowpmpIO%opt_inf(:,:)       = huge(1)
    NoahowpmpIO%opt_infdv(:,:)     = huge(1)
    NoahowpmpIO%dveg(:,:)          = huge(1)
    NoahowpmpIO%opt_alb(:,:)       = huge(1)
    NoahowpmpIO%opt_rad(:,:)       = huge(1)
    NoahowpmpIO%opt_sfc(:,:)       = huge(1)
    NoahowpmpIO%opt_crs(:,:)       = huge(1)
    NoahowpmpIO%opt_crop(:,:)      = huge(1)
    NoahowpmpIO%opt_stc(:,:)       = huge(1)
    NoahowpmpIO%opt_tbot(:,:)      = huge(1)
    NoahowpmpIO%opt_frz(:,:)       = huge(1)
    NoahowpmpIO%opt_btr(:,:)       = huge(1)
    NoahowpmpIO%opt_rsf(:,:)       = huge(1)
    NoahowpmpIO%opt_sub(:,:)       = huge(1)

  end subroutine

  subroutine LevelsTypeAllocate(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%nsoil)) allocate(NoahowpmpIO%nsoil(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%nsnow)) allocate(NoahowpmpIO%nsnow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%nveg)) allocate(NoahowpmpIO%nveg(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine LevelsTypeDefault(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%nsoil(:,:)    = huge(1)
    NoahowpmpIO%nsnow(:,:)    = huge(1)
    NoahowpmpIO%nveg(:,:)     = huge(1)

  end subroutine

  subroutine ForcingTypeAllocate(Noahowp)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%SFCPRS)) allocate(NoahowpmpIO%SFCPRS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SFCTMP)) allocate(NoahowpmpIO%SFCTMP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2)) allocate(NoahowpmpIO%Q2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCP)) allocate(NoahowpmpIO%PRCP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPCONV)) allocate(NoahowpmpIO%PRCPCONV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPNONC)) allocate(NoahowpmpIO%PRCPNONC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPSHCV)) allocate(NoahowpmpIO%PRCPSHCV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPSNOW)) allocate(NoahowpmpIO%PRCPSNOW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPGRPL)) allocate(NoahowpmpIO%PRCPGRPL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPHAIL)) allocate(NoahowpmpIO%PRCPHAIL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SOLDN)) allocate(NoahowpmpIO%SOLDN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LWDN)) allocate(NoahowpmpIO%LWDN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FOLN)) allocate(NoahowpmpIO%FOLN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%O2PP)) allocate(NoahowpmpIO%O2PP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CO2PP)) allocate(NoahowpmpIO%CO2PP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%UU)) allocate(NoahowpmpIO%UU(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%VV)) allocate(NoahowpmpIO%VV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%UR)) allocate(NoahowpmpIO%UR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%THAIR)) allocate(NoahowpmpIO%THAIR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QAIR)) allocate(NoahowpmpIO%QAIR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EAIR)) allocate(NoahowpmpIO%EAIR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RHOAIR)) allocate(NoahowpmpIO%RHOAIR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FPICE)) allocate(NoahowpmpIO%FPICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SWDOWN)) allocate(NoahowpmpIO%SWDOWN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SOLAD)) allocate(NoahowpmpIO%SOLAD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%SOLAI)) allocate(NoahowpmpIO%SOLAI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))

  end subroutine ForcingTypeAllocate

  subroutine ForcingTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%SFCPRS(:,:)    = huge(1.0)
    NoahowpmpIO%SFCTMP(:,:)    = huge(1.0)
    NoahowpmpIO%Q2(:,:)        = huge(1.0)
    NoahowpmpIO%PRCP(:,:)      = huge(1.0)
    NoahowpmpIO%PRCPCONV(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPNONC(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPSHCV(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPSNOW(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPGRPL(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPHAIL(:,:)  = huge(1.0)
    NoahowpmpIO%SOLDN(:,:)     = huge(1.0)
    NoahowpmpIO%LWDN(:,:)      = huge(1.0) 
    NoahowpmpIO%FOLN(:,:)      = huge(1.0) 
    NoahowpmpIO%O2PP(:,:)      = huge(1.0) 
    NoahowpmpIO%CO2PP(:,:)     = huge(1.0) 
    NoahowpmpIO%UU(:,:)        = huge(1.0)
    NoahowpmpIO%VV(:,:)        = huge(1.0)
    NoahowpmpIO%TBOT           = huge(1.0)
    NoahowpmpIO%UR(:,:)        = huge(1.0)
    NoahowpmpIO%THAIR(:,:)     = huge(1.0)
    NoahowpmpIO%QAIR(:,:)      = huge(1.0)
    NoahowpmpIO%EAIR(:,:)      = huge(1.0)
    NoahowpmpIO%RHOAIR(:,:)    = huge(1.0)
    NoahowpmpIO%FPICE(:,:)     = huge(1.0)
    NoahowpmpIO%SWDOWN(:,:)    = huge(1.0)
    NoahowpmpIO%JULIAN         = huge(1.0)
    NoahowpmpIO%YEARLEN        = huge(1)
    NoahowpmpIO%SOLAD(:,:,:)   = huge(1.0)
    NoahowpmpIO%SOLAI(:,:,:)   = huge(1.0)

  end subroutine ForcingTypeDefault

  subroutine EnergyTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%ALB)) allocate(NoahowpmpIO%ALB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ALBD)) allocate(NoahowpmpIO%ALBD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBGRD)) allocate(NoahowpmpIO%ALBGRD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBGRI)) allocate(NoahowpmpIO%ALBGRI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBI)) allocate(NoahowpmpIO%ALBI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBOLD)) allocate(NoahowpmpIO%ALBOLD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBSND)) allocate(NoahowpmpIO%ALBSND(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBSNI)) allocate(NoahowpmpIO%ALBSNI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%APAR)) allocate(NoahowpmpIO%APAR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BGAP)) allocate(NoahowpmpIO%BGAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CAH2)) allocate(NoahowpmpIO%CAH2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CH)) allocate(NoahowpmpIO%CH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHB)) allocate(NoahowpmpIO%CHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHB2)) allocate(NoahowpmpIO%CHB2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHLEAF)) allocate(NoahowpmpIO%CHLEAF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHUC)) allocate(NoahowpmpIO%CHUC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHV)) allocate(NoahowpmpIO%CHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHV2)) allocate(NoahowpmpIO%CHV2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CM)) allocate(NoahowpmpIO%CM(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMB)) allocate(NoahowpmpIO%CMB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMV)) allocate(NoahowpmpIO%CMV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%COSZ)) allocate(NoahowpmpIO%COSZ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%COSZ_HORIZ)) allocate(NoahowpmpIO%COSZ_HORIZ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%DF)) allocate(NoahowpmpIO%DF(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%EAH)) allocate(NoahowpmpIO%EAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EHB2)) allocate(NoahowpmpIO%EHB2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMG)) allocate(NoahowpmpIO%EMG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMISSI)) allocate(NoahowpmpIO%EMISSI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMV)) allocate(NoahowpmpIO%EMV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVB)) allocate(NoahowpmpIO%EVB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVC)) allocate(NoahowpmpIO%EVC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVG)) allocate(NoahowpmpIO%EVG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FABD)) allocate(NoahowpmpIO%FABD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FABI)) allocate(NoahowpmpIO%FABI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FACT)) allocate(NoahowpmpIO%FACT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%FAGE)) allocate(NoahowpmpIO%FAGE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FCEV)) allocate(NoahowpmpIO%FCEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FCTR)) allocate(NoahowpmpIO%FCTR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FGEV)) allocate(NoahowpmpIO%FGEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FIRA)) allocate(NoahowpmpIO%FIRA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FREGD)) allocate(NoahowpmpIO%FREGD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREGI)) allocate(NoahowpmpIO%FREGI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREVD)) allocate(NoahowpmpIO%FREVD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREVI)) allocate(NoahowpmpIO%FREVI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FROZEN_CANOPY)) allocate(NoahowpmpIO%FROZEN_CANOPY(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FROZEN_GROUND)) allocate(NoahowpmpIO%FROZEN_GROUND(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSA)) allocate(NoahowpmpIO%FSA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSH)) allocate(NoahowpmpIO%FSH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSHA)) allocate(NoahowpmpIO%FSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSR)) allocate(NoahowpmpIO%FSR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSRG)) allocate(NoahowpmpIO%FSRG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSRV)) allocate(NoahowpmpIO%FSRV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSUN)) allocate(NoahowpmpIO%FSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FTDD)) allocate(NoahowpmpIO%FTDD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTDI)) allocate(NoahowpmpIO%FTDI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTID)) allocate(NoahowpmpIO%FTID(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTII)) allocate(NoahowpmpIO%FTII(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%GAMMAG)) allocate(NoahowpmpIO%GAMMAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GAMMAV)) allocate(NoahowpmpIO%GAMMAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GH)) allocate(NoahowpmpIO%GH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GHB)) allocate(NoahowpmpIO%GHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GHV)) allocate(NoahowpmpIO%GHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%HCPCT)) allocate(NoahowpmpIO%HCPCT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%ICE)) allocate(NoahowpmpIO%ICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IGS)) allocate(NoahowpmpIO%IGS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IMELT)) allocate(NoahowpmpIO%IMELT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%IRB)) allocate(NoahowpmpIO%IRB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IRC)) allocate(NoahowpmpIO%IRC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IRG)) allocate(NoahowpmpIO%IRG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LAISHA)) allocate(NoahowpmpIO%LAISHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LAISUN)) allocate(NoahowpmpIO%LAISUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEA)) allocate(NoahowpmpIO%LATHEA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEAG)) allocate(NoahowpmpIO%LATHEAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEAV)) allocate(NoahowpmpIO%LATHEAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LH)) allocate(NoahowpmpIO%LH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAH)) allocate(NoahowpmpIO%PAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHB)) allocate(NoahowpmpIO%PAHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHG)) allocate(NoahowpmpIO%PAHG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHV)) allocate(NoahowpmpIO%PAHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PARSHA)) allocate(NoahowpmpIO%PARSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PARSUN)) allocate(NoahowpmpIO%PARSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSN)) allocate(NoahowpmpIO%PSN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSNSHA)) allocate(NoahowpmpIO%PSNSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSNSUN)) allocate(NoahowpmpIO%PSNSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q1)) allocate(NoahowpmpIO%Q1(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2B)) allocate(NoahowpmpIO%Q2B(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2E)) allocate(NoahowpmpIO%Q2E(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2V)) allocate(NoahowpmpIO%Q2V(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QMELT)) allocate(NoahowpmpIO%QMELT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSFC)) allocate(NoahowpmpIO%QSFC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RB)) allocate(NoahowpmpIO%RB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RHO)) allocate(NoahowpmpIO%RHO(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%RHSUR)) allocate(NoahowpmpIO%RHSUR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSSHA)) allocate(NoahowpmpIO%RSSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSSUN)) allocate(NoahowpmpIO%RSSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSURF)) allocate(NoahowpmpIO%RSURF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SAG)) allocate(NoahowpmpIO%SAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SAV)) allocate(NoahowpmpIO%SAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHB)) allocate(NoahowpmpIO%SHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHC)) allocate(NoahowpmpIO%SHC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHG)) allocate(NoahowpmpIO%SHG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SSOIL)) allocate(NoahowpmpIO%SSOIL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%STC)) allocate(NoahowpmpIO%STC(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%T2M)) allocate(NoahowpmpIO%T2M(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%T2MB)) allocate(NoahowpmpIO%T2MB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%T2MV)) allocate(NoahowpmpIO%T2MV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAH)) allocate(NoahowpmpIO%TAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAU)) allocate(NoahowpmpIO%TAU(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUSS)) allocate(NoahowpmpIO%TAUSS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUX)) allocate(NoahowpmpIO%TAUX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUXB)) allocate(NoahowpmpIO%TAUXB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUXV)) allocate(NoahowpmpIO%TAUXV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUY)) allocate(NoahowpmpIO%TAUY(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUYB)) allocate(NoahowpmpIO%TAUYB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUYV)) allocate(NoahowpmpIO%TAUYV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TG)) allocate(NoahowpmpIO%TG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGB)) allocate(NoahowpmpIO%TGB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGS)) allocate(NoahowpmpIO%TGS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGV)) allocate(NoahowpmpIO%TGV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TR)) allocate(NoahowpmpIO%TR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TRAD)) allocate(NoahowpmpIO%TRAD(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TS)) allocate(NoahowpmpIO%TS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TV)) allocate(NoahowpmpIO%TV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%WGAP)) allocate(NoahowpmpIO%WGAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0M)) allocate(NoahowpmpIO%Z0M(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0MG)) allocate(NoahowpmpIO%Z0MG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0WRF)) allocate(NoahowpmpIO%Z0WRF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ZLVL)) allocate(NoahowpmpIO%ZLVL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ZPD)) allocate(NoahowpmpIO%ZPD(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine EnergyTypeAllocate

  subroutine EnergyTypeDefault

    NoahowpmpIO%ALB(:,:) = huge(1.0)
    NoahowpmpIO%ALBD(:,:) = huge(1.0)
    NoahowpmpIO%ALBGRD(:,:) = huge(1.0)
    NoahowpmpIO%ALBGRI(:,:) = huge(1.0)
    NoahowpmpIO%ALBI(:,:) = huge(1.0)
    NoahowpmpIO%ALBOLD(:,:) = huge(1.0)
    NoahowpmpIO%ALBSND(:,:) = huge(1.0)
    NoahowpmpIO%ALBSNI(:,:) = huge(1.0)
    NoahowpmpIO%APAR(:,:) = huge(1.0)
    NoahowpmpIO%BGAP(:,:) = huge(1.0)
    NoahowpmpIO%CAH2(:,:) = huge(1.0)
    NoahowpmpIO%CH(:,:) = huge(1.0)
    NoahowpmpIO%CHB(:,:) = huge(1.0)
    NoahowpmpIO%CHB2(:,:) = huge(1.0)
    NoahowpmpIO%CHLEAF(:,:) = huge(1.0)
    NoahowpmpIO%CHUC(:,:) = huge(1.0)
    NoahowpmpIO%CHV(:,:) = huge(1.0)
    NoahowpmpIO%CHV2(:,:) = huge(1.0)
    NoahowpmpIO%CM(:,:) = huge(1.0)
    NoahowpmpIO%CMB(:,:) = huge(1.0)
    NoahowpmpIO%CMV(:,:) = huge(1.0)
    NoahowpmpIO%COSZ(:,:) = huge(1.0)
    NoahowpmpIO%COSZ_HORIZ(:,:) = huge(1.0)
    NoahowpmpIO%DF(:,:,:) = huge(1.0)
    NoahowpmpIO%EAH(:,:) = huge(1.0)
    NoahowpmpIO%EHB2(:,:) = huge(1.0)
    NoahowpmpIO%EMG(:,:) = huge(1.0)
    NoahowpmpIO%EMISSI(:,:) = huge(1.0)
    NoahowpmpIO%EMV(:,:) = huge(1.0)
    NoahowpmpIO%EVB(:,:) = huge(1.0)
    NoahowpmpIO%EVC(:,:) = huge(1.0)
    NoahowpmpIO%EVG(:,:) = huge(1.0)
    NoahowpmpIO%FABD(:,:) = huge(1.0)
    NoahowpmpIO%FABI(:,:) = huge(1.0)
    NoahowpmpIO%FACT(:,:,:) = huge(1.0)
    NoahowpmpIO%FAGE(:,:) = huge(1.0)
    NoahowpmpIO%FCEV(:,:) = huge(1.0)
    NoahowpmpIO%FCTR(:,:) = huge(1.0)
    NoahowpmpIO%FGEV(:,:) = huge(1.0)
    NoahowpmpIO%FIRA(:,:) = huge(1.0)
    NoahowpmpIO%FREGD(:,:) = huge(1.0)
    NoahowpmpIO%FREGI(:,:) = huge(1.0)
    NoahowpmpIO%FREVD(:,:) = huge(1.0)
    NoahowpmpIO%FREVI(:,:) = huge(1.0)
    NoahowpmpIO%FROZEN_CANOPY(:,:) = .FALSE.
    NoahowpmpIO%FROZEN_GROUND(:,:) = .FALSE.
    NoahowpmpIO%FSA(:,:) = huge(1.0)
    NoahowpmpIO%FSH(:,:) = huge(1.0)
    NoahowpmpIO%FSHA(:,:) = huge(1.0)
    NoahowpmpIO%FSR(:,:) = huge(1.0)
    NoahowpmpIO%FSRG(:,:) = huge(1.0)
    NoahowpmpIO%FSRV(:,:) = huge(1.0)
    NoahowpmpIO%FSUN(:,:) = huge(1.0)
    NoahowpmpIO%FTDD(:,:) = huge(1.0)
    NoahowpmpIO%FTDI(:,:) = huge(1.0)
    NoahowpmpIO%FTID(:,:) = huge(1.0)
    NoahowpmpIO%FTII(:,:) = huge(1.0)
    NoahowpmpIO%GAMMAG(:,:) = huge(1.0)
    NoahowpmpIO%GAMMAV(:,:) = huge(1.0)
    NoahowpmpIO%GH(:,:) = huge(1.0)
    NoahowpmpIO%GHB(:,:) = huge(1.0)
    NoahowpmpIO%GHV(:,:) = huge(1.0)
    NoahowpmpIO%HCPCT(:,:,:) = huge(1.0)
    NoahowpmpIO%ICE(:,:) = huge(1)
    NoahowpmpIO%IGS(:,:) = huge(1.0)
    NoahowpmpIO%IMELT(:,:,:) = huge(1)
    NoahowpmpIO%IRB(:,:) = huge(1.0)
    NoahowpmpIO%IRC(:,:) = huge(1.0)
    NoahowpmpIO%IRG(:,:) = huge(1.0)
    NoahowpmpIO%LAISHA(:,:) = huge(1.0)
    NoahowpmpIO%LAISUN(:,:) = huge(1.0)
    NoahowpmpIO%LATHEA(:,:) = huge(1.0)
    NoahowpmpIO%LATHEAG(:,:) = huge(1.0)
    NoahowpmpIO%LATHEAV(:,:) = huge(1.0)
    NoahowpmpIO%LH(:,:) = huge(1.0)
    NoahowpmpIO%PAH(:,:) = huge(1.0)
    NoahowpmpIO%PAHB(:,:) = huge(1.0)
    NoahowpmpIO%PAHG(:,:) = huge(1.0)
    NoahowpmpIO%PAHV(:,:) = huge(1.0)
    NoahowpmpIO%PARSHA(:,:) = huge(1.0)
    NoahowpmpIO%PARSUN(:,:) = huge(1.0)
    NoahowpmpIO%PSN(:,:) = huge(1.0)
    NoahowpmpIO%PSNSHA(:,:) = huge(1.0)
    NoahowpmpIO%PSNSUN(:,:) = huge(1.0)
    NoahowpmpIO%Q1(:,:) = huge(1.0)
    NoahowpmpIO%Q2B(:,:) = huge(1.0)
    NoahowpmpIO%Q2E(:,:) = huge(1.0)
    NoahowpmpIO%Q2V(:,:) = huge(1.0)
    NoahowpmpIO%QMELT(:,:) = huge(1.0)
    NoahowpmpIO%QSFC(:,:) = huge(1.0)
    NoahowpmpIO%RB(:,:) = huge(1.0)
    NoahowpmpIO%RHO(:,:) = huge(1.0)
    NoahowpmpIO%RHSUR(:,:) = huge(1.0)
    NoahowpmpIO%RSSHA(:,:) = huge(1.0)
    NoahowpmpIO%RSSUN(:,:) = huge(1.0)
    NoahowpmpIO%RSURF(:,:) = huge(1.0)
    NoahowpmpIO%SAG(:,:) = huge(1.0)
    NoahowpmpIO%SAV(:,:) = huge(1.0)
    NoahowpmpIO%SHB(:,:) = huge(1.0)
    NoahowpmpIO%SHC(:,:) = huge(1.0)
    NoahowpmpIO%SHG(:,:) = huge(1.0)
    NoahowpmpIO%SSOIL(:,:) = huge(1.0)
    NoahowpmpIO%STC(:,:,:) = huge(1.0)
    NoahowpmpIO%T2M(:,:) = huge(1.0)
    NoahowpmpIO%T2MB(:,:) = huge(1.0)
    NoahowpmpIO%T2MV(:,:) = huge(1.0)
    NoahowpmpIO%TAH(:,:) = huge(1.0)
    NoahowpmpIO%TAU(:,:) = huge(1.0)
    NoahowpmpIO%TAUSS(:,:) = huge(1.0)
    NoahowpmpIO%TAUX(:,:) = huge(1.0)
    NoahowpmpIO%TAUXB(:,:) = huge(1.0)
    NoahowpmpIO%TAUXV(:,:) = huge(1.0)
    NoahowpmpIO%TAUY(:,:) = huge(1.0)
    NoahowpmpIO%TAUYB(:,:) = huge(1.0)
    NoahowpmpIO%TAUYV(:,:) = huge(1.0)
    NoahowpmpIO%TG(:,:) = huge(1.0)
    NoahowpmpIO%TGB(:,:) = huge(1.0)
    NoahowpmpIO%TGS(:,:) = huge(1.0)
    NoahowpmpIO%TGV(:,:) = huge(1.0)
    NoahowpmpIO%TR(:,:) = huge(1.0)
    NoahowpmpIO%TRAD(:,:) = huge(1.0)
    NoahowpmpIO%TS(:,:) = huge(1.0)
    NoahowpmpIO%TV(:,:) = huge(1.0)
    NoahowpmpIO%WGAP(:,:) = huge(1.0)
    NoahowpmpIO%Z0M(:,:) = huge(1.0)
    NoahowpmpIO%Z0MG(:,:) = huge(1.0)
    NoahowpmpIO%Z0WRF(:,:) = huge(1.0)
    NoahowpmpIO%ZLVL(:,:) = huge(1.0)
    NoahowpmpIO%ZPD(:,:) = huge(1.0)

  end subroutine EnergyTypeDefault

  subroutine DomainTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%lat))             allocate(NoahowpmpIO%lat(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%lon))             allocate(NoahowpmpIO%lon(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%terrain_slope))   allocate(NoahowpmpIO%terrain_slope(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%azimuth))         allocate(NoahowpmpIO%azimuth(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%vegtyp))          allocate(NoahowpmpIO%vegtyp(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%isltyp))          allocate(NoahowpmpIO%isltyp(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IST))             allocate(NoahowpmpIO%IST(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%croptype))        allocate(NoahowpmpIO%croptype(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%zsoil))           allocate(NoahowpmpIO%zsoil (NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%dzsnso))          allocate(NoahowpmpIO%dzsnso(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%zsnso))           allocate(NoahowpmpIO%zsnso(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))

  end subroutine DomainTypeAllocate

  subroutine DomainTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%dt                    = huge(1.0)
    NoahowpmpIO%startdate             = 'EMPTYDATE999'
    NoahowpmpIO%enddate               = 'EMPTYDATE999'
    NoahowpmpIO%nowdate               = 'EMPTYDATE999'
    NoahowpmpIO%start_datetime        = huge(1)
    NoahowpmpIO%end_datetime          = huge(1)
    NoahowpmpIO%curr_datetime         = huge(1)
    NoahowpmpIO%itime                 = huge(1) 
    NoahowpmpIO%ntime                 = huge(1) 
    NoahowpmpIO%time_dbl              = huge(1.d0)
    NoahowpmpIO%ix                    = huge(1)
    NoahowpmpIO%iy                    = huge(1)
    NoahowpmpIO%nx                    = huge(1)
    NoahowpmpIO%ny                    = huge(1)
    NoahowpmpIO%lat(:,:)              = huge(1.0)             
    NoahowpmpIO%lon(:,:)              = huge(1.0)           
    NoahowpmpIO%ZREF(:,:)             = huge(1.0)       
    NoahowpmpIO%terrain_slope(:,:)    = huge(1.0)   
    NoahowpmpIO%azimuth(:,:)          = huge(1.0)        
    NoahowpmpIO%vegtyp(:,:)           = huge(1)          
    NoahowpmpIO%croptype(:,:)         = huge(1)   
    NoahowpmpIO%isltyp(:,:)           = huge(1)  
    NoahowpmpIO%IST(:,:)              = huge(1)          
    NoahowpmpIO%zsoil(:,:,:)          = huge(1.0)           
    NoahowpmpIO%dzsnso(:,:,:)         = huge(1.0)             
    NoahowpmpIO%zsnso(:,:,:)          = huge(1.0)          

  end subroutine DomainTypeDefault

end module NoahmpIOVarInitModule