module NoahowpGridTypeInitModule

  use NoahowpGridTypeModule
  
  implicit none
  
  contains

  subroutine NoahowpGridTypeInit(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    call DomainTypeAllocate(noahowpgrid)
    call DomainTypeDefault(noahowpgrid)
    call EnergyTypeAllocate(noahowpgrid)
    call EnergyTypeDefault(noahowpgrid)
    call ForcingTypeAllocate(noahowpgrid)
    call ForcingTypeDefault(noahowpgrid)
    call LevelsTypeAllocate(noahowpgrid)
    call LevelsTypeDefault(noahowpgrid)
    call OptionsTypeAllocate(noahowpgrid)
    call OptionsTypeDefault(noahowpgrid)
    call ParametersTypeAllocate(noahowpgrid)
    call ParametersTypeDefault(noahowpgrid)
    call WaterTypeAllocate(noahowpgrid)
    call WaterTypeDefault(noahowpgrid)
    call TableVarsAllocate(noahowpgrid)
    call TableVarsDefault(noahowpgrid)

  end subroutine NoahowpGridTypeInit

  subroutine WaterTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x   => noahowpgrid%n_x,   &
              n_y   => noahowpgrid%n_y,   &
              nsoil => noahowpgrid%nsoil, &
              nsnow => noahowpgrid%nsnow  &
              )

    if(.NOT.allocated(noahowpgrid%qinsur)) allocate(noahowpgrid%qinsur(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%qseva)) allocate(noahowpgrid%qseva(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EVAPOTRANS)) allocate(noahowpgrid%EVAPOTRANS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%runsrf)) allocate(noahowpgrid%runsrf(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%runsub)) allocate(noahowpgrid%runsub(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%qdrain)) allocate(noahowpgrid%qdrain(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%zwt)) allocate(noahowpgrid%zwt(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%smcwtd)) allocate(noahowpgrid%smcwtd(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%deeprech)) allocate(noahowpgrid%deeprech(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%fcrmax)) allocate(noahowpgrid%fcrmax(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%snoflow)) allocate(noahowpgrid%snoflow(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%pddum)) allocate(noahowpgrid%pddum(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FACC)) allocate(noahowpgrid%FACC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%sicemax)) allocate(noahowpgrid%sicemax(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FB_snow)) allocate(noahowpgrid%FB_snow(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%rain)) allocate(noahowpgrid%rain(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%snow)) allocate(noahowpgrid%snow(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%bdfall)) allocate(noahowpgrid%bdfall(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FP)) allocate(noahowpgrid%FP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%canliq)) allocate(noahowpgrid%canliq(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%canice)) allocate(noahowpgrid%canice(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FWET)) allocate(noahowpgrid%FWET(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CMC)) allocate(noahowpgrid%CMC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QINTR)) allocate(noahowpgrid%QINTR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QDRIPR)) allocate(noahowpgrid%QDRIPR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QTHROR)) allocate(noahowpgrid%QTHROR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QINTS)) allocate(noahowpgrid%QINTS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QDRIPS)) allocate(noahowpgrid%QDRIPS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QTHROS)) allocate(noahowpgrid%QTHROS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QRAIN)) allocate(noahowpgrid%QRAIN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSNOW)) allocate(noahowpgrid%QSNOW(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SNOWHIN)) allocate(noahowpgrid%SNOWHIN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ECAN)) allocate(noahowpgrid%ECAN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ETRAN)) allocate(noahowpgrid%ETRAN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSNFRO)) allocate(noahowpgrid%QSNFRO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSNSUB)) allocate(noahowpgrid%QSNSUB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SNOWH)) allocate(noahowpgrid%SNOWH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SNEQV)) allocate(noahowpgrid%SNEQV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SNEQVO)) allocate(noahowpgrid%SNEQVO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BDSNO)) allocate(noahowpgrid%BDSNO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSNBOT)) allocate(noahowpgrid%QSNBOT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PONDING)) allocate(noahowpgrid%PONDING(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PONDING1)) allocate(noahowpgrid%PONDING1(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PONDING2)) allocate(noahowpgrid%PONDING2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QVAP)) allocate(noahowpgrid%QVAP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QDEW)) allocate(noahowpgrid%QDEW(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSDEW)) allocate(noahowpgrid%QSDEW(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%WSLAKE)) allocate(noahowpgrid%WSLAKE(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%runsrf_dt)) allocate(noahowpgrid%runsrf_dt(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ASAT)) allocate(noahowpgrid%ASAT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ISNOW)) allocate(noahowpgrid%ISNOW(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%smc)) allocate(noahowpgrid%smc(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%smc_init)) allocate(noahowpgrid%smc_init(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%sice)) allocate(noahowpgrid%sice(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%sh2o)) allocate(noahowpgrid%sh2o(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%etrani)) allocate(noahowpgrid%etrani(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%BTRANI)) allocate(noahowpgrid%BTRANI(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%wcnd)) allocate(noahowpgrid%wcnd(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%fcr)) allocate(noahowpgrid%fcr(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%FICEOLD)) allocate(noahowpgrid%FICEOLD(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%SNICE)) allocate(noahowpgrid%SNICE(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%SNLIQ)) allocate(noahowpgrid%SNLIQ(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%SNICEV)) allocate(noahowpgrid%SNICEV(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%SNLIQV)) allocate(noahowpgrid%SNLIQV(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%FICE)) allocate(noahowpgrid%FICE(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%EPORE)) allocate(noahowpgrid%EPORE(n_x,n_y,-nsnow+1:0))
    if(.NOT.allocated(noahowpgrid%FSNO)) allocate(noahowpgrid%FSNO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BTRAN)) allocate(noahowpgrid%BTRAN(n_x,n_y))

    end associate
    
  end subroutine

  subroutine WaterTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%qinsur(:,:) = huge(1.0)
    noahowpgrid%qseva(:,:) = huge(1.0)
    noahowpgrid%EVAPOTRANS(:,:) = huge(1.0)
    noahowpgrid%runsrf(:,:) = huge(1.0)
    noahowpgrid%runsub(:,:) = huge(1.0)
    noahowpgrid%qdrain(:,:) = huge(1.0)
    noahowpgrid%zwt(:,:) = huge(1.0)
    noahowpgrid%smcwtd(:,:) = huge(1.0)
    noahowpgrid%deeprech(:,:) = huge(1.0)
    noahowpgrid%fcrmax(:,:) = huge(1.0)
    noahowpgrid%snoflow(:,:) = huge(1.0)
    noahowpgrid%pddum(:,:) = huge(1.0)
    noahowpgrid%FACC(:,:) = huge(1.0)
    noahowpgrid%sicemax(:,:) = huge(1.0)
    noahowpgrid%FB_snow(:,:) = huge(1.0)
    noahowpgrid%rain(:,:) = huge(1.0)
    noahowpgrid%snow(:,:) = huge(1.0)
    noahowpgrid%bdfall(:,:) = huge(1.0)
    noahowpgrid%FP(:,:) = huge(1.0)
    noahowpgrid%canliq(:,:) = huge(1.0)
    noahowpgrid%canice(:,:) = huge(1.0)
    noahowpgrid%FWET(:,:) = huge(1.0)
    noahowpgrid%CMC(:,:) = huge(1.0)
    noahowpgrid%QINTR(:,:) = huge(1.0)
    noahowpgrid%QDRIPR(:,:) = huge(1.0)
    noahowpgrid%QTHROR(:,:) = huge(1.0)
    noahowpgrid%QINTS(:,:) = huge(1.0)
    noahowpgrid%QDRIPS(:,:) = huge(1.0)
    noahowpgrid%QTHROS(:,:) = huge(1.0)
    noahowpgrid%QRAIN(:,:) = huge(1.0)
    noahowpgrid%QSNOW(:,:) = huge(1.0)
    noahowpgrid%SNOWHIN(:,:) = huge(1.0)
    noahowpgrid%ECAN(:,:) = huge(1.0)
    noahowpgrid%ETRAN(:,:) = huge(1.0)
    noahowpgrid%QSNFRO(:,:) = huge(1.0)
    noahowpgrid%QSNSUB(:,:) = huge(1.0)
    noahowpgrid%SNOWH(:,:) = huge(1.0)
    noahowpgrid%SNEQV(:,:) = huge(1.0)
    noahowpgrid%SNEQVO(:,:) = huge(1.0)
    noahowpgrid%BDSNO(:,:) = huge(1.0)
    noahowpgrid%QSNBOT(:,:) = huge(1.0)
    noahowpgrid%PONDING(:,:) = huge(1.0)
    noahowpgrid%PONDING1(:,:) = huge(1.0)
    noahowpgrid%PONDING2(:,:) = huge(1.0)
    noahowpgrid%QVAP(:,:) = huge(1.0)
    noahowpgrid%QDEW(:,:) = huge(1.0)
    noahowpgrid%QSDEW(:,:) = huge(1.0)
    noahowpgrid%WSLAKE(:,:) = huge(1.0)
    noahowpgrid%runsrf_dt(:,:) = huge(1.0)
    noahowpgrid%ASAT(:,:) = huge(1.0)
    noahowpgrid%ISNOW(:,:) = huge(1)
    noahowpgrid%smc(:,:,:) = huge(1.0)
    noahowpgrid%smc_init(:,:,:) = huge(1.0)
    noahowpgrid%sice(:,:,:) = huge(1.0)
    noahowpgrid%sh2o(:,:,:) = huge(1.0)
    noahowpgrid%etrani(:,:,:) = huge(1.0)
    noahowpgrid%BTRANI(:,:,:) = huge(1.0)
    noahowpgrid%wcnd(:,:,:) = huge(1.0)
    noahowpgrid%fcr(:,:,:) = huge(1.0)
    noahowpgrid%FICEOLD(:,:,:) = huge(1.0)
    noahowpgrid%SNICE(:,:,:) = huge(1.0)
    noahowpgrid%SNLIQ(:,:,:) = huge(1.0)
    noahowpgrid%SNICEV(:,:,:) = huge(1.0)
    noahowpgrid%SNLIQV(:,:,:) = huge(1.0)
    noahowpgrid%FICE(:,:,:) = huge(1.0)
    noahowpgrid%EPORE(:,:,:) = huge(1.0)
    noahowpgrid%FSNO(:,:) = huge(1.0)
    noahowpgrid%BTRAN(:,:) = huge(1.0)

  end subroutine

  subroutine ParametersTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x => noahowpgrid%n_x, &
              n_y => noahowpgrid%n_y, &
              nsoil => noahowpgrid%nsoil &
              )

    if(.NOT.allocated(noahowpgrid%bexp)) allocate(noahowpgrid%bexp(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%smcmax)) allocate(noahowpgrid%smcmax(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%smcwlt)) allocate(noahowpgrid%smcwlt(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%smcref)) allocate(noahowpgrid%smcref(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%dksat)) allocate(noahowpgrid%dksat(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%dwsat)) allocate(noahowpgrid%dwsat(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%psisat)) allocate(noahowpgrid%psisat(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%bvic)) allocate(noahowpgrid%bvic(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%AXAJ)) allocate(noahowpgrid%AXAJ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BXAJ)) allocate(noahowpgrid%BXAJ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%XXAJ)) allocate(noahowpgrid%XXAJ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BBVIC)) allocate(noahowpgrid%BBVIC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%G)) allocate(noahowpgrid%G(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QUARTZ)) allocate(noahowpgrid%QUARTZ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%kdt)) allocate(noahowpgrid%kdt(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%frzx)) allocate(noahowpgrid%frzx(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ZWT_INIT)) allocate(noahowpgrid%ZWT_INIT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%urban_flag)) allocate(noahowpgrid%urban_flag(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LAIM)) allocate(noahowpgrid%LAIM(n_x,n_y,12))
    if(.NOT.allocated(noahowpgrid%SAIM)) allocate(noahowpgrid%SAIM(n_x,n_y,12))
    if(.NOT.allocated(noahowpgrid%LAI)) allocate(noahowpgrid%LAI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SAI)) allocate(noahowpgrid%SAI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CH2OP)) allocate(noahowpgrid%CH2OP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%NROOT)) allocate(noahowpgrid%NROOT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%HVT)) allocate(noahowpgrid%HVT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%HVB)) allocate(noahowpgrid%HVB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TMIN)) allocate(noahowpgrid%TMIN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SHDFAC)) allocate(noahowpgrid%SHDFAC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SHDMAX)) allocate(noahowpgrid%SHDMAX(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Z0MVT)) allocate(noahowpgrid%Z0MVT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RC)) allocate(noahowpgrid%RC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%XL)) allocate(noahowpgrid%XL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BP)) allocate(noahowpgrid%BP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FOLNMX)) allocate(noahowpgrid%FOLNMX(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QE25)) allocate(noahowpgrid%QE25(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%VCMX25)) allocate(noahowpgrid%VCMX25(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%MP)) allocate(noahowpgrid%MP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RGL)) allocate(noahowpgrid%RGL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RSMIN)) allocate(noahowpgrid%RSMIN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%HS)) allocate(noahowpgrid%HS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%AKC)) allocate(noahowpgrid%AKC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%AKO)) allocate(noahowpgrid%AKO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%AVCMX)) allocate(noahowpgrid%AVCMX(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RSMAX)) allocate(noahowpgrid%RSMAX(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CWP)) allocate(noahowpgrid%CWP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%C3PSN)) allocate(noahowpgrid%C3PSN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%DLEAF)) allocate(noahowpgrid%DLEAF(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%KC25)) allocate(noahowpgrid%KC25(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%KO25)) allocate(noahowpgrid%KO25(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ELAI)) allocate(noahowpgrid%ELAI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ESAI)) allocate(noahowpgrid%ESAI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%VAI)) allocate(noahowpgrid%VAI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%VEG)) allocate(noahowpgrid%VEG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FVEG)) allocate(noahowpgrid%FVEG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RHOL)) allocate(noahowpgrid%RHOL(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%RHOS)) allocate(noahowpgrid%RHOS(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%TAUL)) allocate(noahowpgrid%TAUL(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%TAUS)) allocate(noahowpgrid%TAUS(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%MFSNO)) allocate(noahowpgrid%MFSNO(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ALBSAT)) allocate(noahowpgrid%ALBSAT(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBDRY)) allocate(noahowpgrid%ALBDRY(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBICE)) allocate(noahowpgrid%ALBICE(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBLAK)) allocate(noahowpgrid%ALBLAK(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%OMEGAS)) allocate(noahowpgrid%OMEGAS(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%EG)) allocate(noahowpgrid%EG(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%TOPT)) allocate(noahowpgrid%TOPT(n_x,n_y))

    end associate

  end subroutine

  subroutine ParametersTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%bexp(:,:,:) = huge(1.0)
    noahowpgrid%smcmax(:,:,:) = huge(1.0)
    noahowpgrid%smcwlt(:,:,:) = huge(1.0)
    noahowpgrid%smcref(:,:,:) = huge(1.0)
    noahowpgrid%dksat(:,:,:) = huge(1.0)
    noahowpgrid%dwsat(:,:,:) = huge(1.0)
    noahowpgrid%psisat(:,:,:) = huge(1.0)
    noahowpgrid%bvic(:,:) = huge(1.0)
    noahowpgrid%AXAJ(:,:) = huge(1.0)
    noahowpgrid%BXAJ(:,:) = huge(1.0)
    noahowpgrid%XXAJ(:,:) = huge(1.0)
    noahowpgrid%BBVIC(:,:) = huge(1.0)
    noahowpgrid%G(:,:) = huge(1.0)
    noahowpgrid%QUARTZ(:,:) = huge(1.0)
    noahowpgrid%kdt(:,:) = huge(1.0)
    noahowpgrid%refkdt = huge(1.0)
    noahowpgrid%refdk = huge(1.0)
    noahowpgrid%csoil = huge(1.0)
    noahowpgrid%Z0 = huge(1.0)
    noahowpgrid%CZIL = huge(1.0)
    noahowpgrid%ZBOT = huge(1.0)
    noahowpgrid%frzx(:,:) = huge(1.0)
    noahowpgrid%slope = huge(1.0)
    noahowpgrid%timean = huge(1.0)
    noahowpgrid%fsatmx = huge(1.0)
    noahowpgrid%ZWT_INIT(:,:) = huge(1.0)
    noahowpgrid%urban_flag(:,:) = .FALSE.
    noahowpgrid%LAIM(:,:,:) = huge(1.0)
    noahowpgrid%SAIM(:,:,:) = huge(1.0)
    noahowpgrid%LAI(:,:) = huge(1.0)
    noahowpgrid%SAI(:,:) = huge(1.0)
    noahowpgrid%CH2OP(:,:) = huge(1.0)
    noahowpgrid%NROOT(:,:) = huge(1)
    noahowpgrid%HVT(:,:) = huge(1.0)
    noahowpgrid%HVB(:,:) = huge(1.0)
    noahowpgrid%TMIN(:,:) = huge(1.0)
    noahowpgrid%SHDFAC(:,:) = huge(1.0)
    noahowpgrid%SHDMAX(:,:) = huge(1.0)
    noahowpgrid%Z0MVT(:,:) = huge(1.0)
    noahowpgrid%RC(:,:) = huge(1.0)
    noahowpgrid%XL(:,:) = huge(1.0)
    noahowpgrid%BP(:,:) = huge(1.0)
    noahowpgrid%FOLNMX(:,:) = huge(1.0)
    noahowpgrid%QE25(:,:) = huge(1.0)
    noahowpgrid%VCMX25(:,:) = huge(1.0)
    noahowpgrid%MP(:,:) = huge(1.0)
    noahowpgrid%RGL(:,:) = huge(1.0)
    noahowpgrid%RSMIN(:,:) = huge(1.0)
    noahowpgrid%HS(:,:) = huge(1.0)
    noahowpgrid%AKC(:,:) = huge(1.0)
    noahowpgrid%AKO(:,:) = huge(1.0)
    noahowpgrid%AVCMX(:,:) = huge(1.0)
    noahowpgrid%RSMAX(:,:) = huge(1.0)
    noahowpgrid%CWP(:,:) = huge(1.0)
    noahowpgrid%C3PSN(:,:) = huge(1.0)
    noahowpgrid%DLEAF(:,:) = huge(1.0)
    noahowpgrid%KC25(:,:) = huge(1.0)
    noahowpgrid%KO25(:,:) = huge(1.0)
    noahowpgrid%ELAI(:,:) = huge(1.0)
    noahowpgrid%ESAI(:,:) = huge(1.0)
    noahowpgrid%VAI(:,:) = huge(1.0)
    noahowpgrid%VEG(:,:) = .FALSE.
    noahowpgrid%FVEG(:,:) = huge(1.0)
    noahowpgrid%RHOL(:,:,:) = huge(1.0)
    noahowpgrid%RHOS(:,:,:) = huge(1.0)
    noahowpgrid%TAUL(:,:,:) = huge(1.0)
    noahowpgrid%TAUS(:,:,:) = huge(1.0)
    noahowpgrid%ISURBAN = huge(1)
    noahowpgrid%ISWATER = huge(1)
    noahowpgrid%ISBARREN = huge(1)
    noahowpgrid%ISICE = huge(1)
    noahowpgrid%ISCROP = huge(1)
    noahowpgrid%EBLFOREST = huge(1)
    noahowpgrid%NATURAL = huge(1)
    noahowpgrid%LOW_DENSITY_RESIDENTIAL = huge(1)
    noahowpgrid%HIGH_DENSITY_RESIDENTIAL = huge(1)
    noahowpgrid%HIGH_INTENSITY_INDUSTRIAL = huge(1)
    noahowpgrid%SB = huge(1.0)
    noahowpgrid%VKC = huge(1.0)
    noahowpgrid%TFRZ = huge(1.0)
    noahowpgrid%HSUB = huge(1.0)
    noahowpgrid%HVAP = huge(1.0)
    noahowpgrid%HFUS = huge(1.0)
    noahowpgrid%CWAT = huge(1.0)
    noahowpgrid%CICE = huge(1.0)
    noahowpgrid%CPAIR = huge(1.0)
    noahowpgrid%TKWAT = huge(1.0)
    noahowpgrid%TKICE = huge(1.0)
    noahowpgrid%TKAIR = huge(1.0)
    noahowpgrid%RAIR = huge(1.0)
    noahowpgrid%RW = huge(1.0)
    noahowpgrid%DENH2O = huge(1.0)
    noahowpgrid%DENICE = huge(1.0)
    noahowpgrid%THKW = huge(1.0)
    noahowpgrid%THKO = huge(1.0)
    noahowpgrid%THKQTZ = huge(1.0)
    noahowpgrid%SSI = huge(1.0)
    noahowpgrid%MFSNO(:,:) = huge(1.0)
    noahowpgrid%Z0SNO = huge(1.0)
    noahowpgrid%SWEMX = huge(1.0)
    noahowpgrid%TAU0 = huge(1.0)
    noahowpgrid%GRAIN_GROWTH = huge(1.0)
    noahowpgrid%EXTRA_GROWTH = huge(1.0)
    noahowpgrid%DIRT_SOOT = huge(1.0)
    noahowpgrid%BATS_COSZ = huge(1.0)
    noahowpgrid%BATS_VIS_NEW = huge(1.0)
    noahowpgrid%BATS_NIR_NEW = huge(1.0)
    noahowpgrid%BATS_VIS_AGE = huge(1.0)
    noahowpgrid%BATS_NIR_AGE = huge(1.0)
    noahowpgrid%BATS_VIS_DIR = huge(1.0)
    noahowpgrid%BATS_NIR_DIR = huge(1.0)
    noahowpgrid%RSURF_SNOW = huge(1.0)
    noahowpgrid%RSURF_EXP = huge(1.0)
    noahowpgrid%ALBSAT(:,:,:) = huge(1.0)
    noahowpgrid%ALBDRY(:,:,:) = huge(1.0)
    noahowpgrid%ALBICE(:,:,:) = huge(1.0)
    noahowpgrid%ALBLAK(:,:,:) = huge(1.0)
    noahowpgrid%OMEGAS(:,:,:) = huge(1.0)
    noahowpgrid%BETADS = huge(1.0)
    noahowpgrid%BETAIS = huge(1.0)
    noahowpgrid%EG(:,:,:) = huge(1.0)
    noahowpgrid%WSLMAX = huge(1.0)
    noahowpgrid%max_liq_mass_fraction = huge(1.0)
    noahowpgrid%SNOW_RET_FAC = huge(1.0)
    noahowpgrid%NBAND = huge(1)
    noahowpgrid%MPE = huge(1.0)
    noahowpgrid%TOPT(:,:) = huge(1.0)
    noahowpgrid%O2 = huge(1.0)
    noahowpgrid%CO2 = huge(1.0)
    noahowpgrid%PSIWLT = huge(1.0)
    noahowpgrid%TBOT = huge(1.0)
    noahowpgrid%GRAV = huge(1.0)
    noahowpgrid%rain_snow_thresh = huge(1.0)

  end subroutine

  subroutine OptionsTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x => noahowpgrid%n_x, &
              n_y => noahowpgrid%n_y)

    if(.NOT.allocated(noahowpgrid%opt_snf)) allocate(noahowpgrid%opt_snf(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_run)) allocate(noahowpgrid%opt_run(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_drn)) allocate(noahowpgrid%opt_drn(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_inf)) allocate(noahowpgrid%opt_inf(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_infdv)) allocate(noahowpgrid%opt_infdv(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%dveg)) allocate(noahowpgrid%dveg(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_alb)) allocate(noahowpgrid%opt_alb(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_rad)) allocate(noahowpgrid%opt_rad(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_sfc)) allocate(noahowpgrid%opt_sfc(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_crs)) allocate(noahowpgrid%opt_crs(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_crop)) allocate(noahowpgrid%opt_crop(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_stc)) allocate(noahowpgrid%opt_stc(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_tbot)) allocate(noahowpgrid%opt_tbot(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_frz)) allocate(noahowpgrid%opt_frz(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_btr)) allocate(noahowpgrid%opt_btr(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_rsf)) allocate(noahowpgrid%opt_rsf(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%opt_sub)) allocate(noahowpgrid%opt_sub(n_x,n_y))

    end associate

  end subroutine

  subroutine OptionsTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%opt_snf(:,:)       = huge(1)
    noahowpgrid%opt_run(:,:)       = huge(1)
    noahowpgrid%opt_drn(:,:)       = huge(1)
    noahowpgrid%opt_inf(:,:)       = huge(1)
    noahowpgrid%opt_infdv(:,:)     = huge(1)
    noahowpgrid%dveg(:,:)          = huge(1)
    noahowpgrid%opt_alb(:,:)       = huge(1)
    noahowpgrid%opt_rad(:,:)       = huge(1)
    noahowpgrid%opt_sfc(:,:)       = huge(1)
    noahowpgrid%opt_crs(:,:)       = huge(1)
    noahowpgrid%opt_crop(:,:)      = huge(1)
    noahowpgrid%opt_stc(:,:)       = huge(1)
    noahowpgrid%opt_tbot(:,:)      = huge(1)
    noahowpgrid%opt_frz(:,:)       = huge(1)
    noahowpgrid%opt_btr(:,:)       = huge(1)
    noahowpgrid%opt_rsf(:,:)       = huge(1)
    noahowpgrid%opt_sub(:,:)       = huge(1)

  end subroutine

  subroutine LevelsTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    !Nothing to do

  end subroutine

  subroutine LevelsTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    !noahowpgrid%nsoil    = huge(1)
    !noahowpgrid%nsnow    = huge(1)
    !noahowpgrid%nveg     = huge(1)

  end subroutine

  subroutine ForcingTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x => noahowpgrid%n_x, &
              n_y => noahowpgrid%n_y)

    if(.NOT.allocated(noahowpgrid%SFCPRS)) allocate(noahowpgrid%SFCPRS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SFCTMP)) allocate(noahowpgrid%SFCTMP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Q2)) allocate(noahowpgrid%Q2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCP)) allocate(noahowpgrid%PRCP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPCONV)) allocate(noahowpgrid%PRCPCONV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPNONC)) allocate(noahowpgrid%PRCPNONC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPSHCV)) allocate(noahowpgrid%PRCPSHCV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPSNOW)) allocate(noahowpgrid%PRCPSNOW(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPGRPL)) allocate(noahowpgrid%PRCPGRPL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PRCPHAIL)) allocate(noahowpgrid%PRCPHAIL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SOLDN)) allocate(noahowpgrid%SOLDN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LWDN)) allocate(noahowpgrid%LWDN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FOLN)) allocate(noahowpgrid%FOLN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%O2PP)) allocate(noahowpgrid%O2PP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CO2PP)) allocate(noahowpgrid%CO2PP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%UU)) allocate(noahowpgrid%UU(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%VV)) allocate(noahowpgrid%VV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TBOT)) allocate(noahowpgrid%TBOT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%UR)) allocate(noahowpgrid%UR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%THAIR)) allocate(noahowpgrid%THAIR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QAIR)) allocate(noahowpgrid%QAIR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EAIR)) allocate(noahowpgrid%EAIR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RHOAIR)) allocate(noahowpgrid%RHOAIR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FPICE)) allocate(noahowpgrid%FPICE(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SWDOWN)) allocate(noahowpgrid%SWDOWN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SOLAD)) allocate(noahowpgrid%SOLAD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%SOLAI)) allocate(noahowpgrid%SOLAI(n_x,n_y,2))

    end associate

  end subroutine ForcingTypeAllocate

  subroutine ForcingTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%SFCPRS(:,:)    = huge(1.0)
    noahowpgrid%SFCTMP(:,:)    = huge(1.0)
    noahowpgrid%Q2(:,:)        = huge(1.0)
    noahowpgrid%PRCP(:,:)      = huge(1.0)
    noahowpgrid%PRCPCONV(:,:)  = huge(1.0)
    noahowpgrid%PRCPNONC(:,:)  = huge(1.0)
    noahowpgrid%PRCPSHCV(:,:)  = huge(1.0)
    noahowpgrid%PRCPSNOW(:,:)  = huge(1.0)
    noahowpgrid%PRCPGRPL(:,:)  = huge(1.0)
    noahowpgrid%PRCPHAIL(:,:)  = huge(1.0)
    noahowpgrid%SOLDN(:,:)     = huge(1.0)
    noahowpgrid%LWDN(:,:)      = huge(1.0) 
    noahowpgrid%FOLN(:,:)      = huge(1.0) 
    noahowpgrid%O2PP(:,:)      = huge(1.0) 
    noahowpgrid%CO2PP(:,:)     = huge(1.0) 
    noahowpgrid%UU(:,:)        = huge(1.0)
    noahowpgrid%VV(:,:)        = huge(1.0)
    noahowpgrid%TBOT(:,:)      = huge(1.0)
    noahowpgrid%UR(:,:)        = huge(1.0)
    noahowpgrid%THAIR(:,:)     = huge(1.0)
    noahowpgrid%QAIR(:,:)      = huge(1.0)
    noahowpgrid%EAIR(:,:)      = huge(1.0)
    noahowpgrid%RHOAIR(:,:)    = huge(1.0)
    noahowpgrid%FPICE(:,:)     = huge(1.0)
    noahowpgrid%SWDOWN(:,:)    = huge(1.0)
    noahowpgrid%JULIAN         = huge(1.0)
    noahowpgrid%YEARLEN        = huge(1)
    noahowpgrid%SOLAD(:,:,:)   = huge(1.0)
    noahowpgrid%SOLAI(:,:,:)   = huge(1.0)

  end subroutine ForcingTypeDefault

  subroutine EnergyTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x   => noahowpgrid%n_x,   &
              n_y   => noahowpgrid%n_y,   &
              nsoil => noahowpgrid%nsoil, &
              nsnow => noahowpgrid%nsnow  &
             )

    if(.NOT.allocated(noahowpgrid%ALB)) allocate(noahowpgrid%ALB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ALBD)) allocate(noahowpgrid%ALBD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBGRD)) allocate(noahowpgrid%ALBGRD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBGRI)) allocate(noahowpgrid%ALBGRI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBI)) allocate(noahowpgrid%ALBI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBOLD)) allocate(noahowpgrid%ALBOLD(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ALBSND)) allocate(noahowpgrid%ALBSND(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%ALBSNI)) allocate(noahowpgrid%ALBSNI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%APAR)) allocate(noahowpgrid%APAR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%BGAP)) allocate(noahowpgrid%BGAP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CAH2)) allocate(noahowpgrid%CAH2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CH)) allocate(noahowpgrid%CH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHB)) allocate(noahowpgrid%CHB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHB2)) allocate(noahowpgrid%CHB2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHLEAF)) allocate(noahowpgrid%CHLEAF(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHUC)) allocate(noahowpgrid%CHUC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHV)) allocate(noahowpgrid%CHV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CHV2)) allocate(noahowpgrid%CHV2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CM)) allocate(noahowpgrid%CM(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CMB)) allocate(noahowpgrid%CMB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%CMV)) allocate(noahowpgrid%CMV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%COSZ)) allocate(noahowpgrid%COSZ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%COSZ_HORIZ)) allocate(noahowpgrid%COSZ_HORIZ(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%DF)) allocate(noahowpgrid%DF(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%EAH)) allocate(noahowpgrid%EAH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EHB2)) allocate(noahowpgrid%EHB2(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EMG)) allocate(noahowpgrid%EMG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EMISSI)) allocate(noahowpgrid%EMISSI(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EMV)) allocate(noahowpgrid%EMV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EVB)) allocate(noahowpgrid%EVB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EVC)) allocate(noahowpgrid%EVC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%EVG)) allocate(noahowpgrid%EVG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FABD)) allocate(noahowpgrid%FABD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FABI)) allocate(noahowpgrid%FABI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FACT)) allocate(noahowpgrid%FACT(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%FAGE)) allocate(noahowpgrid%FAGE(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FCEV)) allocate(noahowpgrid%FCEV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FCTR)) allocate(noahowpgrid%FCTR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FGEV)) allocate(noahowpgrid%FGEV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FIRA)) allocate(noahowpgrid%FIRA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FREGD)) allocate(noahowpgrid%FREGD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FREGI)) allocate(noahowpgrid%FREGI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FREVD)) allocate(noahowpgrid%FREVD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FREVI)) allocate(noahowpgrid%FREVI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FROZEN_CANOPY)) allocate(noahowpgrid%FROZEN_CANOPY(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FROZEN_GROUND)) allocate(noahowpgrid%FROZEN_GROUND(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSA)) allocate(noahowpgrid%FSA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSH)) allocate(noahowpgrid%FSH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSHA)) allocate(noahowpgrid%FSHA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSR)) allocate(noahowpgrid%FSR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSRG)) allocate(noahowpgrid%FSRG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSRV)) allocate(noahowpgrid%FSRV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FSUN)) allocate(noahowpgrid%FSUN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%FTDD)) allocate(noahowpgrid%FTDD(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FTDI)) allocate(noahowpgrid%FTDI(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FTID)) allocate(noahowpgrid%FTID(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%FTII)) allocate(noahowpgrid%FTII(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%GAMMAG)) allocate(noahowpgrid%GAMMAG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%GAMMAV)) allocate(noahowpgrid%GAMMAV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%GH)) allocate(noahowpgrid%GH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%GHB)) allocate(noahowpgrid%GHB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%GHV)) allocate(noahowpgrid%GHV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%HCPCT)) allocate(noahowpgrid%HCPCT(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%ICE)) allocate(noahowpgrid%ICE(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%IGS)) allocate(noahowpgrid%IGS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%IMELT)) allocate(noahowpgrid%IMELT(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%IRB)) allocate(noahowpgrid%IRB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%IRC)) allocate(noahowpgrid%IRC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%IRG)) allocate(noahowpgrid%IRG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LAISHA)) allocate(noahowpgrid%LAISHA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LAISUN)) allocate(noahowpgrid%LAISUN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LATHEA)) allocate(noahowpgrid%LATHEA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LATHEAG)) allocate(noahowpgrid%LATHEAG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LATHEAV)) allocate(noahowpgrid%LATHEAV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%LH)) allocate(noahowpgrid%LH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PAH)) allocate(noahowpgrid%PAH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PAHB)) allocate(noahowpgrid%PAHB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PAHG)) allocate(noahowpgrid%PAHG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PAHV)) allocate(noahowpgrid%PAHV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PARSHA)) allocate(noahowpgrid%PARSHA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PARSUN)) allocate(noahowpgrid%PARSUN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PSN)) allocate(noahowpgrid%PSN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PSNSHA)) allocate(noahowpgrid%PSNSHA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%PSNSUN)) allocate(noahowpgrid%PSNSUN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Q1)) allocate(noahowpgrid%Q1(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Q2B)) allocate(noahowpgrid%Q2B(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Q2E)) allocate(noahowpgrid%Q2E(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Q2V)) allocate(noahowpgrid%Q2V(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QMELT)) allocate(noahowpgrid%QMELT(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%QSFC)) allocate(noahowpgrid%QSFC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RB)) allocate(noahowpgrid%RB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RHO)) allocate(noahowpgrid%RHO(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%RHSUR)) allocate(noahowpgrid%RHSUR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RSSHA)) allocate(noahowpgrid%RSSHA(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RSSUN)) allocate(noahowpgrid%RSSUN(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%RSURF)) allocate(noahowpgrid%RSURF(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SAG)) allocate(noahowpgrid%SAG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SAV)) allocate(noahowpgrid%SAV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SHB)) allocate(noahowpgrid%SHB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SHC)) allocate(noahowpgrid%SHC(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SHG)) allocate(noahowpgrid%SHG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%SSOIL)) allocate(noahowpgrid%SSOIL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%STC)) allocate(noahowpgrid%STC(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%T2M)) allocate(noahowpgrid%T2M(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%T2MB)) allocate(noahowpgrid%T2MB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%T2MV)) allocate(noahowpgrid%T2MV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAH)) allocate(noahowpgrid%TAH(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAU)) allocate(noahowpgrid%TAU(n_x,n_y,2))
    if(.NOT.allocated(noahowpgrid%TAUSS)) allocate(noahowpgrid%TAUSS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUX)) allocate(noahowpgrid%TAUX(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUXB)) allocate(noahowpgrid%TAUXB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUXV)) allocate(noahowpgrid%TAUXV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUY)) allocate(noahowpgrid%TAUY(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUYB)) allocate(noahowpgrid%TAUYB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TAUYV)) allocate(noahowpgrid%TAUYV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TG)) allocate(noahowpgrid%TG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TGB)) allocate(noahowpgrid%TGB(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TGS)) allocate(noahowpgrid%TGS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TGV)) allocate(noahowpgrid%TGV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TR)) allocate(noahowpgrid%TR(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TRAD)) allocate(noahowpgrid%TRAD(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TS)) allocate(noahowpgrid%TS(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%TV)) allocate(noahowpgrid%TV(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%WGAP)) allocate(noahowpgrid%WGAP(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Z0M)) allocate(noahowpgrid%Z0M(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Z0MG)) allocate(noahowpgrid%Z0MG(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%Z0WRF)) allocate(noahowpgrid%Z0WRF(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ZLVL)) allocate(noahowpgrid%ZLVL(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ZPD)) allocate(noahowpgrid%ZPD(n_x,n_y))

    end associate

  end subroutine EnergyTypeAllocate

  subroutine EnergyTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%ALB(:,:) = huge(1.0)
    noahowpgrid%ALBD(:,:,:) = huge(1.0)
    noahowpgrid%ALBGRD(:,:,:) = huge(1.0)
    noahowpgrid%ALBGRI(:,:,:) = huge(1.0)
    noahowpgrid%ALBI(:,:,:) = huge(1.0)
    noahowpgrid%ALBOLD(:,:) = huge(1.0)
    noahowpgrid%ALBSND(:,:,:) = huge(1.0)
    noahowpgrid%ALBSNI(:,:,:) = huge(1.0)
    noahowpgrid%APAR(:,:) = huge(1.0)
    noahowpgrid%BGAP(:,:) = huge(1.0)
    noahowpgrid%CAH2(:,:) = huge(1.0)
    noahowpgrid%CH(:,:) = huge(1.0)
    noahowpgrid%CHB(:,:) = huge(1.0)
    noahowpgrid%CHB2(:,:) = huge(1.0)
    noahowpgrid%CHLEAF(:,:) = huge(1.0)
    noahowpgrid%CHUC(:,:) = huge(1.0)
    noahowpgrid%CHV(:,:) = huge(1.0)
    noahowpgrid%CHV2(:,:) = huge(1.0)
    noahowpgrid%CM(:,:) = huge(1.0)
    noahowpgrid%CMB(:,:) = huge(1.0)
    noahowpgrid%CMV(:,:) = huge(1.0)
    noahowpgrid%COSZ(:,:) = huge(1.0)
    noahowpgrid%COSZ_HORIZ(:,:) = huge(1.0)
    noahowpgrid%DF(:,:,:) = huge(1.0)
    noahowpgrid%EAH(:,:) = huge(1.0)
    noahowpgrid%EHB2(:,:) = huge(1.0)
    noahowpgrid%EMG(:,:) = huge(1.0)
    noahowpgrid%EMISSI(:,:) = huge(1.0)
    noahowpgrid%EMV(:,:) = huge(1.0)
    noahowpgrid%EVB(:,:) = huge(1.0)
    noahowpgrid%EVC(:,:) = huge(1.0)
    noahowpgrid%EVG(:,:) = huge(1.0)
    noahowpgrid%FABD(:,:,:) = huge(1.0)
    noahowpgrid%FABI(:,:,:) = huge(1.0)
    noahowpgrid%FACT(:,:,:) = huge(1.0)
    noahowpgrid%FAGE(:,:) = huge(1.0)
    noahowpgrid%FCEV(:,:) = huge(1.0)
    noahowpgrid%FCTR(:,:) = huge(1.0)
    noahowpgrid%FGEV(:,:) = huge(1.0)
    noahowpgrid%FIRA(:,:) = huge(1.0)
    noahowpgrid%FREGD(:,:,:) = huge(1.0)
    noahowpgrid%FREGI(:,:,:) = huge(1.0)
    noahowpgrid%FREVD(:,:,:) = huge(1.0)
    noahowpgrid%FREVI(:,:,:) = huge(1.0)
    noahowpgrid%FROZEN_CANOPY(:,:) = .FALSE.
    noahowpgrid%FROZEN_GROUND(:,:) = .FALSE.
    noahowpgrid%FSA(:,:) = huge(1.0)
    noahowpgrid%FSH(:,:) = huge(1.0)
    noahowpgrid%FSHA(:,:) = huge(1.0)
    noahowpgrid%FSR(:,:) = huge(1.0)
    noahowpgrid%FSRG(:,:) = huge(1.0)
    noahowpgrid%FSRV(:,:) = huge(1.0)
    noahowpgrid%FSUN(:,:) = huge(1.0)
    noahowpgrid%FTDD(:,:,:) = huge(1.0)
    noahowpgrid%FTDI(:,:,:) = huge(1.0)
    noahowpgrid%FTID(:,:,:) = huge(1.0)
    noahowpgrid%FTII(:,:,:) = huge(1.0)
    noahowpgrid%GAMMAG(:,:) = huge(1.0)
    noahowpgrid%GAMMAV(:,:) = huge(1.0)
    noahowpgrid%GH(:,:) = huge(1.0)
    noahowpgrid%GHB(:,:) = huge(1.0)
    noahowpgrid%GHV(:,:) = huge(1.0)
    noahowpgrid%HCPCT(:,:,:) = huge(1.0)
    noahowpgrid%ICE(:,:) = huge(1)
    noahowpgrid%IGS(:,:) = huge(1.0)
    noahowpgrid%IMELT(:,:,:) = huge(1)
    noahowpgrid%IRB(:,:) = huge(1.0)
    noahowpgrid%IRC(:,:) = huge(1.0)
    noahowpgrid%IRG(:,:) = huge(1.0)
    noahowpgrid%LAISHA(:,:) = huge(1.0)
    noahowpgrid%LAISUN(:,:) = huge(1.0)
    noahowpgrid%LATHEA(:,:) = huge(1.0)
    noahowpgrid%LATHEAG(:,:) = huge(1.0)
    noahowpgrid%LATHEAV(:,:) = huge(1.0)
    noahowpgrid%LH(:,:) = huge(1.0)
    noahowpgrid%PAH(:,:) = huge(1.0)
    noahowpgrid%PAHB(:,:) = huge(1.0)
    noahowpgrid%PAHG(:,:) = huge(1.0)
    noahowpgrid%PAHV(:,:) = huge(1.0)
    noahowpgrid%PARSHA(:,:) = huge(1.0)
    noahowpgrid%PARSUN(:,:) = huge(1.0)
    noahowpgrid%PSN(:,:) = huge(1.0)
    noahowpgrid%PSNSHA(:,:) = huge(1.0)
    noahowpgrid%PSNSUN(:,:) = huge(1.0)
    noahowpgrid%Q1(:,:) = huge(1.0)
    noahowpgrid%Q2B(:,:) = huge(1.0)
    noahowpgrid%Q2E(:,:) = huge(1.0)
    noahowpgrid%Q2V(:,:) = huge(1.0)
    noahowpgrid%QMELT(:,:) = huge(1.0)
    noahowpgrid%QSFC(:,:) = huge(1.0)
    noahowpgrid%RB(:,:) = huge(1.0)
    noahowpgrid%RHO(:,:,:) = huge(1.0)
    noahowpgrid%RHSUR(:,:) = huge(1.0)
    noahowpgrid%RSSHA(:,:) = huge(1.0)
    noahowpgrid%RSSUN(:,:) = huge(1.0)
    noahowpgrid%RSURF(:,:) = huge(1.0)
    noahowpgrid%SAG(:,:) = huge(1.0)
    noahowpgrid%SAV(:,:) = huge(1.0)
    noahowpgrid%SHB(:,:) = huge(1.0)
    noahowpgrid%SHC(:,:) = huge(1.0)
    noahowpgrid%SHG(:,:) = huge(1.0)
    noahowpgrid%SSOIL(:,:) = huge(1.0)
    noahowpgrid%STC(:,:,:) = huge(1.0)
    noahowpgrid%T2M(:,:) = huge(1.0)
    noahowpgrid%T2MB(:,:) = huge(1.0)
    noahowpgrid%T2MV(:,:) = huge(1.0)
    noahowpgrid%TAH(:,:) = huge(1.0)
    noahowpgrid%TAU(:,:,:) = huge(1.0)
    noahowpgrid%TAUSS(:,:) = huge(1.0)
    noahowpgrid%TAUX(:,:) = huge(1.0)
    noahowpgrid%TAUXB(:,:) = huge(1.0)
    noahowpgrid%TAUXV(:,:) = huge(1.0)
    noahowpgrid%TAUY(:,:) = huge(1.0)
    noahowpgrid%TAUYB(:,:) = huge(1.0)
    noahowpgrid%TAUYV(:,:) = huge(1.0)
    noahowpgrid%TG(:,:) = huge(1.0)
    noahowpgrid%TGB(:,:) = huge(1.0)
    noahowpgrid%TGS(:,:) = huge(1.0)
    noahowpgrid%TGV(:,:) = huge(1.0)
    noahowpgrid%TR(:,:) = huge(1.0)
    noahowpgrid%TRAD(:,:) = huge(1.0)
    noahowpgrid%TS(:,:) = huge(1.0)
    noahowpgrid%TV(:,:) = huge(1.0)
    noahowpgrid%WGAP(:,:) = huge(1.0)
    noahowpgrid%Z0M(:,:) = huge(1.0)
    noahowpgrid%Z0MG(:,:) = huge(1.0)
    noahowpgrid%Z0WRF(:,:) = huge(1.0)
    noahowpgrid%ZLVL(:,:) = huge(1.0)
    noahowpgrid%ZPD(:,:) = huge(1.0)

  end subroutine EnergyTypeDefault

  subroutine DomainTypeAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(n_x   => noahowpgrid%n_x,   &
              n_y   => noahowpgrid%n_y,   &
              nsoil => noahowpgrid%nsoil, &
              nsnow => noahowpgrid%nsnow  &
             )

    if(.NOT.allocated(noahowpgrid%lat))             allocate(noahowpgrid%lat(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%lon))             allocate(noahowpgrid%lon(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%ZREF))            allocate(noahowpgrid%ZREF(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%terrain_slope))   allocate(noahowpgrid%terrain_slope(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%azimuth))         allocate(noahowpgrid%azimuth(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%vegtyp))          allocate(noahowpgrid%vegtyp(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%isltyp))          allocate(noahowpgrid%isltyp(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%IST))             allocate(noahowpgrid%IST(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%croptype))        allocate(noahowpgrid%croptype(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%soilcolor))       allocate(noahowpgrid%soilcolor(n_x,n_y))
    if(.NOT.allocated(noahowpgrid%zsoil))           allocate(noahowpgrid%zsoil(n_x,n_y,nsoil))
    if(.NOT.allocated(noahowpgrid%dzsnso))          allocate(noahowpgrid%dzsnso(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(noahowpgrid%zsnso))           allocate(noahowpgrid%zsnso(n_x,n_y,-nsnow+1:nsoil))

    end associate

  end subroutine DomainTypeAllocate

  subroutine DomainTypeDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    noahowpgrid%dt                    = huge(1.0)
    noahowpgrid%startdate             = 'EMPTYDATE999'
    noahowpgrid%enddate               = 'EMPTYDATE999'
    noahowpgrid%nowdate               = 'EMPTYDATE999'
    noahowpgrid%start_datetime        = huge(1)
    noahowpgrid%end_datetime          = huge(1)
    noahowpgrid%curr_datetime         = huge(1)
    noahowpgrid%itime                 = huge(1) 
    noahowpgrid%ntime                 = huge(1) 
    noahowpgrid%time_dbl              = huge(1.d0)
    noahowpgrid%ix                    = huge(1)
    noahowpgrid%iy                    = huge(1)
    noahowpgrid%lat(:,:)              = huge(1.0)             
    noahowpgrid%lon(:,:)              = huge(1.0)           
    noahowpgrid%ZREF(:,:)             = huge(1.0)       
    noahowpgrid%terrain_slope(:,:)    = huge(1.0)   
    noahowpgrid%azimuth(:,:)          = huge(1.0)        
    noahowpgrid%vegtyp(:,:)           = huge(1)          
    noahowpgrid%croptype(:,:)         = huge(1)   
    noahowpgrid%isltyp(:,:)           = huge(1)  
    noahowpgrid%IST(:,:)              = huge(1)
    noahowpgrid%soilcolor(:,:)        = huge(1)          
    noahowpgrid%zsoil(:,:,:)          = huge(1.0)           
    noahowpgrid%dzsnso(:,:,:)         = huge(1.0)             
    noahowpgrid%zsnso(:,:,:)          = huge(1.0)          

  end subroutine DomainTypeDefault

  subroutine TableVarsAllocate(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid

    associate(MVT => noahowpgrid%MVT, &
              MBAND => noahowpgrid%MBAND, &
              MAX_SOILTYP => noahowpgrid%MAX_SOILTYP, &
              NCROP => noahowpgrid%NCROP, &
              MSC => noahowpgrid%MSC, &
              NSTAGE => noahowpgrid%NSTAGE &
             )

    if(.NOT.allocated(noahowpgrid%CH2OP_TABLE)) allocate(noahowpgrid%CH2OP_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%DLEAF_TABLE)) allocate(noahowpgrid%DLEAF_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%Z0MVT_TABLE)) allocate(noahowpgrid%Z0MVT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%HVT_TABLE)) allocate(noahowpgrid%HVT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%HVB_TABLE)) allocate(noahowpgrid%HVB_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%DEN_TABLE)) allocate(noahowpgrid%DEN_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RC_TABLE)) allocate(noahowpgrid%RC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%MFSNO_TABLE)) allocate(noahowpgrid%MFSNO_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%SCFFAC_TABLE)) allocate(noahowpgrid%SCFFAC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%SAIM_TABLE)) allocate(noahowpgrid%SAIM_TABLE(MVT,12))
    if(.NOT.allocated(noahowpgrid%LAIM_TABLE)) allocate(noahowpgrid%LAIM_TABLE(MVT,12))
    if(.NOT.allocated(noahowpgrid%SLA_TABLE)) allocate(noahowpgrid%SLA_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%DILEFC_TABLE)) allocate(noahowpgrid%DILEFC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%DILEFW_TABLE)) allocate(noahowpgrid%DILEFW_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%FRAGR_TABLE)) allocate(noahowpgrid%FRAGR_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%LTOVRC_TABLE)) allocate(noahowpgrid%LTOVRC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%C3PSN_TABLE)) allocate(noahowpgrid%C3PSN_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%KC25_TABLE)) allocate(noahowpgrid%KC25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%AKC_TABLE)) allocate(noahowpgrid%AKC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%KO25_TABLE)) allocate(noahowpgrid%KO25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%AKO_TABLE)) allocate(noahowpgrid%AKO_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%VCMX25_TABLE)) allocate(noahowpgrid%VCMX25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%AVCMX_TABLE)) allocate(noahowpgrid%AVCMX_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%BP_TABLE)) allocate(noahowpgrid%BP_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%MP_TABLE)) allocate(noahowpgrid%MP_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%QE25_TABLE)) allocate(noahowpgrid%QE25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%AQE_TABLE)) allocate(noahowpgrid%AQE_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RMF25_TABLE)) allocate(noahowpgrid%RMF25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RMS25_TABLE)) allocate(noahowpgrid%RMS25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RMR25_TABLE)) allocate(noahowpgrid%RMR25_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%ARM_TABLE)) allocate(noahowpgrid%ARM_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%FOLNMX_TABLE)) allocate(noahowpgrid%FOLNMX_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%TMIN_TABLE)) allocate(noahowpgrid%TMIN_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%XL_TABLE)) allocate(noahowpgrid%XL_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RHOL_TABLE)) allocate(noahowpgrid%RHOL_TABLE(MVT,MBAND))
    if(.NOT.allocated(noahowpgrid%RHOS_TABLE)) allocate(noahowpgrid%RHOS_TABLE(MVT,MBAND))
    if(.NOT.allocated(noahowpgrid%TAUL_TABLE)) allocate(noahowpgrid%TAUL_TABLE(MVT,MBAND))
    if(.NOT.allocated(noahowpgrid%TAUS_TABLE)) allocate(noahowpgrid%TAUS_TABLE(MVT,MBAND))
    if(.NOT.allocated(noahowpgrid%MRP_TABLE)) allocate(noahowpgrid%MRP_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%CWPVT_TABLE)) allocate(noahowpgrid%CWPVT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%WRRAT_TABLE)) allocate(noahowpgrid%WRRAT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%WDPOOL_TABLE)) allocate(noahowpgrid%WDPOOL_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%TDLEF_TABLE)) allocate(noahowpgrid%TDLEF_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%SHDFAC_TABLE)) allocate(noahowpgrid%SHDFAC_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%NROOT_TABLE)) allocate(noahowpgrid%NROOT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RGL_TABLE)) allocate(noahowpgrid%RGL_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RS_TABLE)) allocate(noahowpgrid%RS_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%HS_TABLE)) allocate(noahowpgrid%HS_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%TOPT_TABLE)) allocate(noahowpgrid%TOPT_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%RSMAX_TABLE)) allocate(noahowpgrid%RSMAX_TABLE(MVT))
    if(.NOT.allocated(noahowpgrid%BEXP_TABLE)) allocate(noahowpgrid%BEXP_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%SMCDRY_TABLE)) allocate(noahowpgrid%SMCDRY_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%F1_TABLE)) allocate(noahowpgrid%F1_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%SMCMAX_TABLE)) allocate(noahowpgrid%SMCMAX_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%SMCREF_TABLE)) allocate(noahowpgrid%SMCREF_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%PSISAT_TABLE)) allocate(noahowpgrid%PSISAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%DKSAT_TABLE)) allocate(noahowpgrid%DKSAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%DWSAT_TABLE)) allocate(noahowpgrid%DWSAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%SMCWLT_TABLE)) allocate(noahowpgrid%SMCWLT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%QUARTZ_TABLE)) allocate(noahowpgrid%QUARTZ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%BVIC_TABLE)) allocate(noahowpgrid%BVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%AXAJ_TABLE)) allocate(noahowpgrid%AXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%BXAJ_TABLE)) allocate(noahowpgrid%BXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%XXAJ_TABLE)) allocate(noahowpgrid%XXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%BDVIC_TABLE)) allocate(noahowpgrid%BDVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%GDVIC_TABLE)) allocate(noahowpgrid%GDVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%BBVIC_TABLE)) allocate(noahowpgrid%BBVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%SLOPE_TABLE)) allocate(noahowpgrid%SLOPE_TABLE(9))
    if(.NOT.allocated(noahowpgrid%ALBSAT_TABLE)) allocate(noahowpgrid%ALBSAT_TABLE(MSC,MBAND))
    if(.NOT.allocated(noahowpgrid%ALBDRY_TABLE)) allocate(noahowpgrid%ALBDRY_TABLE(MSC,MBAND))
    if(.NOT.allocated(noahowpgrid%ALBICE_TABLE)) allocate(noahowpgrid%ALBICE_TABLE(MBAND))
    if(.NOT.allocated(noahowpgrid%ALBLAK_TABLE)) allocate(noahowpgrid%ALBLAK_TABLE(MBAND))
    if(.NOT.allocated(noahowpgrid%OMEGAS_TABLE)) allocate(noahowpgrid%OMEGAS_TABLE(MBAND))
    if(.NOT.allocated(noahowpgrid%EG_TABLE)) allocate(noahowpgrid%EG_TABLE(2))
    if(.NOT.allocated(noahowpgrid%PLTDAY_TABLE)) allocate(noahowpgrid%PLTDAY_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%HSDAY_TABLE)) allocate(noahowpgrid%HSDAY_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%PLANTPOP_TABLE)) allocate(noahowpgrid%PLANTPOP_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%IRRI_TABLE)) allocate(noahowpgrid%IRRI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDTBASE_TABLE)) allocate(noahowpgrid%GDDTBASE_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDTCUT_TABLE)) allocate(noahowpgrid%GDDTCUT_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDS1_TABLE)) allocate(noahowpgrid%GDDS1_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDS2_TABLE)) allocate(noahowpgrid%GDDS2_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDS3_TABLE)) allocate(noahowpgrid%GDDS3_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDS4_TABLE)) allocate(noahowpgrid%GDDS4_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GDDS5_TABLE)) allocate(noahowpgrid%GDDS5_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%C3PSNI_TABLE)) allocate(noahowpgrid%C3PSNI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%KC25I_TABLE)) allocate(noahowpgrid%KC25I_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%AKCI_TABLE)) allocate(noahowpgrid%AKCI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%KO25I_TABLE)) allocate(noahowpgrid%KO25I_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%AKOI_TABLE)) allocate(noahowpgrid%AKOI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%VCMX25I_TABLE)) allocate(noahowpgrid%VCMX25I_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%AVCMXI_TABLE)) allocate(noahowpgrid%AVCMXI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%BPI_TABLE)) allocate(noahowpgrid%BPI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%MPI_TABLE)) allocate(noahowpgrid%MPI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%QE25I_TABLE)) allocate(noahowpgrid%QE25I_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%FOLNMXI_TABLE)) allocate(noahowpgrid%FOLNMXI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%C3C4_TABLE)) allocate(noahowpgrid%C3C4_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%AREF_TABLE)) allocate(noahowpgrid%AREF_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%PSNRF_TABLE)) allocate(noahowpgrid%PSNRF_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%I2PAR_TABLE)) allocate(noahowpgrid%I2PAR_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%TASSIM0_TABLE)) allocate(noahowpgrid%TASSIM0_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%TASSIM1_TABLE)) allocate(noahowpgrid%TASSIM1_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%TASSIM2_TABLE)) allocate(noahowpgrid%TASSIM2_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%K_TABLE)) allocate(noahowpgrid%K_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%EPSI_TABLE)) allocate(noahowpgrid%EPSI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%Q10MR_TABLE)) allocate(noahowpgrid%Q10MR_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%FOLN_MX_TABLE)) allocate(noahowpgrid%FOLN_MX_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%LEFREEZ_TABLE)) allocate(noahowpgrid%LEFREEZ_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%DILE_FC_TABLE)) allocate(noahowpgrid%DILE_FC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%DILE_FW_TABLE)) allocate(noahowpgrid%DILE_FW_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%FRA_GR_TABLE)) allocate(noahowpgrid%FRA_GR_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%LF_OVRC_TABLE)) allocate(noahowpgrid%LF_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%ST_OVRC_TABLE)) allocate(noahowpgrid%ST_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%RT_OVRC_TABLE)) allocate(noahowpgrid%RT_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%LFMR25_TABLE)) allocate(noahowpgrid%LFMR25_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%STMR25_TABLE)) allocate(noahowpgrid%STMR25_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%RTMR25_TABLE)) allocate(noahowpgrid%RTMR25_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%GRAINMR25_TABLE)) allocate(noahowpgrid%GRAINMR25_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%LFPT_TABLE)) allocate(noahowpgrid%LFPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%STPT_TABLE)) allocate(noahowpgrid%STPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%RTPT_TABLE)) allocate(noahowpgrid%RTPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%GRAINPT_TABLE)) allocate(noahowpgrid%GRAINPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%LFCT_TABLE)) allocate(noahowpgrid%LFCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%STCT_TABLE)) allocate(noahowpgrid%STCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%RTCT_TABLE)) allocate(noahowpgrid%RTCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(noahowpgrid%BIO2LAI_TABLE)) allocate(noahowpgrid%BIO2LAI_TABLE(NCROP))
    if(.NOT.allocated(noahowpgrid%TDSMCFAC_TABLE)) allocate(noahowpgrid%TDSMCFAC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_DC_TABLE)) allocate(noahowpgrid%TD_DC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_DEPTH_TABLE)) allocate(noahowpgrid%TD_DEPTH_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_DCOEF_TABLE)) allocate(noahowpgrid%TD_DCOEF_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_D_TABLE)) allocate(noahowpgrid%TD_D_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_ADEPTH_TABLE)) allocate(noahowpgrid%TD_ADEPTH_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_RADI_TABLE)) allocate(noahowpgrid%TD_RADI_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_SPAC_TABLE)) allocate(noahowpgrid%TD_SPAC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%TD_DDRAIN_TABLE)) allocate(noahowpgrid%TD_DDRAIN_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(noahowpgrid%KLAT_FAC_TABLE)) allocate(noahowpgrid%KLAT_FAC_TABLE(MAX_SOILTYP))  

    end associate

  end subroutine TableVarsAllocate

  subroutine TableVarsDefault(noahowpgrid)

    implicit none
    type(noahowpgrid_type), intent(inout) :: noahowpgrid        

    noahowpgrid%ISURBAN_TABLE = huge(1)
    noahowpgrid%ISWATER_TABLE = huge(1)
    noahowpgrid%ISBARREN_TABLE = huge(1)
    noahowpgrid%ISICE_TABLE = huge(1)
    noahowpgrid%ISCROP_TABLE = huge(1)
    noahowpgrid%EBLFOREST_TABLE = huge(1)
    noahowpgrid%NATURAL_TABLE = huge(1)
    noahowpgrid%LCZ_1_TABLE = huge(1)
    noahowpgrid%LCZ_2_TABLE = huge(1)
    noahowpgrid%LCZ_3_TABLE = huge(1)
    noahowpgrid%LCZ_4_TABLE = huge(1)
    noahowpgrid%LCZ_5_TABLE = huge(1)
    noahowpgrid%LCZ_6_TABLE = huge(1)
    noahowpgrid%LCZ_7_TABLE = huge(1)
    noahowpgrid%LCZ_8_TABLE = huge(1)
    noahowpgrid%LCZ_9_TABLE = huge(1)
    noahowpgrid%LCZ_10_TABLE = huge(1)
    noahowpgrid%LCZ_11_TABLE = huge(1)
    noahowpgrid%CH2OP_TABLE(:) = huge(1.0)
    noahowpgrid%DLEAF_TABLE(:) = huge(1.0)
    noahowpgrid%Z0MVT_TABLE(:) = huge(1.0)
    noahowpgrid%HVT_TABLE(:) = huge(1.0)
    noahowpgrid%HVB_TABLE(:) = huge(1.0)
    noahowpgrid%DEN_TABLE(:) = huge(1.0)
    noahowpgrid%RC_TABLE(:) = huge(1.0)
    noahowpgrid%MFSNO_TABLE(:) = huge(1.0)
    noahowpgrid%SCFFAC_TABLE(:) = huge(1.0)
    noahowpgrid%SAIM_TABLE(:,:) = huge(1.0)
    noahowpgrid%LAIM_TABLE(:,:) = huge(1.0)
    noahowpgrid%SLA_TABLE(:) = huge(1.0)
    noahowpgrid%DILEFC_TABLE(:) = huge(1.0)
    noahowpgrid%DILEFW_TABLE(:) = huge(1.0)
    noahowpgrid%FRAGR_TABLE(:) = huge(1.0)
    noahowpgrid%LTOVRC_TABLE(:) = huge(1.0)
    noahowpgrid%C3PSN_TABLE(:) = huge(1.0)
    noahowpgrid%KC25_TABLE(:) = huge(1.0)
    noahowpgrid%AKC_TABLE(:) = huge(1.0)
    noahowpgrid%KO25_TABLE(:) = huge(1.0)
    noahowpgrid%AKO_TABLE(:) = huge(1.0)
    noahowpgrid%VCMX25_TABLE(:) = huge(1.0)
    noahowpgrid%AVCMX_TABLE(:) = huge(1.0)
    noahowpgrid%BP_TABLE(:) = huge(1.0)
    noahowpgrid%MP_TABLE(:) = huge(1.0)
    noahowpgrid%QE25_TABLE(:) = huge(1.0)
    noahowpgrid%AQE_TABLE(:) = huge(1.0)
    noahowpgrid%RMF25_TABLE(:) = huge(1.0)
    noahowpgrid%RMS25_TABLE(:) = huge(1.0)
    noahowpgrid%RMR25_TABLE(:) = huge(1.0)
    noahowpgrid%ARM_TABLE(:) = huge(1.0)
    noahowpgrid%FOLNMX_TABLE(:) = huge(1.0)
    noahowpgrid%TMIN_TABLE(:) = huge(1.0)
    noahowpgrid%XL_TABLE(:) = huge(1.0)
    noahowpgrid%RHOL_TABLE(:,:) = huge(1.0)
    noahowpgrid%RHOS_TABLE(:,:) = huge(1.0)
    noahowpgrid%TAUL_TABLE(:,:) = huge(1.0)
    noahowpgrid%TAUS_TABLE(:,:) = huge(1.0)
    noahowpgrid%MRP_TABLE(:) = huge(1.0)
    noahowpgrid%CWPVT_TABLE(:) = huge(1.0)
    noahowpgrid%WRRAT_TABLE(:) = huge(1.0)
    noahowpgrid%WDPOOL_TABLE(:) = huge(1.0)
    noahowpgrid%TDLEF_TABLE(:) = huge(1.0)
    noahowpgrid%SHDFAC_TABLE(:) = huge(1.0)
    noahowpgrid%NROOT_TABLE(:) = huge(1.0)
    noahowpgrid%RGL_TABLE(:) = huge(1.0)
    noahowpgrid%RS_TABLE(:) = huge(1.0)
    noahowpgrid%HS_TABLE(:) = huge(1.0)
    noahowpgrid%TOPT_TABLE(:) = huge(1.0)
    noahowpgrid%RSMAX_TABLE(:) = huge(1.0)
    noahowpgrid%SLCATS = huge(1)
    noahowpgrid%BEXP_TABLE(:) = huge(1.0)
    noahowpgrid%SMCDRY_TABLE(:) = huge(1.0)
    noahowpgrid%F1_TABLE(:) = huge(1.0)
    noahowpgrid%SMCMAX_TABLE(:) = huge(1.0)
    noahowpgrid%SMCREF_TABLE(:) = huge(1.0)
    noahowpgrid%PSISAT_TABLE(:) = huge(1.0)
    noahowpgrid%DKSAT_TABLE(:) = huge(1.0)
    noahowpgrid%DWSAT_TABLE(:) = huge(1.0)
    noahowpgrid%SMCWLT_TABLE(:) = huge(1.0)
    noahowpgrid%QUARTZ_TABLE(:) = huge(1.0)
    noahowpgrid%BVIC_TABLE(:) = huge(1.0)
    noahowpgrid%AXAJ_TABLE(:) = huge(1.0)
    noahowpgrid%BXAJ_TABLE(:) = huge(1.0)
    noahowpgrid%XXAJ_TABLE(:) = huge(1.0)
    noahowpgrid%BDVIC_TABLE(:) = huge(1.0)
    noahowpgrid%GDVIC_TABLE(:) = huge(1.0)
    noahowpgrid%BBVIC_TABLE(:) = huge(1.0)
    noahowpgrid%SLOPE_TABLE(:) = huge(1.0)
    noahowpgrid%CSOIL_TABLE = huge(1.0)
    noahowpgrid%REFDK_TABLE = huge(1.0)
    noahowpgrid%REFKDT_TABLE = huge(1.0)
    noahowpgrid%FRZK_TABLE = huge(1.0)
    noahowpgrid%ZBOT_TABLE = huge(1.0)
    noahowpgrid%CZIL_TABLE = huge(1.0)
    noahowpgrid%Z0_TABLE = huge(1.0)
    noahowpgrid%ALBSAT_TABLE(:,:) = huge(1.0)
    noahowpgrid%ALBDRY_TABLE(:,:) = huge(1.0)
    noahowpgrid%ALBICE_TABLE(:) = huge(1.0)
    noahowpgrid%ALBLAK_TABLE(:) = huge(1.0)
    noahowpgrid%OMEGAS_TABLE(:) = huge(1.0)
    noahowpgrid%BETADS_TABLE = huge(1.0)
    noahowpgrid%BETAIS_TABLE = huge(1.0)
    noahowpgrid%EG_TABLE(:) = huge(1.0)
    noahowpgrid%CO2_TABLE = huge(1.0)
    noahowpgrid%O2_TABLE = huge(1.0)
    noahowpgrid%TIMEAN_TABLE = huge(1.0)
    noahowpgrid%FSATMX_TABLE = huge(1.0)
    noahowpgrid%Z0SNO_TABLE = huge(1.0)
    noahowpgrid%SSI_TABLE = huge(1.0)
    noahowpgrid%SNOW_RET_FAC_TABLE = huge(1.0)
    noahowpgrid%SNOW_EMIS_TABLE = huge(1.0)
    noahowpgrid%SWEMX_TABLE = huge(1.0)
    noahowpgrid%TAU0_TABLE = huge(1.0)
    noahowpgrid%GRAIN_GROWTH_TABLE = huge(1.0)
    noahowpgrid%EXTRA_GROWTH_TABLE = huge(1.0)
    noahowpgrid%DIRT_SOOT_TABLE = huge(1.0)
    noahowpgrid%BATS_COSZ_TABLE = huge(1.0)
    noahowpgrid%BATS_VIS_NEW_TABLE = huge(1.0)
    noahowpgrid%BATS_NIR_NEW_TABLE = huge(1.0)
    noahowpgrid%BATS_VIS_AGE_TABLE = huge(1.0)
    noahowpgrid%BATS_NIR_AGE_TABLE = huge(1.0)
    noahowpgrid%BATS_VIS_DIR_TABLE = huge(1.0)
    noahowpgrid%BATS_NIR_DIR_TABLE = huge(1.0)
    noahowpgrid%RSURF_SNOW_TABLE = huge(1.0)
    noahowpgrid%RSURF_EXP_TABLE = huge(1.0)
    noahowpgrid%DEFAULT_CROP_TABLE = huge(1)
    noahowpgrid%PLTDAY_TABLE(:) = huge(1)
    noahowpgrid%HSDAY_TABLE(:) = huge(1)
    noahowpgrid%PLANTPOP_TABLE(:) = huge(1.0)
    noahowpgrid%IRRI_TABLE(:) = huge(1.0)
    noahowpgrid%GDDTBASE_TABLE(:) = huge(1.0)
    noahowpgrid%GDDTCUT_TABLE(:) = huge(1.0)
    noahowpgrid%GDDS1_TABLE(:) = huge(1.0)
    noahowpgrid%GDDS2_TABLE(:) = huge(1.0)
    noahowpgrid%GDDS3_TABLE(:) = huge(1.0)
    noahowpgrid%GDDS4_TABLE(:) = huge(1.0)
    noahowpgrid%GDDS5_TABLE(:) = huge(1.0)
    noahowpgrid%C3PSNI_TABLE(:) = huge(1.0)
    noahowpgrid%KC25I_TABLE(:) = huge(1.0)
    noahowpgrid%AKCI_TABLE(:) = huge(1.0)
    noahowpgrid%KO25I_TABLE(:) = huge(1.0)
    noahowpgrid%AKOI_TABLE(:) = huge(1.0)
    noahowpgrid%VCMX25I_TABLE(:) = huge(1.0)
    noahowpgrid%AVCMXI_TABLE(:) = huge(1.0)
    noahowpgrid%BPI_TABLE(:) = huge(1.0)
    noahowpgrid%MPI_TABLE(:) = huge(1.0)
    noahowpgrid%QE25I_TABLE(:) = huge(1.0)
    noahowpgrid%FOLNMXI_TABLE(:) = huge(1.0)
    noahowpgrid%C3C4_TABLE(:) = huge(1)
    noahowpgrid%AREF_TABLE(:) = huge(1.0)
    noahowpgrid%PSNRF_TABLE(:) = huge(1.0)
    noahowpgrid%I2PAR_TABLE(:) = huge(1.0)
    noahowpgrid%TASSIM0_TABLE(:) = huge(1.0)
    noahowpgrid%TASSIM1_TABLE(:) = huge(1.0)
    noahowpgrid%TASSIM2_TABLE(:) = huge(1.0)
    noahowpgrid%K_TABLE(:) = huge(1.0)
    noahowpgrid%EPSI_TABLE(:) = huge(1.0)
    noahowpgrid%Q10MR_TABLE(:) = huge(1.0)
    noahowpgrid%FOLN_MX_TABLE(:) = huge(1.0)
    noahowpgrid%LEFREEZ_TABLE(:) = huge(1.0)
    noahowpgrid%DILE_FC_TABLE(:,:) = huge(1.0)
    noahowpgrid%DILE_FW_TABLE(:,:) = huge(1.0)
    noahowpgrid%FRA_GR_TABLE(:) = huge(1.0)
    noahowpgrid%LF_OVRC_TABLE(:,:) = huge(1.0)
    noahowpgrid%ST_OVRC_TABLE(:,:) = huge(1.0)
    noahowpgrid%RT_OVRC_TABLE(:,:) = huge(1.0)
    noahowpgrid%LFMR25_TABLE(:) = huge(1.0)
    noahowpgrid%STMR25_TABLE(:) = huge(1.0)
    noahowpgrid%RTMR25_TABLE(:) = huge(1.0)
    noahowpgrid%GRAINMR25_TABLE(:) = huge(1.0)
    noahowpgrid%LFPT_TABLE(:,:) = huge(1.0)
    noahowpgrid%STPT_TABLE(:,:) = huge(1.0)
    noahowpgrid%RTPT_TABLE(:,:) = huge(1.0)
    noahowpgrid%GRAINPT_TABLE(:,:) = huge(1.0)
    noahowpgrid%LFCT_TABLE(:,:) = huge(1.0)
    noahowpgrid%STCT_TABLE(:,:) = huge(1.0)
    noahowpgrid%RTCT_TABLE(:,:) = huge(1.0)
    noahowpgrid%BIO2LAI_TABLE(:) = huge(1.0)
    noahowpgrid%TDSMCFAC_TABLE(:) = huge(1.0)
    noahowpgrid%TD_DC_TABLE(:) = huge(1.0)
    noahowpgrid%TD_DEPTH_TABLE(:) = huge(1)
    noahowpgrid%DRAIN_LAYER_OPT_TABLE = huge(1)
    noahowpgrid%TD_DCOEF_TABLE(:) = huge(1.0)
    noahowpgrid%TD_D_TABLE(:) = huge(1.0)
    noahowpgrid%TD_ADEPTH_TABLE(:) = huge(1.0)
    noahowpgrid%TD_RADI_TABLE(:) = huge(1.0)
    noahowpgrid%TD_SPAC_TABLE(:) = huge(1.0)
    noahowpgrid%TD_DDRAIN_TABLE(:) = huge(1.0)
    noahowpgrid%KLAT_FAC_TABLE(:) = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_a = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_b = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_c = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_d = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_e = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_f = huge(1.0)
    noahowpgrid%sr2006_theta_1500t_g = huge(1.0)
    noahowpgrid%sr2006_theta_1500_a = huge(1.0)
    noahowpgrid%sr2006_theta_1500_b = huge(1.0)
    noahowpgrid%sr2006_theta_33t_a = huge(1.0)
    noahowpgrid%sr2006_theta_33t_b = huge(1.0)
    noahowpgrid%sr2006_theta_33t_c = huge(1.0)
    noahowpgrid%sr2006_theta_33t_d = huge(1.0)
    noahowpgrid%sr2006_theta_33t_e = huge(1.0)
    noahowpgrid%sr2006_theta_33t_f = huge(1.0)
    noahowpgrid%sr2006_theta_33t_g = huge(1.0)
    noahowpgrid%sr2006_theta_33_a = huge(1.0)
    noahowpgrid%sr2006_theta_33_b = huge(1.0)
    noahowpgrid%sr2006_theta_33_c = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_a = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_b = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_c = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_d = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_e = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_f = huge(1.0)
    noahowpgrid%sr2006_theta_s33t_g = huge(1.0)
    noahowpgrid%sr2006_theta_s33_a = huge(1.0)
    noahowpgrid%sr2006_theta_s33_b = huge(1.0)
    noahowpgrid%sr2006_psi_et_a = huge(1.0)
    noahowpgrid%sr2006_psi_et_b = huge(1.0)
    noahowpgrid%sr2006_psi_et_c = huge(1.0)
    noahowpgrid%sr2006_psi_et_d = huge(1.0)
    noahowpgrid%sr2006_psi_et_e = huge(1.0)
    noahowpgrid%sr2006_psi_et_f = huge(1.0)
    noahowpgrid%sr2006_psi_et_g = huge(1.0)
    noahowpgrid%sr2006_psi_e_a = huge(1.0)
    noahowpgrid%sr2006_psi_e_b = huge(1.0)
    noahowpgrid%sr2006_psi_e_c = huge(1.0)
    noahowpgrid%sr2006_smcmax_a = huge(1.0)
    noahowpgrid%sr2006_smcmax_b = huge(1.0)
    
  end subroutine TableVarsDefault

end module NoahowpGridTypeInitModule