module NoahowpmpIOTypeInitModule

  use NoahowpmpIOType
  
  implicit none
  
  contains

  subroutine NoahowpmpIOTypeInit(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    call DomainTypeAllocate(NoahowpmpIO)
    call DomainTypeDefault(NoahowpmpIO)
    call EnergyTypeAllocate(NoahowpmpIO)
    call EnergyTypeDefault(NoahowpmpIO)
    call ForcingTypeAllocate(NoahowpmpIO)
    call ForcingTypeDefault(NoahowpmpIO)
    call LevelsTypeAllocate(NoahowpmpIO)
    call LevelsTypeDefault(NoahowpmpIO)
    call OptionsTypeAllocate(NoahowpmpIO)
    call OptionsTypeDefault(NoahowpmpIO)
    call ParametersTypeAllocate(NoahowpmpIO)
    call ParametersTypeDefault(NoahowpmpIO)
    call WaterTypeAllocate(NoahowpmpIO)
    call WaterTypeDefault(NoahowpmpIO)
    call TableVarsAllocate(NoahowpmpIO)
    call TableVarsDefault(NoahowpmpIO)

  end subroutine NoahowpmpIOTypeInit

  subroutine WaterTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%qinsur)) allocate(NoahowpmpIO%qinsur(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%qseva)) allocate(NoahowpmpIO%qseva(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVAPOTRANS)) allocate(NoahowpmpIO%EVAPOTRANS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsrf)) allocate(NoahowpmpIO%runsrf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsub)) allocate(NoahowpmpIO%runsub(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%qdrain)) allocate(NoahowpmpIO%qdrain(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%zwt)) allocate(NoahowpmpIO%zwt(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%smcwtd)) allocate(NoahowpmpIO%smcwtd(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%deeprech)) allocate(NoahowpmpIO%deeprech(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%fcrmax)) allocate(NoahowpmpIO%fcrmax(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%snoflow)) allocate(NoahowpmpIO%snoflow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%pddum)) allocate(NoahowpmpIO%pddum(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FACC)) allocate(NoahowpmpIO%FACC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%sicemax)) allocate(NoahowpmpIO%sicemax(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FB_snow)) allocate(NoahowpmpIO%FB_snow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%rain)) allocate(NoahowpmpIO%rain(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%snow)) allocate(NoahowpmpIO%snow(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%bdfall)) allocate(NoahowpmpIO%bdfall(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FP)) allocate(NoahowpmpIO%FP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%canliq)) allocate(NoahowpmpIO%canliq(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%canice)) allocate(NoahowpmpIO%canice(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FWET)) allocate(NoahowpmpIO%FWET(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMC)) allocate(NoahowpmpIO%CMC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QINTR)) allocate(NoahowpmpIO%QINTR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDRIPR)) allocate(NoahowpmpIO%QDRIPR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QTHROR)) allocate(NoahowpmpIO%QTHROR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QINTS)) allocate(NoahowpmpIO%QINTS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDRIPS)) allocate(NoahowpmpIO%QDRIPS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QTHROS)) allocate(NoahowpmpIO%QTHROS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QRAIN)) allocate(NoahowpmpIO%QRAIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNOW)) allocate(NoahowpmpIO%QSNOW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNOWHIN)) allocate(NoahowpmpIO%SNOWHIN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ECAN)) allocate(NoahowpmpIO%ECAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ETRAN)) allocate(NoahowpmpIO%ETRAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNFRO)) allocate(NoahowpmpIO%QSNFRO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNSUB)) allocate(NoahowpmpIO%QSNSUB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNOWH)) allocate(NoahowpmpIO%SNOWH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNEQV)) allocate(NoahowpmpIO%SNEQV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SNEQVO)) allocate(NoahowpmpIO%SNEQVO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BDSNO)) allocate(NoahowpmpIO%BDSNO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSNBOT)) allocate(NoahowpmpIO%QSNBOT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING)) allocate(NoahowpmpIO%PONDING(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING1)) allocate(NoahowpmpIO%PONDING1(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PONDING2)) allocate(NoahowpmpIO%PONDING2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QVAP)) allocate(NoahowpmpIO%QVAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QDEW)) allocate(NoahowpmpIO%QDEW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSDEW)) allocate(NoahowpmpIO%QSDEW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%WSLAKE)) allocate(NoahowpmpIO%WSLAKE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%runsrf_dt)) allocate(NoahowpmpIO%runsrf_dt(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ASAT)) allocate(NoahowpmpIO%ASAT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ISNOW)) allocate(NoahowpmpIO%ISNOW(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%smc)) allocate(NoahowpmpIO%smc(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%smc_init)) allocate(NoahowpmpIO%smc_init(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%sice)) allocate(NoahowpmpIO%sice(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%sh2o)) allocate(NoahowpmpIO%sh2o(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%etrani)) allocate(NoahowpmpIO%etrani(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%BTRANI)) allocate(NoahowpmpIO%BTRANI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%wcnd)) allocate(NoahowpmpIO%wcnd(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%fcr)) allocate(NoahowpmpIO%fcr(NoahowpmpIO%n_x,NoahowpmpIO%n_y,NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%FICEOLD)) allocate(NoahowpmpIO%FICEOLD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNICE)) allocate(NoahowpmpIO%SNICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNLIQ)) allocate(NoahowpmpIO%SNLIQ(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNICEV)) allocate(NoahowpmpIO%SNICEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%SNLIQV)) allocate(NoahowpmpIO%SNLIQV(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%FICE)) allocate(NoahowpmpIO%FICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%EPORE)) allocate(NoahowpmpIO%EPORE(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:0))
    if(.NOT.allocated(NoahowpmpIO%FSNO)) allocate(NoahowpmpIO%FSNO(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BTRAN)) allocate(NoahowpmpIO%BTRAN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine WaterTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%qinsur(:,:) = huge(1.0)
    NoahowpmpIO%qseva(:,:) = huge(1.0)
    NoahowpmpIO%EVAPOTRANS(:,:) = huge(1.0)
    NoahowpmpIO%runsrf(:,:) = huge(1.0)
    NoahowpmpIO%runsub(:,:) = huge(1.0)
    NoahowpmpIO%qdrain(:,:) = huge(1.0)
    NoahowpmpIO%zwt(:,:) = huge(1.0)
    NoahowpmpIO%smcwtd(:,:) = huge(1.0)
    NoahowpmpIO%deeprech(:,:) = huge(1.0)
    NoahowpmpIO%fcrmax(:,:) = huge(1.0)
    NoahowpmpIO%snoflow(:,:) = huge(1.0)
    NoahowpmpIO%pddum(:,:) = huge(1.0)
    NoahowpmpIO%FACC(:,:) = huge(1.0)
    NoahowpmpIO%sicemax(:,:) = huge(1.0)
    NoahowpmpIO%FB_snow(:,:) = huge(1.0)
    NoahowpmpIO%rain(:,:) = huge(1.0)
    NoahowpmpIO%snow(:,:) = huge(1.0)
    NoahowpmpIO%bdfall(:,:) = huge(1.0)
    NoahowpmpIO%FP(:,:) = huge(1.0)
    NoahowpmpIO%canliq(:,:) = huge(1.0)
    NoahowpmpIO%canice(:,:) = huge(1.0)
    NoahowpmpIO%FWET(:,:) = huge(1.0)
    NoahowpmpIO%CMC(:,:) = huge(1.0)
    NoahowpmpIO%QINTR(:,:) = huge(1.0)
    NoahowpmpIO%QDRIPR(:,:) = huge(1.0)
    NoahowpmpIO%QTHROR(:,:) = huge(1.0)
    NoahowpmpIO%QINTS(:,:) = huge(1.0)
    NoahowpmpIO%QDRIPS(:,:) = huge(1.0)
    NoahowpmpIO%QTHROS(:,:) = huge(1.0)
    NoahowpmpIO%QRAIN(:,:) = huge(1.0)
    NoahowpmpIO%QSNOW(:,:) = huge(1.0)
    NoahowpmpIO%SNOWHIN(:,:) = huge(1.0)
    NoahowpmpIO%ECAN(:,:) = huge(1.0)
    NoahowpmpIO%ETRAN(:,:) = huge(1.0)
    NoahowpmpIO%QSNFRO(:,:) = huge(1.0)
    NoahowpmpIO%QSNSUB(:,:) = huge(1.0)
    NoahowpmpIO%SNOWH(:,:) = huge(1.0)
    NoahowpmpIO%SNEQV(:,:) = huge(1.0)
    NoahowpmpIO%SNEQVO(:,:) = huge(1.0)
    NoahowpmpIO%BDSNO(:,:) = huge(1.0)
    NoahowpmpIO%QSNBOT(:,:) = huge(1.0)
    NoahowpmpIO%PONDING(:,:) = huge(1.0)
    NoahowpmpIO%PONDING1(:,:) = huge(1.0)
    NoahowpmpIO%PONDING2(:,:) = huge(1.0)
    NoahowpmpIO%QVAP(:,:) = huge(1.0)
    NoahowpmpIO%QDEW(:,:) = huge(1.0)
    NoahowpmpIO%QSDEW(:,:) = huge(1.0)
    NoahowpmpIO%WSLAKE(:,:) = huge(1.0)
    NoahowpmpIO%runsrf_dt(:,:) = huge(1.0)
    NoahowpmpIO%ASAT(:,:) = huge(1.0)
    NoahowpmpIO%ISNOW(:,:) = huge(1)
    NoahowpmpIO%smc(:,:,:) = huge(1.0)
    NoahowpmpIO%smc_init(:,:,:) = huge(1.0)
    NoahowpmpIO%sice(:,:,:) = huge(1.0)
    NoahowpmpIO%sh2o(:,:,:) = huge(1.0)
    NoahowpmpIO%etrani(:,:,:) = huge(1.0)
    NoahowpmpIO%BTRANI(:,:,:) = huge(1.0)
    NoahowpmpIO%wcnd(:,:,:) = huge(1.0)
    NoahowpmpIO%fcr(:,:,:) = huge(1.0)
    NoahowpmpIO%FICEOLD(:,:,:) = huge(1.0)
    NoahowpmpIO%SNICE(:,:,:) = huge(1.0)
    NoahowpmpIO%SNLIQ(:,:,:) = huge(1.0)
    NoahowpmpIO%SNICEV(:,:,:) = huge(1.0)
    NoahowpmpIO%SNLIQV(:,:,:) = huge(1.0)
    NoahowpmpIO%FICE(:,:,:) = huge(1.0)
    NoahowpmpIO%EPORE(:,:,:) = huge(1.0)
    NoahowpmpIO%FSNO(:,:) = huge(1.0)
    NoahowpmpIO%BTRAN(:,:) = huge(1.0)

  end subroutine

  subroutine ParametersTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    associate(n_x => NoahowpmpIO%n_x, &
              n_y => NoahowpmpIO%n_y, &
              nsoil => NoahowpmpIO%nsoil &
              )

    if(.NOT.allocated(NoahowpmpIO%bexp)) allocate(NoahowpmpIO%bexp(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcmax)) allocate(NoahowpmpIO%smcmax(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcwlt)) allocate(NoahowpmpIO%smcwlt(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%smcref)) allocate(NoahowpmpIO%smcref(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%dksat)) allocate(NoahowpmpIO%dksat(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%dwsat)) allocate(NoahowpmpIO%dwsat(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%psisat)) allocate(NoahowpmpIO%psisat(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%bvic)) allocate(NoahowpmpIO%bvic(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%AXAJ)) allocate(NoahowpmpIO%AXAJ(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%BXAJ)) allocate(NoahowpmpIO%BXAJ(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%XXAJ)) allocate(NoahowpmpIO%XXAJ(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%BBVIC)) allocate(NoahowpmpIO%BBVIC(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%G)) allocate(NoahowpmpIO%G(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%QUARTZ)) allocate(NoahowpmpIO%QUARTZ(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%kdt)) allocate(NoahowpmpIO%kdt(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%frzx)) allocate(NoahowpmpIO%frzx(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%ZWT_INIT)) allocate(NoahowpmpIO%ZWT_INIT(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%urban_flag)) allocate(NoahowpmpIO%urban_flag(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%LAIM)) allocate(NoahowpmpIO%LAIM(n_x,n_y,12))
    if(.NOT.allocated(NoahowpmpIO%SAIM)) allocate(NoahowpmpIO%SAIM(n_x,n_y,12))
    if(.NOT.allocated(NoahowpmpIO%LAI)) allocate(NoahowpmpIO%LAI(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SAI)) allocate(NoahowpmpIO%SAI(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%CH2OP)) allocate(NoahowpmpIO%CH2OP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%NROOT)) allocate(NoahowpmpIO%NROOT(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%HVT)) allocate(NoahowpmpIO%HVT(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%HVB)) allocate(NoahowpmpIO%HVB(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%TMIN)) allocate(NoahowpmpIO%TMIN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SHDFAC)) allocate(NoahowpmpIO%SHDFAC(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SHDMAX)) allocate(NoahowpmpIO%SHDMAX(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0MVT)) allocate(NoahowpmpIO%Z0MVT(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RC)) allocate(NoahowpmpIO%RC(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%XL)) allocate(NoahowpmpIO%XL(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%BP)) allocate(NoahowpmpIO%BP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%FOLNMX)) allocate(NoahowpmpIO%FOLNMX(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%QE25)) allocate(NoahowpmpIO%QE25(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%VCMX25)) allocate(NoahowpmpIO%VCMX25(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%MP)) allocate(NoahowpmpIO%MP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RGL)) allocate(NoahowpmpIO%RGL(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RSMIN)) allocate(NoahowpmpIO%RSMIN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%HS)) allocate(NoahowpmpIO%HS(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%AKC)) allocate(NoahowpmpIO%AKC(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%AKO)) allocate(NoahowpmpIO%AKO(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%AVCMX)) allocate(NoahowpmpIO%AVCMX(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RSMAX)) allocate(NoahowpmpIO%RSMAX(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%CWP)) allocate(NoahowpmpIO%CWP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%C3PSN)) allocate(NoahowpmpIO%C3PSN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%DLEAF)) allocate(NoahowpmpIO%DLEAF(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%KC25)) allocate(NoahowpmpIO%KC25(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%KO25)) allocate(NoahowpmpIO%KO25(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%ELAI)) allocate(NoahowpmpIO%ELAI(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%ESAI)) allocate(NoahowpmpIO%ESAI(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%VAI)) allocate(NoahowpmpIO%VAI(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%VEG)) allocate(NoahowpmpIO%VEG(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%FVEG)) allocate(NoahowpmpIO%FVEG(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RHOL)) allocate(NoahowpmpIO%RHOL(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%RHOS)) allocate(NoahowpmpIO%RHOS(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUL)) allocate(NoahowpmpIO%TAUL(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUS)) allocate(NoahowpmpIO%TAUS(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%MFSNO)) allocate(NoahowpmpIO%MFSNO(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%ALBSAT)) allocate(NoahowpmpIO%ALBSAT(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBDRY)) allocate(NoahowpmpIO%ALBDRY(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBICE)) allocate(NoahowpmpIO%ALBICE(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBLAK)) allocate(NoahowpmpIO%ALBLAK(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%OMEGAS)) allocate(NoahowpmpIO%OMEGAS(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%EG)) allocate(NoahowpmpIO%EG(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TOPT)) allocate(NoahowpmpIO%TOPT(n_x,n_y))

    end associate

  end subroutine

  subroutine ParametersTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%bexp(:,:,:) = huge(1.0)
    NoahowpmpIO%smcmax(:,:,:) = huge(1.0)
    NoahowpmpIO%smcwlt(:,:,:) = huge(1.0)
    NoahowpmpIO%smcref(:,:,:) = huge(1.0)
    NoahowpmpIO%dksat(:,:,:) = huge(1.0)
    NoahowpmpIO%dwsat(:,:,:) = huge(1.0)
    NoahowpmpIO%psisat(:,:,:) = huge(1.0)
    NoahowpmpIO%bvic(:,:) = huge(1.0)
    NoahowpmpIO%AXAJ(:,:) = huge(1.0)
    NoahowpmpIO%BXAJ(:,:) = huge(1.0)
    NoahowpmpIO%XXAJ(:,:) = huge(1.0)
    NoahowpmpIO%BBVIC(:,:) = huge(1.0)
    NoahowpmpIO%G(:,:) = huge(1.0)
    NoahowpmpIO%QUARTZ(:,:) = huge(1.0)
    NoahowpmpIO%kdt(:,:) = huge(1.0)
    NoahowpmpIO%refkdt = huge(1.0)
    NoahowpmpIO%refdk = huge(1.0)
    NoahowpmpIO%csoil = huge(1.0)
    NoahowpmpIO%Z0 = huge(1.0)
    NoahowpmpIO%CZIL = huge(1.0)
    NoahowpmpIO%ZBOT = huge(1.0)
    NoahowpmpIO%frzx(:,:) = huge(1.0)
    NoahowpmpIO%slope = huge(1.0)
    NoahowpmpIO%timean = huge(1.0)
    NoahowpmpIO%fsatmx = huge(1.0)
    NoahowpmpIO%ZWT_INIT(:,:) = huge(1.0)
    NoahowpmpIO%urban_flag(:,:) = .FALSE.
    NoahowpmpIO%LAIM(:,:,:) = huge(1.0)
    NoahowpmpIO%SAIM(:,:,:) = huge(1.0)
    NoahowpmpIO%LAI(:,:) = huge(1.0)
    NoahowpmpIO%SAI(:,:) = huge(1.0)
    NoahowpmpIO%CH2OP(:,:) = huge(1.0)
    NoahowpmpIO%NROOT(:,:) = huge(1)
    NoahowpmpIO%HVT(:,:) = huge(1.0)
    NoahowpmpIO%HVB(:,:) = huge(1.0)
    NoahowpmpIO%TMIN(:,:) = huge(1.0)
    NoahowpmpIO%SHDFAC(:,:) = huge(1.0)
    NoahowpmpIO%SHDMAX(:,:) = huge(1.0)
    NoahowpmpIO%Z0MVT(:,:) = huge(1.0)
    NoahowpmpIO%RC(:,:) = huge(1.0)
    NoahowpmpIO%XL(:,:) = huge(1.0)
    NoahowpmpIO%BP(:,:) = huge(1.0)
    NoahowpmpIO%FOLNMX(:,:) = huge(1.0)
    NoahowpmpIO%QE25(:,:) = huge(1.0)
    NoahowpmpIO%VCMX25(:,:) = huge(1.0)
    NoahowpmpIO%MP(:,:) = huge(1.0)
    NoahowpmpIO%RGL(:,:) = huge(1.0)
    NoahowpmpIO%RSMIN(:,:) = huge(1.0)
    NoahowpmpIO%HS(:,:) = huge(1.0)
    NoahowpmpIO%AKC(:,:) = huge(1.0)
    NoahowpmpIO%AKO(:,:) = huge(1.0)
    NoahowpmpIO%AVCMX(:,:) = huge(1.0)
    NoahowpmpIO%RSMAX(:,:) = huge(1.0)
    NoahowpmpIO%CWP(:,:) = huge(1.0)
    NoahowpmpIO%C3PSN(:,:) = huge(1.0)
    NoahowpmpIO%DLEAF(:,:) = huge(1.0)
    NoahowpmpIO%KC25(:,:) = huge(1.0)
    NoahowpmpIO%KO25(:,:) = huge(1.0)
    NoahowpmpIO%ELAI(:,:) = huge(1.0)
    NoahowpmpIO%ESAI(:,:) = huge(1.0)
    NoahowpmpIO%VAI(:,:) = huge(1.0)
    NoahowpmpIO%VEG(:,:) = .FALSE.
    NoahowpmpIO%FVEG(:,:) = huge(1.0)
    NoahowpmpIO%RHOL(:,:,:) = huge(1.0)
    NoahowpmpIO%RHOS(:,:,:) = huge(1.0)
    NoahowpmpIO%TAUL(:,:,:) = huge(1.0)
    NoahowpmpIO%TAUS(:,:,:) = huge(1.0)
    NoahowpmpIO%ISURBAN = huge(1)
    NoahowpmpIO%ISWATER = huge(1)
    NoahowpmpIO%ISBARREN = huge(1)
    NoahowpmpIO%ISICE = huge(1)
    NoahowpmpIO%ISCROP = huge(1)
    NoahowpmpIO%EBLFOREST = huge(1)
    NoahowpmpIO%NATURAL = huge(1)
    NoahowpmpIO%LOW_DENSITY_RESIDENTIAL = huge(1)
    NoahowpmpIO%HIGH_DENSITY_RESIDENTIAL = huge(1)
    NoahowpmpIO%HIGH_INTENSITY_INDUSTRIAL = huge(1)
    NoahowpmpIO%SB = huge(1.0)
    NoahowpmpIO%VKC = huge(1.0)
    NoahowpmpIO%TFRZ = huge(1.0)
    NoahowpmpIO%HSUB = huge(1.0)
    NoahowpmpIO%HVAP = huge(1.0)
    NoahowpmpIO%HFUS = huge(1.0)
    NoahowpmpIO%CWAT = huge(1.0)
    NoahowpmpIO%CICE = huge(1.0)
    NoahowpmpIO%CPAIR = huge(1.0)
    NoahowpmpIO%TKWAT = huge(1.0)
    NoahowpmpIO%TKICE = huge(1.0)
    NoahowpmpIO%TKAIR = huge(1.0)
    NoahowpmpIO%RAIR = huge(1.0)
    NoahowpmpIO%RW = huge(1.0)
    NoahowpmpIO%DENH2O = huge(1.0)
    NoahowpmpIO%DENICE = huge(1.0)
    NoahowpmpIO%THKW = huge(1.0)
    NoahowpmpIO%THKO = huge(1.0)
    NoahowpmpIO%THKQTZ = huge(1.0)
    NoahowpmpIO%SSI = huge(1.0)
    NoahowpmpIO%MFSNO(:,:) = huge(1.0)
    NoahowpmpIO%Z0SNO = huge(1.0)
    NoahowpmpIO%SWEMX = huge(1.0)
    NoahowpmpIO%TAU0 = huge(1.0)
    NoahowpmpIO%GRAIN_GROWTH = huge(1.0)
    NoahowpmpIO%EXTRA_GROWTH = huge(1.0)
    NoahowpmpIO%DIRT_SOOT = huge(1.0)
    NoahowpmpIO%BATS_COSZ = huge(1.0)
    NoahowpmpIO%BATS_VIS_NEW = huge(1.0)
    NoahowpmpIO%BATS_NIR_NEW = huge(1.0)
    NoahowpmpIO%BATS_VIS_AGE = huge(1.0)
    NoahowpmpIO%BATS_NIR_AGE = huge(1.0)
    NoahowpmpIO%BATS_VIS_DIR = huge(1.0)
    NoahowpmpIO%BATS_NIR_DIR = huge(1.0)
    NoahowpmpIO%RSURF_SNOW = huge(1.0)
    NoahowpmpIO%RSURF_EXP = huge(1.0)
    NoahowpmpIO%ALBSAT(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBDRY(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBICE(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBLAK(:,:,:) = huge(1.0)
    NoahowpmpIO%OMEGAS(:,:,:) = huge(1.0)
    NoahowpmpIO%BETADS = huge(1.0)
    NoahowpmpIO%BETAIS = huge(1.0)
    NoahowpmpIO%EG(:,:,:) = huge(1.0)
    NoahowpmpIO%WSLMAX = huge(1.0)
    NoahowpmpIO%max_liq_mass_fraction = huge(1.0)
    NoahowpmpIO%SNOW_RET_FAC = huge(1.0)
    NoahowpmpIO%NBAND = huge(1)
    NoahowpmpIO%MPE = huge(1.0)
    NoahowpmpIO%TOPT(:,:) = huge(1.0)
    NoahowpmpIO%O2 = huge(1.0)
    NoahowpmpIO%CO2 = huge(1.0)
    NoahowpmpIO%PSIWLT = huge(1.0)
    NoahowpmpIO%TBOT = huge(1.0)
    NoahowpmpIO%GRAV = huge(1.0)
    NoahowpmpIO%rain_snow_thresh = huge(1.0)

  end subroutine

  subroutine OptionsTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    if(.NOT.allocated(NoahowpmpIO%opt_snf)) allocate(NoahowpmpIO%opt_snf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_run)) allocate(NoahowpmpIO%opt_run(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_drn)) allocate(NoahowpmpIO%opt_drn(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_inf)) allocate(NoahowpmpIO%opt_inf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_infdv)) allocate(NoahowpmpIO%opt_infdv(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%dveg)) allocate(NoahowpmpIO%dveg(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_alb)) allocate(NoahowpmpIO%opt_alb(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_rad)) allocate(NoahowpmpIO%opt_rad(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_sfc)) allocate(NoahowpmpIO%opt_sfc(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_crs)) allocate(NoahowpmpIO%opt_crs(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_crop)) allocate(NoahowpmpIO%opt_crop(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_stc)) allocate(NoahowpmpIO%opt_stc(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_tbot)) allocate(NoahowpmpIO%opt_tbot(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_frz)) allocate(NoahowpmpIO%opt_frz(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_btr)) allocate(NoahowpmpIO%opt_btr(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_rsf)) allocate(NoahowpmpIO%opt_rsf(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%opt_sub)) allocate(NoahowpmpIO%opt_sub(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

  end subroutine

  subroutine OptionsTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%opt_snf(:,:)       = huge(1)
    NoahowpmpIO%opt_run(:,:)       = huge(1)
    NoahowpmpIO%opt_drn(:,:)       = huge(1)
    NoahowpmpIO%opt_inf(:,:)       = huge(1)
    NoahowpmpIO%opt_infdv(:,:)     = huge(1)
    NoahowpmpIO%dveg(:,:)          = huge(1)
    NoahowpmpIO%opt_alb(:,:)       = huge(1)
    NoahowpmpIO%opt_rad(:,:)       = huge(1)
    NoahowpmpIO%opt_sfc(:,:)       = huge(1)
    NoahowpmpIO%opt_crs(:,:)       = huge(1)
    NoahowpmpIO%opt_crop(:,:)      = huge(1)
    NoahowpmpIO%opt_stc(:,:)       = huge(1)
    NoahowpmpIO%opt_tbot(:,:)      = huge(1)
    NoahowpmpIO%opt_frz(:,:)       = huge(1)
    NoahowpmpIO%opt_btr(:,:)       = huge(1)
    NoahowpmpIO%opt_rsf(:,:)       = huge(1)
    NoahowpmpIO%opt_sub(:,:)       = huge(1)

  end subroutine

  subroutine LevelsTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

  end subroutine

  subroutine LevelsTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    !NoahowpmpIO%nsoil    = huge(1)
    !NoahowpmpIO%nsnow    = huge(1)
    !NoahowpmpIO%nveg     = huge(1)

  end subroutine

  subroutine ForcingTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    associate(n_x => NoahowpmpIO%n_x, &
              n_y => NoahowpmpIO%n_y)

    if(.NOT.allocated(NoahowpmpIO%SFCPRS)) allocate(NoahowpmpIO%SFCPRS(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SFCTMP)) allocate(NoahowpmpIO%SFCTMP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2)) allocate(NoahowpmpIO%Q2(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCP)) allocate(NoahowpmpIO%PRCP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPCONV)) allocate(NoahowpmpIO%PRCPCONV(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPNONC)) allocate(NoahowpmpIO%PRCPNONC(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPSHCV)) allocate(NoahowpmpIO%PRCPSHCV(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPSNOW)) allocate(NoahowpmpIO%PRCPSNOW(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPGRPL)) allocate(NoahowpmpIO%PRCPGRPL(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%PRCPHAIL)) allocate(NoahowpmpIO%PRCPHAIL(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SOLDN)) allocate(NoahowpmpIO%SOLDN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%LWDN)) allocate(NoahowpmpIO%LWDN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%FOLN)) allocate(NoahowpmpIO%FOLN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%O2PP)) allocate(NoahowpmpIO%O2PP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%CO2PP)) allocate(NoahowpmpIO%CO2PP(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%UU)) allocate(NoahowpmpIO%UU(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%VV)) allocate(NoahowpmpIO%VV(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%TBOT)) allocate(NoahowpmpIO%TBOT(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%UR)) allocate(NoahowpmpIO%UR(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%THAIR)) allocate(NoahowpmpIO%THAIR(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%QAIR)) allocate(NoahowpmpIO%QAIR(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%EAIR)) allocate(NoahowpmpIO%EAIR(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%RHOAIR)) allocate(NoahowpmpIO%RHOAIR(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%FPICE)) allocate(NoahowpmpIO%FPICE(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SWDOWN)) allocate(NoahowpmpIO%SWDOWN(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%SOLAD)) allocate(NoahowpmpIO%SOLAD(n_x,n_y,2))
    if(.NOT.allocated(NoahowpmpIO%SOLAI)) allocate(NoahowpmpIO%SOLAI(n_x,n_y,2))

    end associate

  end subroutine ForcingTypeAllocate

  subroutine ForcingTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%SFCPRS(:,:)    = huge(1.0)
    NoahowpmpIO%SFCTMP(:,:)    = huge(1.0)
    NoahowpmpIO%Q2(:,:)        = huge(1.0)
    NoahowpmpIO%PRCP(:,:)      = huge(1.0)
    NoahowpmpIO%PRCPCONV(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPNONC(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPSHCV(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPSNOW(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPGRPL(:,:)  = huge(1.0)
    NoahowpmpIO%PRCPHAIL(:,:)  = huge(1.0)
    NoahowpmpIO%SOLDN(:,:)     = huge(1.0)
    NoahowpmpIO%LWDN(:,:)      = huge(1.0) 
    NoahowpmpIO%FOLN(:,:)      = huge(1.0) 
    NoahowpmpIO%O2PP(:,:)      = huge(1.0) 
    NoahowpmpIO%CO2PP(:,:)     = huge(1.0) 
    NoahowpmpIO%UU(:,:)        = huge(1.0)
    NoahowpmpIO%VV(:,:)        = huge(1.0)
    NoahowpmpIO%TBOT(:,:)      = huge(1.0)
    NoahowpmpIO%UR(:,:)        = huge(1.0)
    NoahowpmpIO%THAIR(:,:)     = huge(1.0)
    NoahowpmpIO%QAIR(:,:)      = huge(1.0)
    NoahowpmpIO%EAIR(:,:)      = huge(1.0)
    NoahowpmpIO%RHOAIR(:,:)    = huge(1.0)
    NoahowpmpIO%FPICE(:,:)     = huge(1.0)
    NoahowpmpIO%SWDOWN(:,:)    = huge(1.0)
    NoahowpmpIO%JULIAN         = huge(1.0)
    NoahowpmpIO%YEARLEN        = huge(1)
    NoahowpmpIO%SOLAD(:,:,:)   = huge(1.0)
    NoahowpmpIO%SOLAI(:,:,:)   = huge(1.0)

  end subroutine ForcingTypeDefault

  subroutine EnergyTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    associate(n_x   => NoahowpmpIO%n_x,   &
              n_y   => NoahowpmpIO%n_y,   &
              nsoil => NoahowpmpIO%nsoil, &
              nsnow => NoahowpmpIO%nsnow  &
             )

    if(.NOT.allocated(NoahowpmpIO%ALB)) allocate(NoahowpmpIO%ALB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ALBD)) allocate(NoahowpmpIO%ALBD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBGRD)) allocate(NoahowpmpIO%ALBGRD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBGRI)) allocate(NoahowpmpIO%ALBGRI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBI)) allocate(NoahowpmpIO%ALBI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBOLD)) allocate(NoahowpmpIO%ALBOLD(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ALBSND)) allocate(NoahowpmpIO%ALBSND(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%ALBSNI)) allocate(NoahowpmpIO%ALBSNI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%APAR)) allocate(NoahowpmpIO%APAR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%BGAP)) allocate(NoahowpmpIO%BGAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CAH2)) allocate(NoahowpmpIO%CAH2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CH)) allocate(NoahowpmpIO%CH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHB)) allocate(NoahowpmpIO%CHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHB2)) allocate(NoahowpmpIO%CHB2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHLEAF)) allocate(NoahowpmpIO%CHLEAF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHUC)) allocate(NoahowpmpIO%CHUC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHV)) allocate(NoahowpmpIO%CHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CHV2)) allocate(NoahowpmpIO%CHV2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CM)) allocate(NoahowpmpIO%CM(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMB)) allocate(NoahowpmpIO%CMB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%CMV)) allocate(NoahowpmpIO%CMV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%COSZ)) allocate(NoahowpmpIO%COSZ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%COSZ_HORIZ)) allocate(NoahowpmpIO%COSZ_HORIZ(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%DF)) allocate(NoahowpmpIO%DF(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%EAH)) allocate(NoahowpmpIO%EAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EHB2)) allocate(NoahowpmpIO%EHB2(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMG)) allocate(NoahowpmpIO%EMG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMISSI)) allocate(NoahowpmpIO%EMISSI(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EMV)) allocate(NoahowpmpIO%EMV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVB)) allocate(NoahowpmpIO%EVB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVC)) allocate(NoahowpmpIO%EVC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%EVG)) allocate(NoahowpmpIO%EVG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FABD)) allocate(NoahowpmpIO%FABD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FABI)) allocate(NoahowpmpIO%FABI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FACT)) allocate(NoahowpmpIO%FACT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%FAGE)) allocate(NoahowpmpIO%FAGE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FCEV)) allocate(NoahowpmpIO%FCEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FCTR)) allocate(NoahowpmpIO%FCTR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FGEV)) allocate(NoahowpmpIO%FGEV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FIRA)) allocate(NoahowpmpIO%FIRA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FREGD)) allocate(NoahowpmpIO%FREGD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREGI)) allocate(NoahowpmpIO%FREGI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREVD)) allocate(NoahowpmpIO%FREVD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FREVI)) allocate(NoahowpmpIO%FREVI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FROZEN_CANOPY)) allocate(NoahowpmpIO%FROZEN_CANOPY(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FROZEN_GROUND)) allocate(NoahowpmpIO%FROZEN_GROUND(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSA)) allocate(NoahowpmpIO%FSA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSH)) allocate(NoahowpmpIO%FSH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSHA)) allocate(NoahowpmpIO%FSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSR)) allocate(NoahowpmpIO%FSR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSRG)) allocate(NoahowpmpIO%FSRG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSRV)) allocate(NoahowpmpIO%FSRV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FSUN)) allocate(NoahowpmpIO%FSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%FTDD)) allocate(NoahowpmpIO%FTDD(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTDI)) allocate(NoahowpmpIO%FTDI(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTID)) allocate(NoahowpmpIO%FTID(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%FTII)) allocate(NoahowpmpIO%FTII(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%GAMMAG)) allocate(NoahowpmpIO%GAMMAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GAMMAV)) allocate(NoahowpmpIO%GAMMAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GH)) allocate(NoahowpmpIO%GH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GHB)) allocate(NoahowpmpIO%GHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%GHV)) allocate(NoahowpmpIO%GHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%HCPCT)) allocate(NoahowpmpIO%HCPCT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%ICE)) allocate(NoahowpmpIO%ICE(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IGS)) allocate(NoahowpmpIO%IGS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IMELT)) allocate(NoahowpmpIO%IMELT(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%IRB)) allocate(NoahowpmpIO%IRB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IRC)) allocate(NoahowpmpIO%IRC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%IRG)) allocate(NoahowpmpIO%IRG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LAISHA)) allocate(NoahowpmpIO%LAISHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LAISUN)) allocate(NoahowpmpIO%LAISUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEA)) allocate(NoahowpmpIO%LATHEA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEAG)) allocate(NoahowpmpIO%LATHEAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LATHEAV)) allocate(NoahowpmpIO%LATHEAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%LH)) allocate(NoahowpmpIO%LH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAH)) allocate(NoahowpmpIO%PAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHB)) allocate(NoahowpmpIO%PAHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHG)) allocate(NoahowpmpIO%PAHG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PAHV)) allocate(NoahowpmpIO%PAHV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PARSHA)) allocate(NoahowpmpIO%PARSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PARSUN)) allocate(NoahowpmpIO%PARSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSN)) allocate(NoahowpmpIO%PSN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSNSHA)) allocate(NoahowpmpIO%PSNSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%PSNSUN)) allocate(NoahowpmpIO%PSNSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q1)) allocate(NoahowpmpIO%Q1(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2B)) allocate(NoahowpmpIO%Q2B(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2E)) allocate(NoahowpmpIO%Q2E(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Q2V)) allocate(NoahowpmpIO%Q2V(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QMELT)) allocate(NoahowpmpIO%QMELT(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%QSFC)) allocate(NoahowpmpIO%QSFC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RB)) allocate(NoahowpmpIO%RB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RHO)) allocate(NoahowpmpIO%RHO(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%RHSUR)) allocate(NoahowpmpIO%RHSUR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSSHA)) allocate(NoahowpmpIO%RSSHA(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSSUN)) allocate(NoahowpmpIO%RSSUN(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%RSURF)) allocate(NoahowpmpIO%RSURF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SAG)) allocate(NoahowpmpIO%SAG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SAV)) allocate(NoahowpmpIO%SAV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHB)) allocate(NoahowpmpIO%SHB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHC)) allocate(NoahowpmpIO%SHC(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SHG)) allocate(NoahowpmpIO%SHG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%SSOIL)) allocate(NoahowpmpIO%SSOIL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%STC)) allocate(NoahowpmpIO%STC(NoahowpmpIO%n_x,NoahowpmpIO%n_y,-NoahowpmpIO%nsnow+1:NoahowpmpIO%nsoil))
    if(.NOT.allocated(NoahowpmpIO%T2M)) allocate(NoahowpmpIO%T2M(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%T2MB)) allocate(NoahowpmpIO%T2MB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%T2MV)) allocate(NoahowpmpIO%T2MV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAH)) allocate(NoahowpmpIO%TAH(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAU)) allocate(NoahowpmpIO%TAU(NoahowpmpIO%n_x,NoahowpmpIO%n_y,2))
    if(.NOT.allocated(NoahowpmpIO%TAUSS)) allocate(NoahowpmpIO%TAUSS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUX)) allocate(NoahowpmpIO%TAUX(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUXB)) allocate(NoahowpmpIO%TAUXB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUXV)) allocate(NoahowpmpIO%TAUXV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUY)) allocate(NoahowpmpIO%TAUY(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUYB)) allocate(NoahowpmpIO%TAUYB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TAUYV)) allocate(NoahowpmpIO%TAUYV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TG)) allocate(NoahowpmpIO%TG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGB)) allocate(NoahowpmpIO%TGB(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGS)) allocate(NoahowpmpIO%TGS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TGV)) allocate(NoahowpmpIO%TGV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TR)) allocate(NoahowpmpIO%TR(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TRAD)) allocate(NoahowpmpIO%TRAD(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TS)) allocate(NoahowpmpIO%TS(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%TV)) allocate(NoahowpmpIO%TV(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%WGAP)) allocate(NoahowpmpIO%WGAP(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0M)) allocate(NoahowpmpIO%Z0M(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0MG)) allocate(NoahowpmpIO%Z0MG(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%Z0WRF)) allocate(NoahowpmpIO%Z0WRF(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ZLVL)) allocate(NoahowpmpIO%ZLVL(NoahowpmpIO%n_x,NoahowpmpIO%n_y))
    if(.NOT.allocated(NoahowpmpIO%ZPD)) allocate(NoahowpmpIO%ZPD(NoahowpmpIO%n_x,NoahowpmpIO%n_y))

    end associate

  end subroutine EnergyTypeAllocate

  subroutine EnergyTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%ALB(:,:) = huge(1.0)
    NoahowpmpIO%ALBD(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBGRD(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBGRI(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBI(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBOLD(:,:) = huge(1.0)
    NoahowpmpIO%ALBSND(:,:,:) = huge(1.0)
    NoahowpmpIO%ALBSNI(:,:,:) = huge(1.0)
    NoahowpmpIO%APAR(:,:) = huge(1.0)
    NoahowpmpIO%BGAP(:,:) = huge(1.0)
    NoahowpmpIO%CAH2(:,:) = huge(1.0)
    NoahowpmpIO%CH(:,:) = huge(1.0)
    NoahowpmpIO%CHB(:,:) = huge(1.0)
    NoahowpmpIO%CHB2(:,:) = huge(1.0)
    NoahowpmpIO%CHLEAF(:,:) = huge(1.0)
    NoahowpmpIO%CHUC(:,:) = huge(1.0)
    NoahowpmpIO%CHV(:,:) = huge(1.0)
    NoahowpmpIO%CHV2(:,:) = huge(1.0)
    NoahowpmpIO%CM(:,:) = huge(1.0)
    NoahowpmpIO%CMB(:,:) = huge(1.0)
    NoahowpmpIO%CMV(:,:) = huge(1.0)
    NoahowpmpIO%COSZ(:,:) = huge(1.0)
    NoahowpmpIO%COSZ_HORIZ(:,:) = huge(1.0)
    NoahowpmpIO%DF(:,:,:) = huge(1.0)
    NoahowpmpIO%EAH(:,:) = huge(1.0)
    NoahowpmpIO%EHB2(:,:) = huge(1.0)
    NoahowpmpIO%EMG(:,:) = huge(1.0)
    NoahowpmpIO%EMISSI(:,:) = huge(1.0)
    NoahowpmpIO%EMV(:,:) = huge(1.0)
    NoahowpmpIO%EVB(:,:) = huge(1.0)
    NoahowpmpIO%EVC(:,:) = huge(1.0)
    NoahowpmpIO%EVG(:,:) = huge(1.0)
    NoahowpmpIO%FABD(:,:,:) = huge(1.0)
    NoahowpmpIO%FABI(:,:,:) = huge(1.0)
    NoahowpmpIO%FACT(:,:,:) = huge(1.0)
    NoahowpmpIO%FAGE(:,:) = huge(1.0)
    NoahowpmpIO%FCEV(:,:) = huge(1.0)
    NoahowpmpIO%FCTR(:,:) = huge(1.0)
    NoahowpmpIO%FGEV(:,:) = huge(1.0)
    NoahowpmpIO%FIRA(:,:) = huge(1.0)
    NoahowpmpIO%FREGD(:,:,:) = huge(1.0)
    NoahowpmpIO%FREGI(:,:,:) = huge(1.0)
    NoahowpmpIO%FREVD(:,:,:) = huge(1.0)
    NoahowpmpIO%FREVI(:,:,:) = huge(1.0)
    NoahowpmpIO%FROZEN_CANOPY(:,:) = .FALSE.
    NoahowpmpIO%FROZEN_GROUND(:,:) = .FALSE.
    NoahowpmpIO%FSA(:,:) = huge(1.0)
    NoahowpmpIO%FSH(:,:) = huge(1.0)
    NoahowpmpIO%FSHA(:,:) = huge(1.0)
    NoahowpmpIO%FSR(:,:) = huge(1.0)
    NoahowpmpIO%FSRG(:,:) = huge(1.0)
    NoahowpmpIO%FSRV(:,:) = huge(1.0)
    NoahowpmpIO%FSUN(:,:) = huge(1.0)
    NoahowpmpIO%FTDD(:,:,:) = huge(1.0)
    NoahowpmpIO%FTDI(:,:,:) = huge(1.0)
    NoahowpmpIO%FTID(:,:,:) = huge(1.0)
    NoahowpmpIO%FTII(:,:,:) = huge(1.0)
    NoahowpmpIO%GAMMAG(:,:) = huge(1.0)
    NoahowpmpIO%GAMMAV(:,:) = huge(1.0)
    NoahowpmpIO%GH(:,:) = huge(1.0)
    NoahowpmpIO%GHB(:,:) = huge(1.0)
    NoahowpmpIO%GHV(:,:) = huge(1.0)
    NoahowpmpIO%HCPCT(:,:,:) = huge(1.0)
    NoahowpmpIO%ICE(:,:) = huge(1)
    NoahowpmpIO%IGS(:,:) = huge(1.0)
    NoahowpmpIO%IMELT(:,:,:) = huge(1)
    NoahowpmpIO%IRB(:,:) = huge(1.0)
    NoahowpmpIO%IRC(:,:) = huge(1.0)
    NoahowpmpIO%IRG(:,:) = huge(1.0)
    NoahowpmpIO%LAISHA(:,:) = huge(1.0)
    NoahowpmpIO%LAISUN(:,:) = huge(1.0)
    NoahowpmpIO%LATHEA(:,:) = huge(1.0)
    NoahowpmpIO%LATHEAG(:,:) = huge(1.0)
    NoahowpmpIO%LATHEAV(:,:) = huge(1.0)
    NoahowpmpIO%LH(:,:) = huge(1.0)
    NoahowpmpIO%PAH(:,:) = huge(1.0)
    NoahowpmpIO%PAHB(:,:) = huge(1.0)
    NoahowpmpIO%PAHG(:,:) = huge(1.0)
    NoahowpmpIO%PAHV(:,:) = huge(1.0)
    NoahowpmpIO%PARSHA(:,:) = huge(1.0)
    NoahowpmpIO%PARSUN(:,:) = huge(1.0)
    NoahowpmpIO%PSN(:,:) = huge(1.0)
    NoahowpmpIO%PSNSHA(:,:) = huge(1.0)
    NoahowpmpIO%PSNSUN(:,:) = huge(1.0)
    NoahowpmpIO%Q1(:,:) = huge(1.0)
    NoahowpmpIO%Q2B(:,:) = huge(1.0)
    NoahowpmpIO%Q2E(:,:) = huge(1.0)
    NoahowpmpIO%Q2V(:,:) = huge(1.0)
    NoahowpmpIO%QMELT(:,:) = huge(1.0)
    NoahowpmpIO%QSFC(:,:) = huge(1.0)
    NoahowpmpIO%RB(:,:) = huge(1.0)
    NoahowpmpIO%RHO(:,:,:) = huge(1.0)
    NoahowpmpIO%RHSUR(:,:) = huge(1.0)
    NoahowpmpIO%RSSHA(:,:) = huge(1.0)
    NoahowpmpIO%RSSUN(:,:) = huge(1.0)
    NoahowpmpIO%RSURF(:,:) = huge(1.0)
    NoahowpmpIO%SAG(:,:) = huge(1.0)
    NoahowpmpIO%SAV(:,:) = huge(1.0)
    NoahowpmpIO%SHB(:,:) = huge(1.0)
    NoahowpmpIO%SHC(:,:) = huge(1.0)
    NoahowpmpIO%SHG(:,:) = huge(1.0)
    NoahowpmpIO%SSOIL(:,:) = huge(1.0)
    NoahowpmpIO%STC(:,:,:) = huge(1.0)
    NoahowpmpIO%T2M(:,:) = huge(1.0)
    NoahowpmpIO%T2MB(:,:) = huge(1.0)
    NoahowpmpIO%T2MV(:,:) = huge(1.0)
    NoahowpmpIO%TAH(:,:) = huge(1.0)
    NoahowpmpIO%TAU(:,:,:) = huge(1.0)
    NoahowpmpIO%TAUSS(:,:) = huge(1.0)
    NoahowpmpIO%TAUX(:,:) = huge(1.0)
    NoahowpmpIO%TAUXB(:,:) = huge(1.0)
    NoahowpmpIO%TAUXV(:,:) = huge(1.0)
    NoahowpmpIO%TAUY(:,:) = huge(1.0)
    NoahowpmpIO%TAUYB(:,:) = huge(1.0)
    NoahowpmpIO%TAUYV(:,:) = huge(1.0)
    NoahowpmpIO%TG(:,:) = huge(1.0)
    NoahowpmpIO%TGB(:,:) = huge(1.0)
    NoahowpmpIO%TGS(:,:) = huge(1.0)
    NoahowpmpIO%TGV(:,:) = huge(1.0)
    NoahowpmpIO%TR(:,:) = huge(1.0)
    NoahowpmpIO%TRAD(:,:) = huge(1.0)
    NoahowpmpIO%TS(:,:) = huge(1.0)
    NoahowpmpIO%TV(:,:) = huge(1.0)
    NoahowpmpIO%WGAP(:,:) = huge(1.0)
    NoahowpmpIO%Z0M(:,:) = huge(1.0)
    NoahowpmpIO%Z0MG(:,:) = huge(1.0)
    NoahowpmpIO%Z0WRF(:,:) = huge(1.0)
    NoahowpmpIO%ZLVL(:,:) = huge(1.0)
    NoahowpmpIO%ZPD(:,:) = huge(1.0)

  end subroutine EnergyTypeDefault

  subroutine DomainTypeAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    associate(n_x   => NoahowpmpIO%n_x,   &
              n_y   => NoahowpmpIO%n_y,   &
              nsoil => NoahowpmpIO%nsoil, &
              nsnow => NoahowpmpIO%nsnow  &
             )

    if(.NOT.allocated(NoahowpmpIO%lat))             allocate(NoahowpmpIO%lat(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%lon))             allocate(NoahowpmpIO%lon(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%ZREF))            allocate(NoahowpmpIO%ZREF(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%terrain_slope))   allocate(NoahowpmpIO%terrain_slope(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%azimuth))         allocate(NoahowpmpIO%azimuth(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%vegtyp))          allocate(NoahowpmpIO%vegtyp(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%isltyp))          allocate(NoahowpmpIO%isltyp(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%IST))             allocate(NoahowpmpIO%IST(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%croptype))        allocate(NoahowpmpIO%croptype(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%soilcolor))       allocate(NoahowpmpIO%soilcolor(n_x,n_y))
    if(.NOT.allocated(NoahowpmpIO%zsoil))           allocate(NoahowpmpIO%zsoil(n_x,n_y,nsoil))
    if(.NOT.allocated(NoahowpmpIO%dzsnso))          allocate(NoahowpmpIO%dzsnso(n_x,n_y,-nsnow+1:nsoil))
    if(.NOT.allocated(NoahowpmpIO%zsnso))           allocate(NoahowpmpIO%zsnso(n_x,n_y,-nsnow+1:nsoil))

    end associate

  end subroutine DomainTypeAllocate

  subroutine DomainTypeDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    NoahowpmpIO%dt                    = huge(1.0)
    NoahowpmpIO%startdate             = 'EMPTYDATE999'
    NoahowpmpIO%enddate               = 'EMPTYDATE999'
    NoahowpmpIO%nowdate               = 'EMPTYDATE999'
    NoahowpmpIO%start_datetime        = huge(1)
    NoahowpmpIO%end_datetime          = huge(1)
    NoahowpmpIO%curr_datetime         = huge(1)
    NoahowpmpIO%itime                 = huge(1) 
    NoahowpmpIO%ntime                 = huge(1) 
    NoahowpmpIO%time_dbl              = huge(1.d0)
    NoahowpmpIO%ix                    = huge(1)
    NoahowpmpIO%iy                    = huge(1)
    NoahowpmpIO%lat(:,:)              = huge(1.0)             
    NoahowpmpIO%lon(:,:)              = huge(1.0)           
    NoahowpmpIO%ZREF(:,:)             = huge(1.0)       
    NoahowpmpIO%terrain_slope(:,:)    = huge(1.0)   
    NoahowpmpIO%azimuth(:,:)          = huge(1.0)        
    NoahowpmpIO%vegtyp(:,:)           = huge(1)          
    NoahowpmpIO%croptype(:,:)         = huge(1)   
    NoahowpmpIO%isltyp(:,:)           = huge(1)  
    NoahowpmpIO%IST(:,:)              = huge(1)
    NoahowpmpIO%soilcolor(:,:)        = huge(1)          
    NoahowpmpIO%zsoil(:,:,:)          = huge(1.0)           
    NoahowpmpIO%dzsnso(:,:,:)         = huge(1.0)             
    NoahowpmpIO%zsnso(:,:,:)          = huge(1.0)          

  end subroutine DomainTypeDefault

  subroutine TableVarsAllocate(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO

    associate(MVT => NoahowpmpIO%MVT, &
              MBAND => NoahowpmpIO%MBAND, &
              MAX_SOILTYP => NoahowpmpIO%MAX_SOILTYP, &
              NCROP => NoahowpmpIO%NCROP, &
              MSC => NoahowpmpIO%MSC, &
              NSTAGE => NoahowpmpIO%NSTAGE &
             )

    if(.NOT.allocated(NoahowpmpIO%CH2OP_TABLE)) allocate(NoahowpmpIO%CH2OP_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%DLEAF_TABLE)) allocate(NoahowpmpIO%DLEAF_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%Z0MVT_TABLE)) allocate(NoahowpmpIO%Z0MVT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%HVT_TABLE)) allocate(NoahowpmpIO%HVT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%HVB_TABLE)) allocate(NoahowpmpIO%HVB_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%DEN_TABLE)) allocate(NoahowpmpIO%DEN_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RC_TABLE)) allocate(NoahowpmpIO%RC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%MFSNO_TABLE)) allocate(NoahowpmpIO%MFSNO_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%SCFFAC_TABLE)) allocate(NoahowpmpIO%SCFFAC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%SAIM_TABLE)) allocate(NoahowpmpIO%SAIM_TABLE(MVT,12))
    if(.NOT.allocated(NoahowpmpIO%LAIM_TABLE)) allocate(NoahowpmpIO%LAIM_TABLE(MVT,12))
    if(.NOT.allocated(NoahowpmpIO%SLA_TABLE)) allocate(NoahowpmpIO%SLA_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%DILEFC_TABLE)) allocate(NoahowpmpIO%DILEFC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%DILEFW_TABLE)) allocate(NoahowpmpIO%DILEFW_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%FRAGR_TABLE)) allocate(NoahowpmpIO%FRAGR_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%LTOVRC_TABLE)) allocate(NoahowpmpIO%LTOVRC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%C3PSN_TABLE)) allocate(NoahowpmpIO%C3PSN_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%KC25_TABLE)) allocate(NoahowpmpIO%KC25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%AKC_TABLE)) allocate(NoahowpmpIO%AKC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%KO25_TABLE)) allocate(NoahowpmpIO%KO25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%AKO_TABLE)) allocate(NoahowpmpIO%AKO_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%VCMX25_TABLE)) allocate(NoahowpmpIO%VCMX25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%AVCMX_TABLE)) allocate(NoahowpmpIO%AVCMX_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%BP_TABLE)) allocate(NoahowpmpIO%BP_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%MP_TABLE)) allocate(NoahowpmpIO%MP_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%QE25_TABLE)) allocate(NoahowpmpIO%QE25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%AQE_TABLE)) allocate(NoahowpmpIO%AQE_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RMF25_TABLE)) allocate(NoahowpmpIO%RMF25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RMS25_TABLE)) allocate(NoahowpmpIO%RMS25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RMR25_TABLE)) allocate(NoahowpmpIO%RMR25_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%ARM_TABLE)) allocate(NoahowpmpIO%ARM_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%FOLNMX_TABLE)) allocate(NoahowpmpIO%FOLNMX_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%TMIN_TABLE)) allocate(NoahowpmpIO%TMIN_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%XL_TABLE)) allocate(NoahowpmpIO%XL_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RHOL_TABLE)) allocate(NoahowpmpIO%RHOL_TABLE(MVT,MBAND))
    if(.NOT.allocated(NoahowpmpIO%RHOS_TABLE)) allocate(NoahowpmpIO%RHOS_TABLE(MVT,MBAND))
    if(.NOT.allocated(NoahowpmpIO%TAUL_TABLE)) allocate(NoahowpmpIO%TAUL_TABLE(MVT,MBAND))
    if(.NOT.allocated(NoahowpmpIO%TAUS_TABLE)) allocate(NoahowpmpIO%TAUS_TABLE(MVT,MBAND))
    if(.NOT.allocated(NoahowpmpIO%MRP_TABLE)) allocate(NoahowpmpIO%MRP_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%CWPVT_TABLE)) allocate(NoahowpmpIO%CWPVT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%WRRAT_TABLE)) allocate(NoahowpmpIO%WRRAT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%WDPOOL_TABLE)) allocate(NoahowpmpIO%WDPOOL_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%TDLEF_TABLE)) allocate(NoahowpmpIO%TDLEF_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%SHDFAC_TABLE)) allocate(NoahowpmpIO%SHDFAC_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%NROOT_TABLE)) allocate(NoahowpmpIO%NROOT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RGL_TABLE)) allocate(NoahowpmpIO%RGL_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RS_TABLE)) allocate(NoahowpmpIO%RS_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%HS_TABLE)) allocate(NoahowpmpIO%HS_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%TOPT_TABLE)) allocate(NoahowpmpIO%TOPT_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%RSMAX_TABLE)) allocate(NoahowpmpIO%RSMAX_TABLE(MVT))
    if(.NOT.allocated(NoahowpmpIO%BEXP_TABLE)) allocate(NoahowpmpIO%BEXP_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%SMCDRY_TABLE)) allocate(NoahowpmpIO%SMCDRY_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%F1_TABLE)) allocate(NoahowpmpIO%F1_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%SMCMAX_TABLE)) allocate(NoahowpmpIO%SMCMAX_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%SMCREF_TABLE)) allocate(NoahowpmpIO%SMCREF_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%PSISAT_TABLE)) allocate(NoahowpmpIO%PSISAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%DKSAT_TABLE)) allocate(NoahowpmpIO%DKSAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%DWSAT_TABLE)) allocate(NoahowpmpIO%DWSAT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%SMCWLT_TABLE)) allocate(NoahowpmpIO%SMCWLT_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%QUARTZ_TABLE)) allocate(NoahowpmpIO%QUARTZ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%BVIC_TABLE)) allocate(NoahowpmpIO%BVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%AXAJ_TABLE)) allocate(NoahowpmpIO%AXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%BXAJ_TABLE)) allocate(NoahowpmpIO%BXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%XXAJ_TABLE)) allocate(NoahowpmpIO%XXAJ_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%BDVIC_TABLE)) allocate(NoahowpmpIO%BDVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%GDVIC_TABLE)) allocate(NoahowpmpIO%GDVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%BBVIC_TABLE)) allocate(NoahowpmpIO%BBVIC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%SLOPE_TABLE)) allocate(NoahowpmpIO%SLOPE_TABLE(9))
    if(.NOT.allocated(NoahowpmpIO%ALBSAT_TABLE)) allocate(NoahowpmpIO%ALBSAT_TABLE(MSC,MBAND))
    if(.NOT.allocated(NoahowpmpIO%ALBDRY_TABLE)) allocate(NoahowpmpIO%ALBDRY_TABLE(MSC,MBAND))
    if(.NOT.allocated(NoahowpmpIO%ALBICE_TABLE)) allocate(NoahowpmpIO%ALBICE_TABLE(MBAND))
    if(.NOT.allocated(NoahowpmpIO%ALBLAK_TABLE)) allocate(NoahowpmpIO%ALBLAK_TABLE(MBAND))
    if(.NOT.allocated(NoahowpmpIO%OMEGAS_TABLE)) allocate(NoahowpmpIO%OMEGAS_TABLE(MBAND))
    if(.NOT.allocated(NoahowpmpIO%EG_TABLE)) allocate(NoahowpmpIO%EG_TABLE(2))
    if(.NOT.allocated(NoahowpmpIO%PLTDAY_TABLE)) allocate(NoahowpmpIO%PLTDAY_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%HSDAY_TABLE)) allocate(NoahowpmpIO%HSDAY_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%PLANTPOP_TABLE)) allocate(NoahowpmpIO%PLANTPOP_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%IRRI_TABLE)) allocate(NoahowpmpIO%IRRI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDTBASE_TABLE)) allocate(NoahowpmpIO%GDDTBASE_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDTCUT_TABLE)) allocate(NoahowpmpIO%GDDTCUT_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDS1_TABLE)) allocate(NoahowpmpIO%GDDS1_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDS2_TABLE)) allocate(NoahowpmpIO%GDDS2_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDS3_TABLE)) allocate(NoahowpmpIO%GDDS3_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDS4_TABLE)) allocate(NoahowpmpIO%GDDS4_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GDDS5_TABLE)) allocate(NoahowpmpIO%GDDS5_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%C3PSNI_TABLE)) allocate(NoahowpmpIO%C3PSNI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%KC25I_TABLE)) allocate(NoahowpmpIO%KC25I_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%AKCI_TABLE)) allocate(NoahowpmpIO%AKCI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%KO25I_TABLE)) allocate(NoahowpmpIO%KO25I_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%AKOI_TABLE)) allocate(NoahowpmpIO%AKOI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%VCMX25I_TABLE)) allocate(NoahowpmpIO%VCMX25I_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%AVCMXI_TABLE)) allocate(NoahowpmpIO%AVCMXI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%BPI_TABLE)) allocate(NoahowpmpIO%BPI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%MPI_TABLE)) allocate(NoahowpmpIO%MPI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%QE25I_TABLE)) allocate(NoahowpmpIO%QE25I_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%FOLNMXI_TABLE)) allocate(NoahowpmpIO%FOLNMXI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%C3C4_TABLE)) allocate(NoahowpmpIO%C3C4_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%AREF_TABLE)) allocate(NoahowpmpIO%AREF_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%PSNRF_TABLE)) allocate(NoahowpmpIO%PSNRF_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%I2PAR_TABLE)) allocate(NoahowpmpIO%I2PAR_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%TASSIM0_TABLE)) allocate(NoahowpmpIO%TASSIM0_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%TASSIM1_TABLE)) allocate(NoahowpmpIO%TASSIM1_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%TASSIM2_TABLE)) allocate(NoahowpmpIO%TASSIM2_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%K_TABLE)) allocate(NoahowpmpIO%K_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%EPSI_TABLE)) allocate(NoahowpmpIO%EPSI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%Q10MR_TABLE)) allocate(NoahowpmpIO%Q10MR_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%FOLN_MX_TABLE)) allocate(NoahowpmpIO%FOLN_MX_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%LEFREEZ_TABLE)) allocate(NoahowpmpIO%LEFREEZ_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%DILE_FC_TABLE)) allocate(NoahowpmpIO%DILE_FC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%DILE_FW_TABLE)) allocate(NoahowpmpIO%DILE_FW_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%FRA_GR_TABLE)) allocate(NoahowpmpIO%FRA_GR_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%LF_OVRC_TABLE)) allocate(NoahowpmpIO%LF_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%ST_OVRC_TABLE)) allocate(NoahowpmpIO%ST_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%RT_OVRC_TABLE)) allocate(NoahowpmpIO%RT_OVRC_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%LFMR25_TABLE)) allocate(NoahowpmpIO%LFMR25_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%STMR25_TABLE)) allocate(NoahowpmpIO%STMR25_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%RTMR25_TABLE)) allocate(NoahowpmpIO%RTMR25_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%GRAINMR25_TABLE)) allocate(NoahowpmpIO%GRAINMR25_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%LFPT_TABLE)) allocate(NoahowpmpIO%LFPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%STPT_TABLE)) allocate(NoahowpmpIO%STPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%RTPT_TABLE)) allocate(NoahowpmpIO%RTPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%GRAINPT_TABLE)) allocate(NoahowpmpIO%GRAINPT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%LFCT_TABLE)) allocate(NoahowpmpIO%LFCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%STCT_TABLE)) allocate(NoahowpmpIO%STCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%RTCT_TABLE)) allocate(NoahowpmpIO%RTCT_TABLE(NCROP,NSTAGE))
    if(.NOT.allocated(NoahowpmpIO%BIO2LAI_TABLE)) allocate(NoahowpmpIO%BIO2LAI_TABLE(NCROP))
    if(.NOT.allocated(NoahowpmpIO%TDSMCFAC_TABLE)) allocate(NoahowpmpIO%TDSMCFAC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_DC_TABLE)) allocate(NoahowpmpIO%TD_DC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_DEPTH_TABLE)) allocate(NoahowpmpIO%TD_DEPTH_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_DCOEF_TABLE)) allocate(NoahowpmpIO%TD_DCOEF_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_D_TABLE)) allocate(NoahowpmpIO%TD_D_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_ADEPTH_TABLE)) allocate(NoahowpmpIO%TD_ADEPTH_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_RADI_TABLE)) allocate(NoahowpmpIO%TD_RADI_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_SPAC_TABLE)) allocate(NoahowpmpIO%TD_SPAC_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%TD_DDRAIN_TABLE)) allocate(NoahowpmpIO%TD_DDRAIN_TABLE(MAX_SOILTYP))
    if(.NOT.allocated(NoahowpmpIO%KLAT_FAC_TABLE)) allocate(NoahowpmpIO%KLAT_FAC_TABLE(MAX_SOILTYP))  

    end associate

  end subroutine TableVarsAllocate

  subroutine TableVarsDefault(NoahowpmpIO)

    implicit none
    type(NoahowpmpIO_type), intent(inout) :: NoahowpmpIO        

    NoahowpmpIO%ISURBAN_TABLE = huge(1)
    NoahowpmpIO%ISWATER_TABLE = huge(1)
    NoahowpmpIO%ISBARREN_TABLE = huge(1)
    NoahowpmpIO%ISICE_TABLE = huge(1)
    NoahowpmpIO%ISCROP_TABLE = huge(1)
    NoahowpmpIO%EBLFOREST_TABLE = huge(1)
    NoahowpmpIO%NATURAL_TABLE = huge(1)
    NoahowpmpIO%LCZ_1_TABLE = huge(1)
    NoahowpmpIO%LCZ_2_TABLE = huge(1)
    NoahowpmpIO%LCZ_3_TABLE = huge(1)
    NoahowpmpIO%LCZ_4_TABLE = huge(1)
    NoahowpmpIO%LCZ_5_TABLE = huge(1)
    NoahowpmpIO%LCZ_6_TABLE = huge(1)
    NoahowpmpIO%LCZ_7_TABLE = huge(1)
    NoahowpmpIO%LCZ_8_TABLE = huge(1)
    NoahowpmpIO%LCZ_9_TABLE = huge(1)
    NoahowpmpIO%LCZ_10_TABLE = huge(1)
    NoahowpmpIO%LCZ_11_TABLE = huge(1)
    NoahowpmpIO%CH2OP_TABLE(:) = huge(1.0)
    NoahowpmpIO%DLEAF_TABLE(:) = huge(1.0)
    NoahowpmpIO%Z0MVT_TABLE(:) = huge(1.0)
    NoahowpmpIO%HVT_TABLE(:) = huge(1.0)
    NoahowpmpIO%HVB_TABLE(:) = huge(1.0)
    NoahowpmpIO%DEN_TABLE(:) = huge(1.0)
    NoahowpmpIO%RC_TABLE(:) = huge(1.0)
    NoahowpmpIO%MFSNO_TABLE(:) = huge(1.0)
    NoahowpmpIO%SCFFAC_TABLE(:) = huge(1.0)
    NoahowpmpIO%SAIM_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%LAIM_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%SLA_TABLE(:) = huge(1.0)
    NoahowpmpIO%DILEFC_TABLE(:) = huge(1.0)
    NoahowpmpIO%DILEFW_TABLE(:) = huge(1.0)
    NoahowpmpIO%FRAGR_TABLE(:) = huge(1.0)
    NoahowpmpIO%LTOVRC_TABLE(:) = huge(1.0)
    NoahowpmpIO%C3PSN_TABLE(:) = huge(1.0)
    NoahowpmpIO%KC25_TABLE(:) = huge(1.0)
    NoahowpmpIO%AKC_TABLE(:) = huge(1.0)
    NoahowpmpIO%KO25_TABLE(:) = huge(1.0)
    NoahowpmpIO%AKO_TABLE(:) = huge(1.0)
    NoahowpmpIO%VCMX25_TABLE(:) = huge(1.0)
    NoahowpmpIO%AVCMX_TABLE(:) = huge(1.0)
    NoahowpmpIO%BP_TABLE(:) = huge(1.0)
    NoahowpmpIO%MP_TABLE(:) = huge(1.0)
    NoahowpmpIO%QE25_TABLE(:) = huge(1.0)
    NoahowpmpIO%AQE_TABLE(:) = huge(1.0)
    NoahowpmpIO%RMF25_TABLE(:) = huge(1.0)
    NoahowpmpIO%RMS25_TABLE(:) = huge(1.0)
    NoahowpmpIO%RMR25_TABLE(:) = huge(1.0)
    NoahowpmpIO%ARM_TABLE(:) = huge(1.0)
    NoahowpmpIO%FOLNMX_TABLE(:) = huge(1.0)
    NoahowpmpIO%TMIN_TABLE(:) = huge(1.0)
    NoahowpmpIO%XL_TABLE(:) = huge(1.0)
    NoahowpmpIO%RHOL_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%RHOS_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%TAUL_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%TAUS_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%MRP_TABLE(:) = huge(1.0)
    NoahowpmpIO%CWPVT_TABLE(:) = huge(1.0)
    NoahowpmpIO%WRRAT_TABLE(:) = huge(1.0)
    NoahowpmpIO%WDPOOL_TABLE(:) = huge(1.0)
    NoahowpmpIO%TDLEF_TABLE(:) = huge(1.0)
    NoahowpmpIO%SHDFAC_TABLE(:) = huge(1.0)
    NoahowpmpIO%NROOT_TABLE(:) = huge(1.0)
    NoahowpmpIO%RGL_TABLE(:) = huge(1.0)
    NoahowpmpIO%RS_TABLE(:) = huge(1.0)
    NoahowpmpIO%HS_TABLE(:) = huge(1.0)
    NoahowpmpIO%TOPT_TABLE(:) = huge(1.0)
    NoahowpmpIO%RSMAX_TABLE(:) = huge(1.0)
    NoahowpmpIO%SLCATS = huge(1)
    NoahowpmpIO%BEXP_TABLE(:) = huge(1.0)
    NoahowpmpIO%SMCDRY_TABLE(:) = huge(1.0)
    NoahowpmpIO%F1_TABLE(:) = huge(1.0)
    NoahowpmpIO%SMCMAX_TABLE(:) = huge(1.0)
    NoahowpmpIO%SMCREF_TABLE(:) = huge(1.0)
    NoahowpmpIO%PSISAT_TABLE(:) = huge(1.0)
    NoahowpmpIO%DKSAT_TABLE(:) = huge(1.0)
    NoahowpmpIO%DWSAT_TABLE(:) = huge(1.0)
    NoahowpmpIO%SMCWLT_TABLE(:) = huge(1.0)
    NoahowpmpIO%QUARTZ_TABLE(:) = huge(1.0)
    NoahowpmpIO%BVIC_TABLE(:) = huge(1.0)
    NoahowpmpIO%AXAJ_TABLE(:) = huge(1.0)
    NoahowpmpIO%BXAJ_TABLE(:) = huge(1.0)
    NoahowpmpIO%XXAJ_TABLE(:) = huge(1.0)
    NoahowpmpIO%BDVIC_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDVIC_TABLE(:) = huge(1.0)
    NoahowpmpIO%BBVIC_TABLE(:) = huge(1.0)
    NoahowpmpIO%SLOPE_TABLE(:) = huge(1.0)
    NoahowpmpIO%CSOIL_TABLE = huge(1.0)
    NoahowpmpIO%REFDK_TABLE = huge(1.0)
    NoahowpmpIO%REFKDT_TABLE = huge(1.0)
    NoahowpmpIO%FRZK_TABLE = huge(1.0)
    NoahowpmpIO%ZBOT_TABLE = huge(1.0)
    NoahowpmpIO%CZIL_TABLE = huge(1.0)
    NoahowpmpIO%Z0_TABLE = huge(1.0)
    NoahowpmpIO%ALBSAT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%ALBDRY_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%ALBICE_TABLE(:) = huge(1.0)
    NoahowpmpIO%ALBLAK_TABLE(:) = huge(1.0)
    NoahowpmpIO%OMEGAS_TABLE(:) = huge(1.0)
    NoahowpmpIO%BETADS_TABLE = huge(1.0)
    NoahowpmpIO%BETAIS_TABLE = huge(1.0)
    NoahowpmpIO%EG_TABLE(:) = huge(1.0)
    NoahowpmpIO%CO2_TABLE = huge(1.0)
    NoahowpmpIO%O2_TABLE = huge(1.0)
    NoahowpmpIO%TIMEAN_TABLE = huge(1.0)
    NoahowpmpIO%FSATMX_TABLE = huge(1.0)
    NoahowpmpIO%Z0SNO_TABLE = huge(1.0)
    NoahowpmpIO%SSI_TABLE = huge(1.0)
    NoahowpmpIO%SNOW_RET_FAC_TABLE = huge(1.0)
    NoahowpmpIO%SNOW_EMIS_TABLE = huge(1.0)
    NoahowpmpIO%SWEMX_TABLE = huge(1.0)
    NoahowpmpIO%TAU0_TABLE = huge(1.0)
    NoahowpmpIO%GRAIN_GROWTH_TABLE = huge(1.0)
    NoahowpmpIO%EXTRA_GROWTH_TABLE = huge(1.0)
    NoahowpmpIO%DIRT_SOOT_TABLE = huge(1.0)
    NoahowpmpIO%BATS_COSZ_TABLE = huge(1.0)
    NoahowpmpIO%BATS_VIS_NEW_TABLE = huge(1.0)
    NoahowpmpIO%BATS_NIR_NEW_TABLE = huge(1.0)
    NoahowpmpIO%BATS_VIS_AGE_TABLE = huge(1.0)
    NoahowpmpIO%BATS_NIR_AGE_TABLE = huge(1.0)
    NoahowpmpIO%BATS_VIS_DIR_TABLE = huge(1.0)
    NoahowpmpIO%BATS_NIR_DIR_TABLE = huge(1.0)
    NoahowpmpIO%RSURF_SNOW_TABLE = huge(1.0)
    NoahowpmpIO%RSURF_EXP_TABLE = huge(1.0)
    NoahowpmpIO%DEFAULT_CROP_TABLE = huge(1)
    NoahowpmpIO%PLTDAY_TABLE(:) = huge(1)
    NoahowpmpIO%HSDAY_TABLE(:) = huge(1)
    NoahowpmpIO%PLANTPOP_TABLE(:) = huge(1.0)
    NoahowpmpIO%IRRI_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDTBASE_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDTCUT_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDS1_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDS2_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDS3_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDS4_TABLE(:) = huge(1.0)
    NoahowpmpIO%GDDS5_TABLE(:) = huge(1.0)
    NoahowpmpIO%C3PSNI_TABLE(:) = huge(1.0)
    NoahowpmpIO%KC25I_TABLE(:) = huge(1.0)
    NoahowpmpIO%AKCI_TABLE(:) = huge(1.0)
    NoahowpmpIO%KO25I_TABLE(:) = huge(1.0)
    NoahowpmpIO%AKOI_TABLE(:) = huge(1.0)
    NoahowpmpIO%VCMX25I_TABLE(:) = huge(1.0)
    NoahowpmpIO%AVCMXI_TABLE(:) = huge(1.0)
    NoahowpmpIO%BPI_TABLE(:) = huge(1.0)
    NoahowpmpIO%MPI_TABLE(:) = huge(1.0)
    NoahowpmpIO%QE25I_TABLE(:) = huge(1.0)
    NoahowpmpIO%FOLNMXI_TABLE(:) = huge(1.0)
    NoahowpmpIO%C3C4_TABLE(:) = huge(1)
    NoahowpmpIO%AREF_TABLE(:) = huge(1.0)
    NoahowpmpIO%PSNRF_TABLE(:) = huge(1.0)
    NoahowpmpIO%I2PAR_TABLE(:) = huge(1.0)
    NoahowpmpIO%TASSIM0_TABLE(:) = huge(1.0)
    NoahowpmpIO%TASSIM1_TABLE(:) = huge(1.0)
    NoahowpmpIO%TASSIM2_TABLE(:) = huge(1.0)
    NoahowpmpIO%K_TABLE(:) = huge(1.0)
    NoahowpmpIO%EPSI_TABLE(:) = huge(1.0)
    NoahowpmpIO%Q10MR_TABLE(:) = huge(1.0)
    NoahowpmpIO%FOLN_MX_TABLE(:) = huge(1.0)
    NoahowpmpIO%LEFREEZ_TABLE(:) = huge(1.0)
    NoahowpmpIO%DILE_FC_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%DILE_FW_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%FRA_GR_TABLE(:) = huge(1.0)
    NoahowpmpIO%LF_OVRC_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%ST_OVRC_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%RT_OVRC_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%LFMR25_TABLE(:) = huge(1.0)
    NoahowpmpIO%STMR25_TABLE(:) = huge(1.0)
    NoahowpmpIO%RTMR25_TABLE(:) = huge(1.0)
    NoahowpmpIO%GRAINMR25_TABLE(:) = huge(1.0)
    NoahowpmpIO%LFPT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%STPT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%RTPT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%GRAINPT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%LFCT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%STCT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%RTCT_TABLE(:,:) = huge(1.0)
    NoahowpmpIO%BIO2LAI_TABLE(:) = huge(1.0)
    NoahowpmpIO%TDSMCFAC_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_DC_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_DEPTH_TABLE(:) = huge(1)
    NoahowpmpIO%DRAIN_LAYER_OPT_TABLE = huge(1)
    NoahowpmpIO%TD_DCOEF_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_D_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_ADEPTH_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_RADI_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_SPAC_TABLE(:) = huge(1.0)
    NoahowpmpIO%TD_DDRAIN_TABLE(:) = huge(1.0)
    NoahowpmpIO%KLAT_FAC_TABLE(:) = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_b = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_c = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_d = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_e = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_f = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500t_g = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_1500_b = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_b = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_c = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_d = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_e = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_f = huge(1.0)
    NoahowpmpIO%sr2006_theta_33t_g = huge(1.0)
    NoahowpmpIO%sr2006_theta_33_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_33_b = huge(1.0)
    NoahowpmpIO%sr2006_theta_33_c = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_b = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_c = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_d = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_e = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_f = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33t_g = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33_a = huge(1.0)
    NoahowpmpIO%sr2006_theta_s33_b = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_a = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_b = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_c = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_d = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_e = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_f = huge(1.0)
    NoahowpmpIO%sr2006_psi_et_g = huge(1.0)
    NoahowpmpIO%sr2006_psi_e_a = huge(1.0)
    NoahowpmpIO%sr2006_psi_e_b = huge(1.0)
    NoahowpmpIO%sr2006_psi_e_c = huge(1.0)
    NoahowpmpIO%sr2006_smcmax_a = huge(1.0)
    NoahowpmpIO%sr2006_smcmax_b = huge(1.0)
    
  end subroutine TableVarsDefault

end module NoahowpmpIOTypeInitModule